== Preface

That feeling inherent in our nature, which loves to remember and to be remembered,
having, in many instances,
tended to the improvement as well as entertainment of those who
prefer the narrative dictated by truth to works of imagination;
and the taste of the present day, more than of some of former ages,
seeming to favour this judicious choice;
the compiler has been encouraged in a persuasion, that,
instead of confining to their own descendants,
these memoirs and sentiments of an exemplary couple,
they may be usefully introduced into more public view, and the memory thus preserved,
of those virtues which graced the sphere allotted to them.

A considerable number of letters, or extracts from letters,
addressed by the late Richard Shackleton to some of his numerous friends,
have already been submitted to the public eye, principally collected by his worthy,
much-valued contemporary, John Kendall;
by which his talents for epistolary converse have been evinced,
in a way that it is hoped will favourably dispose
many readers to receive the present volume.

The few letters of Elizabeth Shackleton here offered,
though not the product of what may be accounted shining endowments,
are so fraught with virtuous sentiments and just distinctions,
as may sufficiently warrant their publication.
Nor can it be doubted that the development of the character of their revered father,
the elder Abraham Shackleton, will prove equally interesting and instructive.

Various anecdotes and allusions, respecting other individuals, amongst relations,
family connections, and friends, are also interspersed,
as being too immediately connected with the principal subjects to admit of exclusion.

The circumstances of the prominent characters in this little work,
being closely interwoven, the editor has generally adopted a chronological order,
considering that the advantage resulting from this,
will be paramount to any inconvenience which may arise from a broken narrative.
