== Chapter I.

Birth of Richard Shackleton--Some account of his parents-- Circumstances attendant on
Richard Shackleton`'s youth--His marriage--Extracts from letters--Decease of his wife

Richard Shackleton was born in Ballitore, on the 9th of the 10th month, 1726.
His grandfather, whose name he bore, was a native of Yorkshire, where he married,
in the year 1683, Sarah Briggs.
Of their six children, Abraham, born in 1696, was the youngest.
His mother died when he was six years of age, his father two years afterwards.
Though deprived so early of religious parents, the impression made on him,
by their careful education, was not in vain.
He used frequently to mention the tender concern of his pious father, who,
following him to his bedside, was wont, on leaving him to his repose,
awfully to recommend him to seek the Divine blessing.
And that blessing did remarkably attend him during the course of his life;
for whilst as yet very young, and exposed to manifold dangers,
he was enabled to preserve the tenderness and innocence
which constitute the happiness of childhood;
and often, retiring from his companions, he mused in solitude on the love of his Maker.
In his youth, he underwent great exercise and conflicts;
but persevering in the strait path of duty, and yielding obedience to the Divine monitor,
through every stage of life the same protection was extended,
as the same watchful care to seek after it was maintained.

His bodily frame not being robust,
after having made trial of other means of gaining a livelihood, he resigned them,
and cultivated his natural taste for literature.
Though he was twenty years of age when he began to learn the Latin language, yet,
with genius and application united, he speedily became a good classical scholar,
and even wrote pure and elegant Latin.
His acquirements, his diligence, and still more his character,
induced some of the most respectable families of the Society of Friends in Ireland,
(of which religious body he was himself a member,)
to encourage him to come into this country,
and undertake the tuition of their children.
He first engaged in the employment of a private teacher;
and in great simplicity of heart, and awful fear, discharged his important trust,
greatly to the satisfaction of his employers.
Having, before his removal, been a teacher in the school of David Hall, of Skipton,
in Yorkshire, he there became acquainted with Margaret Wilkinson,
first cousin to David Hall, an inmate in his family, and daughter of Richard Wilkinson,
of Knowlbank, in Yorkshire.
She was pleasing in person and manners, cheerful, of a sweet temper,
and endowed with good sense;
but what attracted and confirmed Abraham Shackleton`'s affection to her,
was the excellence of her humble and pious spirit.
He loved her with a true love, and, in a few years, returned to England, solicited,
and obtained her hand.
Those friends who had had trial of his abilities as a private teacher,
and who saw the advantages accruing to the youth, from such an example as his,
were glad to find he had determined to settle in Ireland, and to open a boarding-school.
They, probably, suggested the idea to him, for he was of a diffident disposition.
Ballitore seemed to be a suitable place for this purpose,
a retired village in the county of Kildare, twenty-eight miles south of Dublin,
the river Griese, a pleasant stream,
running through the valley in which the village stands,
and contributing to its salubrity.
It was a situation, also,
which gratified Abraham Shackleton`'s inclination for the country,
and his love of agriculture and planting.
Hither, then, he brought his beloved Margaret.
Here they passed their peaceful, pious lives;
here shone the steady lustre of their bright example;
and here they laid down their heads in a good old age.
But their virtues left behind a sweet odour, when their places knew them no more;
and their memories are handed down with respect and love, from one generation to another.

The boarding-school was opened on the 1st of the 3rd month, 1726,
and succeeded beyond the humble hopes of its conductors;
so that not only those of their own society, and of the middle rank,
but many persons of considerable note, and of various denominations,
placed their children under their care; several of whom, afterwards,
filled conspicuous stations in life;
and many not only retained a grateful and affectionate
respect for the memory of their preceptor,
but good-will and regard for the Society of Friends, on his account;
remembering his extraordinary diligence and care in their tuition,
his fatherly oversight of them, and also the living lesson of uprightness, temperance,
gravity, and humility, which he taught by his example.

And there is ground to believe,
that the principles of the people called Quakers were better understood,
and that many illiberal prejudices against them were removed,
by means of Ballitore School.
Amongst the scholars of Abraham Shackleton,
one of the most distinguished for early attainments in literature, was Edmund Burke, who,
with Garrett, and Richard, his brothers, was placed under his care, in the year 1741.
Edmund, being then about eleven years of age, manifested uncommon genius,
with qualities which shelter that "`painful preeminence`" from those envious blasts,
which annoy even when they cannot injure; for he was unassuming, affable, and modest.
He and Richard Shackleton, the son of Abraham, pursued their studies together.
The minds of both were strongly bent to literary acquirements;
both were endowed with a classical taste, solid judgment, and keen perceptions;
and with similar dispositions, cheerful, affectionate, and benevolent.

Between these kindred minds a friendship was formed, which continued through life,
notwithstanding the different spheres in which they moved.
When they met afterwards,
Edmund Burke delighted to converse with the friend of his youth,
on subjects that recalled their juvenile days.
In private life, he was distinguished by the practice of the domestic and social virtues,
and by exemplary moral conduct.
His manners and conversation were engaging and instructive;
clothed with a simplicity which softened the brilliancy of his talents,
and made him even more beloved than admired.

Michael Kearney was another of Abraham Shackleton`'s pupils, a native of Dublin;
a person of acknowledged worth and learning,
and as remarkable for his modesty as for his acquirements.
At the age of eighty, he gave proof, by a few lines addressed to one of the family,
of the permanency of that friendship, which,
springing from the soil of innocent and cultivated minds, produces blossoms and fruits,
to gladden the heart in youth and in age.
"`A renewal,`" says he, "`however slight, of a correspondence with Ballitore,
excited a most affecting pulsation in my heart: it attracted my attention to old times,
when I was accustomed to receive letters from your father,
to whom I am indebted for much instruction in what is laudable and excellent.`"
Speaking of the pleasure with which he read a description of Ballitore in verse, he adds,
"`It bestowed on me a momentary youth.
I recollected the haunts of my boyhood with inexpressible pleasure,
and retraced events that had occurred on every spot.
The cowslips of the Mill-field were not forgotten,
and many instructive conversations with your father started into my mind.`"
It was not the recollection of hours spent with his friend in idleness, folly,
or mischievous frolics, which was presented to his memory;
but through the long retrospect of much more than half a century,
this venerable man could pleasantly contemplate their past studies and recreations.
The cultivation of taste and science is favourable
to the preservation of purity in conduct and sentiment;
and though there are lamentable instances of fine talents being laid waste, and,
instead of raising a goodly and useful structure, affording, by their ruin,
a shelter to the beasts of prey and birds of night;
yet the generality of the dissipated and profligate,
appear to be those who have neglected or despised the improvement of their own abilities,
and endeavoured to depreciate those intellectual powers and accomplishments,
which they were either unwilling or unable to comprehend; who, in, the words of Gay,

"`O`'erlook with scorn all virtuous arts;

For vice is fitted to their parts.`"

When Richard Shackleton was but five years old,
his heart experienced the touches of Divine love;
and he sometimes withdrew to a retired spot, where he poured out his soul in prayer,
and was permitted to approach Him who said, "`Suffer little children to come unto me.`"
Often did he look back upon this time, and the scene of these early aspirations,
which seemed hallowed in his view.
It was a precious period of his life when he was led to enter into
covenant with his Maker--when he walked out alone with his Bible,
and poured out his prayers and his tears,
being favoured with that heavenly feeling which surpasses every other enjoyment;
and this tenderness continued, with very little interruption,
to operate on his mind till the sixteenth year of his age.

On his arriving at this critical period of life, the levity incident to youth,
and his own natural vivacity, drew him, in degree,
from that watchfulness enjoined by the highest authority,
and on which our safety and happiness depend;
and though preserved within the bounds of morality,
the religious sensibility experienced in early life was weakened.
This lapse, though it had been long recovered, he regretted,
when about to close his exemplary life.
He was very diligent in seeking after improvement in literary knowledge; and,
while yet a child, was able to assist his father.
For this purpose he spent some time in Dublin, attending lectures at the college,
and learning the Hebrew language.
The pious care exercised over him, when absent from his parents,
will appear by the following extracts from letters written to him by his father.

1744+++.+++ Keep thy mind as quiet as possible,
so that thou mayst have benefit of this little tour.
I desire thou mayst have thy eye to Him that hath preserved, in some degree,
him that writeth, and is his chiefest joy.
Next to that, my joy is that mine may walk acceptably before Him.
Durable riches, I know, and honours, are in his right hand,
which He dispenses impartially, in his own fit time.

[.asterism]
'''

1748+++.+++ We are very desirous of seeing thee at home, for several reasons;
and yet very loath to interrupt thee in that in which thou proposest to thyself an advantage,
or, at least, a satisfaction; for thou mayst assure thyself,
whilst thou continuest to eye the best things, thou art and wilt be near to me.

My dear son, that gracious hand that dispenses divine favours liberally,
hath not been wanting to my mind, since thou left us,
and thou hast been nearly remembered by me; and my desires are,
that thou mayst often participate of those riches and treasures that add no sorrow,
but give the soul dominion over all lower enjoyments.
This sifting, winnowing, purging, cleansing hand,
that would make room for itself---that would leave nothing but the pure,
weighty grain--bring every thought, word, and action to judgment;
may it be attended upon, and, when retired and withdrawn, patiently waited for.
Experience tells us here, too, that the prodigal must know want.

[.asterism]
'''

Thou hast been pretty much in my mind since we parted,
and I have often remembered that portion of Scripture: "`The refining pot is for silver,
and the furnace for gold.`"
Various are the probations that are permitted to fall to our share, in this vale of tears.
I cannot think but, if it be not our own fault, they may turn to our lasting advantage,
in purging away the dross, the tin, and the reprobate silver.
The more deep the trials, the more severe and heavy the refining,
reforming hand presses on our souls; the more high they may rise in acceptance,
and have the more sensible enjoyments; and then may the soul bow,
in the depth of humility, to the root,
and know its dependance on that from whence living nourishment springs.
Surely, the all-wise God hath, for a wise and blessed end,
dispensed day and night to our souls, as well as to the outward creation,
to engage and enamour our souls to love Him.
1748.

Richard Shackleton very early in life became attached to Elizabeth,
youngest daughter of Henry and Deborah Fuller;^
footnote:[Deborah Fuller was the daughter of John Barcroft,
one of the proprietors of the lands of Ballitore, and Elizabeth, his wife,
who was an acceptable minister.
She died in 1740, having survived her husband several years.
Near the close of life, she overflowed in sweet counsel to her children,
and testified of her early experience of the Lord`'s goodness,
which had been continued through life.]
and having his parents`' entire approbation of his choice,
he applied for her hand about the twenty-second year of his age.
The state of his mind at that time, is best expressed in his own words,
as he related it to a dear friend.
"`I received a kind of refusal, which I took;
my mind being awakened in a most extraordinary manner,
from the time of my application to that period, and possessed with doubt and dread,
so that I feared, if we went together, the divine blessing would not crown our union.
In this season I sought solitary places to weep in, and pour out my tears to the Lord.
Many wondered that I took the disappointment so to heart,
supposing my dejection to proceed from that.
I let them suppose what they would, and being favoured to keep inward,
my covenants were renewed.
In about six months from this time, I found a liberty to renew my suit.`"

They were married the 2nd of 2nd month, 1749, and settled in a pleasant dwelling,
in the village near their parents,
who looked forward with joyful hope to future prospects for their children,
whom they beheld walking in the path which leads to happiness.

About this time, a little band, young in years,
but increasing in the experience of those things which belong to peace,
became closely united.
Amongst these, Mary Peisley, Samuel Neale, Elizabeth Pike,
Richard Shackleton and his wife, and Elizabeth Carleton, often met,
and were a strength and encouragement to each other.
Their union is expressed thus, in a letter from Richard Shackleton to Samuel Neale:
"`My cry was today, dear friend! for us who are young, who are known by one another,
to have good desires begotten in us for the blessed cause, that we might be preserved,
and plentifully filled with divine wisdom, of which I saw a great necessity,
that the Lord would take us, being children, and teach us himself;
and that we might be drawn into near unity with one another.`"
Samuel Neale, who had been forgiven much, loved much;
and having been obedient to the heavenly vision, became a vessel of honour,
replenished with good, and pouring it forth for the refreshment of ethers.
He was one, who, remembering the trials which attend youth, compassionated them;
and in advanced life, his winning affability towards young persons,
his fatherly love and care, his heart and house open to receive them,
made a deep impression on their minds, from which many received lasting advantage.

The following extracts from letters written in the year 1752,
instructively depict the state of Richard Shackleton`'s mind at this period.

7th of 4th Month.

Had I kept, as I believe thou dost, to my first love,
and not suffered the wisdom of the fallen nature to blind and deafen, and, in appearance,
almost totally quench in me the second Adam, which is a quickening spirit,
I should not now be without true wisdom, in a captious, deceitful world.
May the harms of others teach thee to beware.
Prize, O prize, the jewel which I believe thou art possessed of.
It is indeed the pearl of price.
I should rather possess the least portion of it, than all the wisdom of this world.
Knowledge, indeed, puffeth up; but charity, which is this pure love, edifieth.
Take William Penn`'s advice to his children: "`Part with all for it,
but part not with it for all the world.`"

[.asterism]
'''

14th of 6th Month.

I have had a pretty deal of Mary Peisly`'s company since my last.
She proves, by her conversation, that text,
"`The words of the wise are as nails fastened in a sure place.`"
As there is no company so agreeable to me as that of such dear instruments,
I find myself not out of danger in indulging myself in it.
My mind is too apt to be drawn out in these opportunities, from a still, quiet frame,
into a flutter and commotion;
and the affections of the creature to steal gradually
into the room of the pure love of the Creator,
who is ever jealous of his just right: and this wounds the life,
and defeats the true satisfaction and benefit which might accrue from such conversation;
and instead of parting from our friends with a sweet savour,
we make that parting doubly uneasy,
by losing the company of the invisible as well as visible friend.

[.asterism]
'''

25th of 9th Month.

Oh! how I love uprightness and plain dealing; a heart which loves its friends sincerely;
that will not harbour and conceal a self-pleasing, envious,
injurious thought of its friend, nor bear to hear it uttered by another without rebuke.
May the virtues of integrity and simplicity, and single and honest-heartedness, be ours,
for they are truly Christian.
Yea, may it please Divine wisdom more and more to purge out the sour leaven,
and leaven our hearts with the leaven of the kingdom; even the leaven of meekness,
long suffering, and tenderness of spirit: so shall we be disciples indeed; contrite,
humble, and faithful followers of the Lamb, whithersoever he leadeth.
May the Lord preserve us as innocent, tender, and babe-like children before him,
hungering to be fed by him, and growing up as goodly plants under his hand.
Oh! this child-like nature: when shall I get enough into it?
It is only as a measure of this is effected in us, that we can cry, "`Abba, Father.`"

Though, as thou sayest, "`things look bad,`" let us look well at home;
and as we are incapable, in a great degree, of doing any thing to make matters better,
let us not make them worse, and the breach wider in the enmity,
by saying or doing any thing in our own unregenerated wills, and natural heat of temper,
which may hurt instead of furthering others.
For the enemy works in us with the engines and tools of our corrupt nature,
which he finds there: and so crafty is the serpent,
that he will seem to employ these weapons for the good cause, against himself; whereas,
he works in a mystery for himself, against the cause, by raising heats, and divisions,
and hardness of heart between brethren.
But let us endeavour, as much as in us lies, to live peaceably with all men,
and if we see a brother offend in breaking any branch of our Christian testimony,
and by the fire of pure zeal warming and cleansing our own hearts,
we find that the truth (as will often be the case) calls for a witness to it,
let us wait to be guided by the Spirit of love and meekness, to bear our innocent,
faithful testimony; and if it be not received, stand in the counsel of the same spirit,
and let not that get up which would render evil for evil, but overcome evil with good.

[.asterism]
'''

14th of 10th Month.

I have, I confess, been favoured at times, since my last,
with the washing of water to repentance and regeneration;
not through any instrumental help,
but through the powerful operation of the spirit of judgment and of burning,
in my solid retirement in and before my family.
We are too apt, after such washing times, to run like sheep,
skipping and leaping from the washpool,
and so are in danger of being bespattered with mire again,
instead of being weightily concerned that a sense of that power may rest upon our spirits,
which is alone truly comfortable, and can keep us solid, steady, and fruitful.
For as the sheep is washed, in order that it may be shorn; so are we washed and cleansed,
that we may "`bring forth fruit meet for Him who has dressed.`"
My desires are strong in my measure, that we, several of us,
who are known by one another, and known to our heavenly Father to have, at times,
living desires raised in us for the glory of God and the eternal happiness of ourselves,
and one of another;
and sometimes a further concern that our backsliding brethren may no more revolt,
but return and live: my desires are that we may come up nobly and boldly in his cause,
and be absolutely (I see no other way to be of service) resigned
to the will and disposal of the great Lord of the harvest,
dedicating freely and cheerfully, as our forefathers did, all we have,
internal and external, to his service.

The following is an extract from the only letter which has been found,
from Richard Shackleton to his wife.
They were not often separated: they probably hoped to pass a long life together,
and therefore might not have been so careful to preserve
such memorials of affection as he afterwards became;
and he often regretted his not having one letter by him,
of the few he had received from the dear object of his youthful love,
who was tenderly remembered by him through the whole of his succeeding life.

Dublin, 6th of 11th Month, 1752.

My Dear Wife,

I trust it is the Lord, the God of our fathers and forefathers,
even the Lord who I believe was with us in joining us together in his holy ordinance;
he has appeared in my heart at this season, both in public and private,
as a refiner with fire, and as a fuller with soap,
to the cleansing and purifying my heart,
and fitting it for a temple meet for him to dwell in.
May thou and I, my dear wife, patiently abide the day and way of his coming,
that in due season we may witness our sins blotted out,
and the times of refreshment from before his presence; that so,
having desired him that he may be the stay of our youth,
we may experience him (if length of days be continued to us) to be the staff of our age.

Thy tender, affectionate husband,

Richard Shackleton.

In the spring of 1754, an afflictive dispensation was allotted to Richard Shackleton.
On the ninth day after the birth of his son Henry, he was deprived, by death,
of his beloved wife, and left the sorrowful father of four children; viz. Deborah,
Margaret, Abraham, and Henry,
(the latter died young.) The exquisite distress which he endured at this separation,
was proportionate to the sweetness of their union:
he had lost the object of his early affections,
the endeared companion with whom he had entered into those family duties, which,
during the short space of time they had lived together, she had worthily fulfilled.
He had lost her when, from youth and health,
they might naturally have looked forward to many happy years:
but the great Disposer of events, in his inscrutable wisdom, ordered otherwise.

Richard Shackleton to +++________+++

Ballitore, 2nd of 1st Month, 1755.

I have the comfort to tell thee, without boasting,
that I think I grow a little in a sense that death itself cannot separate and divide
the union of those spirits whom the Lord hath joined and preserved near himself;
and this has been my greatest relief in some late sorrowing seasons,
for the loss of my very dear and inwardly-beloved companion,
whose spirit I am at times nearly united unto, when in the depth of affliction;
and whose better part I fervently pray to rejoin, when my trials, my baptisms,
my provings, and solitary sorrows, which are many, shall be over.

Richard Shackleton.

[.asterism]
'''

From the Same to the Same.

Ballitore, 29th of 6th Month, 1755.

Outward trials are suffered to come to prove us,
whether they will dislocate our minds from that which ought to be their centre.
If they effect this, the accuser of the brethren,
who obtained permission to put forth his blasting
hand upon the outward substance of upright Job,
has gained so much of his point;
but if such storms only drive us nearer to the shelter
of that hand which is full of blessing,
then they have a good effect.

"`Who sees not Providence all good and wise,

Alike in what he gives and what denies?`"--Pope.

Richard Shackleton.
