== Chapter II.

[.chapter-synopsis]
* Memoirs of Elizabeth Carleton`'s early life
* Extracts from Letters
* Richard Shackleton`'s second marriage
* Some account of the establishment at Ballitore

Elizabeth Carleton^
footnote:[Elizabeth Carleton was descended from a good stock: her paternal grandfather,
Thomas Carleton, of Cumberland, was united to the Society of Friends by convincement,
became a public preacher; and suffered much, both in property and health,
by along imprisonment on account of his testimony against tithes.
He moved afterwards to Ireland, where several of his children were born,
and where he died in 1684.
Her maternal grandfather, George Rooke, also a native of Cumberland,
joined Friends when a youth, and was a minister amongst them sixty-six years.
His only daughter, Rachel, married Joshua, the youngest son of Thomas Carleton,
in the year 1710.]
has been already mentioned,
as forming one of the little company of young persons
united by the bonds of Christian friendship;
and as the circumstances of her early life are fraught with instruction,
some narration of them will, it is believed, prove interesting to the reader.

She was born the 10th of 10th Month, 1726.
When young she discovered a strong inclination for the fine arts; had a musical ear,
and a fine voice; and indulged in dress as far as she could.
Her person was agreeable, her manners pleasing,
and her company acceptable to the gay and thoughtless; though a native delicacy,
amounting to timidity, and a sense of decorum,
prevented her from taking the latitude she might otherwise have been induced to take.
She excelled in skill and ingenuity with her needle,
and was preparing to work a picture for an exhibition, when the ministry of a friend,
on a religious visit in Ireland,
was made instrumental to discover to her the vanity of the things in which she had delighted.
The account of this period of her life is thus related by herself.

[.embedded-content-document.testimony]
--

As long as I can remember, I think I was of a diffident, cowardly disposition,
fearful of doing what I knew was wrong, lest I should be punished; yet, when very young,
was fond of play, and at times earned reproof.
As I advanced in age, the follies and pleasures of youth allured my mind; and company,
though of our own society, with whom I was intimate,
strengthened the growth of the wrong seed in my heart:
so that I delighted much in many things which,
though perhaps not accounted evil by the people, yet were very hurtful,
and in danger of destroying the innocent life,
which ought to be cherished with great care; such as light airy company, music,
and singing;
and a great thirst for reading such books as were entertaining to the natural part,
with specious titles for promoting virtue and rendering vice odious; yet,
like subtle poison,
gradually tending to the destruction of the root of virtue and innocence in the mind,
and creating a dislike to reading the scriptures,
and such other writings as would strengthen and encourage us to live a self-denying life,
according to the precepts of our blessed Lord.

These practices of mine were not with the knowledge
or approbation of my dear mother and grandfather,
the only parents I had left; but concealed from them,
and on that account attended with fear and remorse,
knowing well that I could not hide from the penetrating
eye of Him who beholds the secrets of all hearts.
This sense caused a dread of future misery for such conduct,
as well as fear of being discovered by my friends to be what I did not appear to be;
which, though enticed to join with the temptations when they presented,
yet was a character I much disliked.
And the sincerity of my heart, I believe,
pleaded with Almighty goodness to have an eye to me, and not to cast me off,
but mercifully and wonderfully to preserve me from greater evils,
of which I was in much danger; and also to awaken me to a sense of my perilous situation:
so that when I would retire to bed at night for sleep, his terrors,
lest I should be deprived of life in that state, followed me.
I feared to think of it, and would often resolve to live more circumspectly;
but fresh temptations often falling in my way,
and not keeping up the inward watch as I ought, my condition, like that of many others,
was to be deplored.
But He, whose compassion faileth not,
was pleased to visit my soul in a particular manner, in a public meeting in Meath Street,
Dublin; I think on the 3rd of 9th month, (old style,) 1747,
about the twenty-first year of my age,
through the living testimony of a faithful servant, Richard Hipsley, from Bristol.

My mind had been awakened, in the same meeting, by the testimony of some other Friend,
and I thought how pleasing it would be,
if such ministers of the gospel were to continue with us; when Richard Hipsley stood up,
and mentioned, as well as I remember, the disciples being for building three tabernacles,
one for Moses, one for Elias, and one for Christ; but these servants were removed,
Christ remained, and the voice uttered: "`This is my beloved Son, hear ye him.`"
I cannot recollect further of his testimony, but those words had such an effect on me,
that my heart seemed changed, tender,
and broken--a heart of flesh instead of a stony one; my desires seemed new,
a new heaven and a new earth, in which some degree of righteousness was about to dwell.
The cross then, in this day of power, which before I could not willingly take up,
became easier, and the burden lighter;
the practices before mentioned I dare not join with; often being retired, humbled,
and broken as it were to pieces.
Strength was administered to withstand temptations,
and my love to truth and the friends of it grew strong;
and the love of such seemed much toward me,
so that I wondered that they should take such notice of me,
who seemed to myself entirely unworthy.

I found that my safety consisted in watchfulness to know, and humble resolution to do,
what I thought was required of me, though much in the cross to my nature;
divine goodness strengthening me to bear reproaches, persuasions,
and mockings of my old companions, who, to their own miserable loss,
withstood the offers of heavenly love extended to them;
and notwithstanding I might expect such treatment, I dare not shun the place,
but appear amongst them in a very different manner from what I was used to do,
both in my conduct and dress.
Of myself I could not have acted thus,
but by endeavouring to keep inward and watchful over my words and behaviour,
begging to be preserved from bringing dishonour on that
Holy One whom I was now above all desirous to serve;
and he was pleased, in great condescension, to preserve me in simplicity,
and fear of offending him.
I dare not stay from any meeting which it was in my power to attend,
and often called to see or inquire for such friends as I heard were indisposed,
even if not much or at all acquainted with them before,
which caused many to have an affectionate regard for me;
and made way to drop hints sometimes to my friends, which I was afraid to omit,
lest I should be one of those that were not faithful in small things,
and so become weaker,
and not able to pursue the path which my eyes were opened to see was that of acceptance.

As other things were become new, so was my desire for reading.
Now the Scriptures, our friends`' sufferings,
and other writings edifying and useful I delighted in,
and forsook those which I knew were hurtful to my mind.
Retirement and waiting upon the Lord, to renew my strength in him,
I found was good and necessary.
Visiting, or being in much company, I declined,
lest thereby I should be drawn away from off my watch.
Religious friends I loved to be with, and such were kind and tender towards me;
and under the sense of the notice that many worthy
ministers visiting this nation took of me,
my mind was often bowed in humble admiration, that such a poor, weak creature as I,
should be so favoured; and it was often hard to part with such, and cost me many tears;
and after they were gone, divers have written me encouraging letters.

Thus was I helped,
through the kindness of Him who affords strength
to those that are sensible of their own weakness,
and entire insufficiency to preserve themselves; fulfilling his old promise,
of "`carrying his lambs as in his arms.`"

Though my mind was so bent to practise what I believed to be my duty in religion,
I saw also that it was my duty to be diligent and industrious in outward business,
helping to make it easier to my aged mother and weakly sister.
I have had often to admire how I was enabled, when left alone with a servant,
(my mother and sister in the country,
on account of my sister`'s health,) to carry on our little business,
attend meetings constantly,
and keep the house in so frugal a manner that little would be expended,
and my kind neighbours and friends well pleased, when they called to see me,
to find me at home and properly employed.

Thus I went on for some years, endeavouring to do justly, love mercy, and walk humbly;
being sensible that a warfare still must be maintained,
and a greater victory must be achieved over my own passions and natural propensities,
and that best wisdom was necessary to guide me through life.
As my experience could not be much, therefore I often begged for it.
In course of time, some degree of zeal for the promotion of truth seemed kindled in me,
and a desire to attend some of the general meetings, which was scarcely in my power,
from my situation; but in a while,
my dear friend Elizabeth Pike was raised up to be a kind and faithful help-meet to me,
and we took many journeys together to general meetings, often under difficulties.

We frequently met with discouragement in our meetings for discipline,
by such as were settled in the old way,
which they did not seem to think necessary to alter,
though strongly recommended to do so, by worthy servants sent from far to visit us;
but our minds being preserved in patience and humble dependence on Almighty help,
in time way was made to have things brought into better order, which my worthy friend,
Elizabeth Gill, endeavoured to promote.
She was a tender, loving friend,
and willing to encourage the youth who were desirous
to be what the Lord would have them to be.

--

To this truly pious and amiable friend, Elizabeth Carleton,
Richard Shackleton made proposals of marriage.
The two situations which she most wished to avoid,
that of a step-mother and mistress of a boarding-school,
were involved in the serious subject for consideration laid before her,
which her friendship for Richard Shackleton and her
conviction of the excellence of his character,
could scarcely have outweighed; but her sense of duty was added to them,
and in accepting his offer she became one of the best of stepmothers,
and one of the best of matrons to a public school.
Her sphere of usefulness was enlarged, and she needed not affliction to keep her humble,
which, in the sincerity of her heart, she had desired, if necessary;
for the responsibility of her station forcibly impressed the need of that constant
watchfulness which so remarkably characterized her words and actions.

The difficulties which she anticipated, vanished or were made easy to her; and she found,
in the worth and affection of her excellent companion,
those blessings which constitute the happiness of married life.

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Father.

[.signed-section-context-open]
Dublin, 1st of 11th Month, 1755.

[.salutation]
Dear Father,

The meeting began this day for the nation.
I have not much to say about it.
It looks as if we must labour hard for our bread, through the course of the meetings:
perhaps it may be best so, for what is hardly gotten is oftentimes carefully kept.
And, indeed, I think I have seen great loss accrue to some of honourable rank,
in this respect; that when good Providence, in unmerited condescension,
has favoured them with the bedewings of his goodness,
in order for leavening and seasoning their spirits for his service,
(which is so much wanting,) they have, for want of knowing a settlement,
and abiding in the life, let these favours pass transiently over,
and not be productive of the fruit intended by them.
And with sorrow it may be too often said of them: "`Their goodness is as a morning cloud,
and as the early dew it goeth away.`"

[.signed-section-closing]
Thy affectionate son,

[.signed-section-signature]
Richard Shackleton

--

[.offset]
Richard Shackleton and Elizabeth Carleton were married the 17th of 10th Month, 1755.

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Mother-in-Law, Rachel Carleton.

[.signed-section-context-open]
Ballitore, 16th of 12th Month, 1755.

It would give me pleasure,
and add much to the satisfaction I daily enjoy in thy daughter,
to know that her loss sits with tolerable ease upon you.
I should rather call it her absence, not her loss;
for I hope Providence will favour us with meeting divers times together again,
in this land of uncertainty; and they are not lost,
who are found in the places which Infinite Wisdom has ordered them in,
which I hope is the case with thy dear, valuable child:
and I doubt not but this consideration makes this separation easier to be borne by thee.
And I sincerely desire it may be made up to you by the most solid comfort,
which unites together in spirit those that are absent in body,
and is the crown of the aged as well as the youth.
That this may be our chiefest care to seek after, whether old or young,
is the sincere desire of

[.signed-section-closing]
Thy dutiful and affectionate son,

[.signed-section-signature]
Richard Shackleton.

--

In 1759, Elizabeth Shackleton`'s mother, and her sister Deborah, settled in Ballitore;
and, ultimately,
all Richard Shackleton`'s daughters were placed under the care of Deborah Carleton.
Few were better qualified for the care of young persons,
than this amiable and excellent woman: she won their hearts and gained their confidence,
made every proper allowance for them, and granted them every proper indulgence.

Richard Shackleton`'s three eldest children loved his second wife with sincere affection,
and her conduct towards them deserved it.
Her own two daughters were treated, by their sisters and brother,
with that affectionate tenderness which young, generous hearts,
are wont to show those who look up to them with love;
and the care of their mother and aunt was found necessary,
to protect them from that excessive indulgence which
these young persons were disposed to give them.
Thus was Richard Shackleton made thankful to Him who setteth the solitary in families,
for having permitted him to form another happy matrimonial connection.
He, pursuing his onward path,
and seeking first the kingdom of heaven and its righteousness,
found all things necessary added--all things necessary for those whose desires are moderate;
and this is likely to be the case with such as are concerned to keep on their watch:
they may hope to see what to do and what to leave undone, even in their temporal affairs.

Richard and Elizabeth Shackleton, in the pursuit of the arduous undertaking,
the instruction and care of youth, were imbued with that reverential fear,
which is a blessing and a safeguard to those who abide under it.
The advantage of their example extending far beyond their sphere in life,
was felt throughout their neighbourhood,
so that many of the higher ranks desired to cultivate a familiar
intercourse with a man distinguished by his talents and learning,
and a woman of so benevolent a character.
But while they received such marks of kindness with respectful courtesy,
they were not drawn by them from their allotted situation.
Their time and thoughts were claimed by their duties,
and they were the more respected for preserving this line of conduct.
Industrious and prudent, yet casting their care upon Providence,
they felt the shackles of the world hang loose about them.
They were eminently useful members of religious society,
with clean hands and discerning spirits,
being well qualified to take an active part in conducting its discipline.
Their duties to the children under their care were conscientiously fulfilled,
of which the grateful love that their pupils retained for them is a convincing proof.
Several of those who, while they were under their mistress`'s eye,
had thought her too strict, loved her the better afterwards, even for this;
and many remembered, and we may hope profited by,
the tender admonitions which she was wont to impart,
particularly at the time of their leaving school, to enter into an untried world.

When the varied business of the day was over,
it was a comely sight to see the parlour supper-table surrounded by the master, mistress,
their children, the young men who were parlour-boarders, the ushers, and the housekeeper,
all on equal footing; all equally at liberty to express their sentiments,
or gain instruction and pleasure from those expressed by others.
Without losing the respect due to their own characters
and situation as heads of the establishment,
careful and observant of the conduct of all these,
Richard and Elizabeth Shackleton treated them with a kind familiarity,
which attached them to home,
and precluded the desire of seeking more enjoyment elsewhere,
which is too often the effect of repulsive manners.
This social meal seemed to bind all more closely together:
the heads of the house saw the elder branches of their family collected,
and they separated with mutual good will.

To one who once belonged to this table, but who was then the father of a family,
and advanced in life, the grandson of Richard Shackleton was introduced.
He was politely received by the old gentleman, but his name once mentioned,
all ceremony vanished: "`Shackleton! you are the grandson of my old master!
I loved him next to my own father!`" then grasping both the hands of the young man,
he permitted his heart to overflow in affectionate remembrance of departed worth.
He afterwards thus wrote to one of the family:
"`It will be only with existence that I shall lose recollection
of the numerous acts of kindness I have experienced from your father.
He was my inestimable preceptor: he was my indulgent friend.
I acknowledge my debt of gratitude, and shall ever be most happy in evincing it,
and how highly I revere and respect his memory.`"

The large establishment, and consequent plentiful table,
caused the indigent to resort to Richard Shackleton`'s house,
Perhaps they were relieved too indiscriminately;
but there was much care taken to inspect the wants of the modest poor:
employment given to some, the sick supplied with medicine,
and those who had known better days considered with delicate attention.
Old neighbours were taken into the family,
occupations found for them suited to their age and weakness,
their infirmities alleviated, their fretfulness endured,
and their close of life rendered as comfortable as was in the power of their benefactors.
One of these died in the house of the younger Abraham Shackleton, having,
it was supposed, attained his hundredth year; and another,
who had served the three generations as steward,
also died in his house at the age of eighty.
Thus, in a comparatively humble walk of life,
were generous and charitable dispositions unostentatiously exerted.

Richard Shackleton was blessed with a cheerful, contented mind,
conducive to his own happiness, and the happiness of all around him.
He was prepared to adopt the language of the poet:

[verse]
____
Ten thousand thousand precious gifts,
My daily thanks employ;
Nor is the least a cheerful heart,
That tastes those gifts with joy.--Addison.
____

The fault of his temper was quickness, not violence;
but this was soon subjected to his judgment,
and if he thought he had wounded any one thereby, he was ready to acknowledge it,
with a benign humility which melted the heart,
and disposed it to follow so touching an example.
From his conversation young persons derived much instruction and delight;
and such was his solicitude for their eternal welfare,
that he might almost be designated, "`the apostle of the youth.`"
He seldom or ever left home, for any considerable length of time,
without paying farewell visits to his neighbours;
nor returned without greeting them at their own habitations.
After a day industriously spent,
it was his practice to retire every evening to his garden or chamber; his countenance,
when he returned to his family, bearing the impress of divine meditation.
And before retiring to rest, he read a portion of scripture.
If he was under difficulty or perplexity,
the first thoughts which occurred to him on awaking in the morning,
were generally those to which he took heed,
by which he was often freed from what had annoyed him.
He had learned to cast his care on Divine Providence,
in matters of less as well as greater moment.
He was a kind and considerate master,
being careful to avoid giving servants unnecessary trouble.
He rose early both in summer and winter.
Neither he nor his wife were in the station of minister; but in meetings for discipline,
and in families, they were often concerned to deliver wise counsel,
in words few and pertinent; and Richard Shackleton sometimes spoke in public meetings,
but, like his father, in the character of an elder.
When he returned to our national meeting,
on account of his attendance at the yearly meeting of London,
his words were delivered with such humility, sweetness, and brokenness,
that the influence under which he moved, seemed to overspread the assembly.

He was freely given up to these services by his true helpmate,
whose exertions to promote the good of all, united with his own.
This pious woman assiduously endeavoured to alleviate the sufferings of body or of mind,
which came under her notice; and, as has been alluded to before, her nature,
as well as her religion,
prompted her to visit the fatherless and widows in their affliction;
and in fulfilling these duties,
she experienced that feeling so excellently described by the poet:

[verse]
____
The heart which bleeds for others`' woes,
Shall feel each selfish sorrow less;
The breast which happiness bestows,
Reflected happiness shall bless.--Cartwright.
____

Being enabled to overcome evil with good, she was sincerely beloved,
and seemed to be made a blessing to some who had at one time been prejudiced against her.
With a solid and improved understanding, her simplicity was such,
that it might appear not difficult for the artful to impose upon her;
yet it not unfrequently happens, that the single-hearted and artless,
more readily penetrate into the characters and motives of others,
than those do who are busy in concealing their own.
Her grave manners tended to inspire awe in young persons;
but they soon found that these were softened by such kindness of heart,
that love overcame every other feeling towards her.
Sedulously attentive to the improvement of his pupils,
Richard Shackleton`'s time was fully occupied with this employment,
and he resigned to his wife the management of his farm;
not that he was himself averse to, or incapable of conducting it;
nor did it appear that any other person entertained an opinion,
which he often expressed respecting himself,
that he was fit for nothing but a schoolmaster;
but he knew his wife`'s capability and inclination for these concerns,
and her willingness to receive advice from those
who were experienced in agricultural affairs.
She was, indeed, remarkable for this; and readily waved her own plans,
to make trial of what others recommended,
though it often happened that her former practice proved to be the best.

She was slow and deliberate in her movements and decisions.
She not only provided for her household, combining therein economy with plenty,
and attended to the various business of the farm,
but superintended the building of several houses;
permitting nothing to prevent her fulfilling her duties to her aged mothers,
to her children, and to the other branches of her family:
the regular distribution of her time, and the love of order,
enabling her to accomplish what few of greater activity, without these aids,
find themselves capable of.

She was an admirer of good poetry,
but still feeling the limit which had restrained her youthful imagination,
she justly feared the danger of transgressing it for herself and others: thus restricted,
the enjoyment, so far as it was permitted, was without a sting.

Her husband, also,
scrupulously endeavoured to keep his genius for literature in subjection to higher objects:
if he had turned the bent of his mind to it, he probably might have excelled in poetry.
Those who have no taste of this kind themselves,
are in danger of mistaking their motives, when they condemn those who have.
None who are sensible of the beauties of literature can despise them,
however they may feel themselves circumscribed in the indulgence of their inclination.
Of a winter`'s evening,
Elizabeth Shackleton frequently brought those scholars
who belonged to her own religious society,
into the parlour, to read her the journals of Friends, as she sat at work.
She was also pleased at hearing history read to her,
generally by the young students who were parlour-boarders.
This employment was the more agreeable and instructive,
because she had an excellent memory and sound judgment.
She entered into the characters of those held up to view,
often supplied the thread of the narration, when it had escaped the young reader,
and took a lively interest in the public or private events which were narrated.
She persuaded herself that Caligula`'s reason was impaired by the fever
which had seized him before he was raised to the imperial dignity,
and therefore imputed to insanity, the apparent change of character,
and the subsequent horrors of his reign.
She lamented and blamed the timidity of Seneca,
which deterred him from curbing the headstrong passions of Nero; believing,
that had he been faithful in the discharge of his duty,
his pupil might have been awakened to a sense of his enormities,
and the preceptor been longer spared to a degenerate age.
It was natural that this fault should appear evident to
one who was herself religiously concerned to avoid it;
for she believed it was required of her, in many instances,
to admonish those whose improper words or actions came under her notice.
She spoke not of those offenders; she spoke to them;
though in doing thus she took up the cross, and often for a time felt it heavy;
but whatever the rank, or how little soever acquainted with the person,
she must fulfill her apprehended duty, to obtain that peace, which, flowing as a river,
amply rewarded such sacrifices.
It need scarcely be added, that in these performances, her own will being laid aside,
she was instructed so to speak, as seldom, if ever, to offend;
and we cannot calculate how much good may have been produced
by those alms (if they may be so termed) given in secret.

[.offset]
The manner in which Elizabeth Shackleton was strengthened to perform her duties,
is thus described by herself.

[.embedded-content-document.letter]
--

Being sensible of my own inability, my dependance was on Divine help,
which I had often experienced in times of need.
I was favoured with understanding and knowledge for the business,
beyond what I could have thought; my careful,
industrious husband assisting in many things belonging
to my department as well as his own;
so that we were reciprocally helpful one to the other,
sympathizing and bearing burdens one for the other, in our arduous calling;
and both being near of an age, and favoured, for many years,
with a good degree of health,
our success in endeavouring to do our duty was an encouragement,
and our minds were preserved in a grateful sense
of the gracious dealings of the Lord to us.
And notwithstanding our close and constant engagements,
so that we seldom left home on other occasions,
we found it but our reasonable duty to attend the
meetings for discipline to which we belonged,
as well as quarterly and half-yearly meetings; also to show, by an exemplary life,
the efficacy of the principles of truth we professed to be led by,
amongst the numerous acquaintance we had;
being employed by many who knew little or nothing of those principles.

--

An instance of this occurred, when a gentlewoman, on leaving her son,
requested of Richard Shackleton that he might be permitted to read the Bible.
He, amazed,
expressed his surprise that she should place her child where such a request was necessary,
assuring her that the Bible was daily read in the family.
She asked his excuse,
telling him that she understood that George Fox`'s Journal was substituted instead of it,
by those of his profession.
At another time, the son of a man of fortune was brought to his school by his mother,
who, till she came to Ballitore, had never seen one of the people called Quakers.
Elizabeth Shackleton queried why she brought her
son among a people who were such strangers to her.
She answered, that she had heard a good character of them,
although they differed from the Church of England concerning baptism and the supper.
This lad spent most of his childhood, and some of his youth, at Ballitore,
perhaps the happiest part of his life; for when he lay in an American prison,
dying of wounds received in a battle,
in which the British army (wherein he was an officer) was defeated,
and the prison was so crowded as to aggravate the pangs of death,
"`If I were at Ballitore I should not be thus neglected,`"
were almost the last words he uttered.

One of the pupils, an only child, died of the small-pox;
and Elizabeth Shackleton lost her own child, then also an only one, about the same time,
of the same distemper.
"`This,`" said she, "`proved a trial to me, which I hope was of service; believing,
that whatever afflictions are permitted to attend us, are for our good,
if we make a right use of them,
and more and more cast our care on Him who careth for his humble dependant children.`"
