== Chapter V.

[.chapter-subtitle--blurb]
Letters written between the years 1781 and 1788, inclusive.

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth Shackleton to Her Husband.

[.signed-section-context-open]
Ballitore, 1781.

Though it was agreeable to get a letter from thee,
yet thou mayst be sure it would have been much more so to have had thyself,
if it had been right: if not,
it is better for thee to be employed in the business of going about doing good.
This I hope is the case,
and if thou thinkest thou canst not do much more than assist
and support the hands of our ancient friend,
who may often be cast down through infirmities of body, and distress of mind,
it must be doing good.
Distress of mind thy honest heart is well used to,
on account of the unfaithfulness of the professors of the unchangeable truth,
which will remain so, though all men should forsake it.
What remains to be done by the few who are concerned for the promotion thereof, is,
to be watchful and humble, seeking to know what is required,
and then honestly and simply performing it.
This, I believe, is the way for the work of reformation to go forward,
that is begun in many minds.
The more we are reduced and brought into the littleness,
(as thy father used to say,) and kept in it, the more helpful we shall be,
as instruments in the hand of the Almighty, who can work by whom it pleaseth him to work.

[.signed-section-signature]
Elizabeth Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 7th of 1st Month, 1781,

I suppose thy good man Samuel is by this time in Cork.
I wish his honest mind may receive benefit there.
Such breaking away, every now and then, from the cares and cumbers of this life,
is very necessary and profitable to all who can compass it,
and should be struggled and contended for by men of business.
And not only at such seasons of general edification, do I wish you, dear children,
to profit; but recommend, what I doubt not is at times your practice,
often to cultivate at home a renewing of the baptism of truth in your own hearts:
this tendering influence, this daily sacrifice of a broken and contrite spirit,
will be acceptable to him who is the Author of every blessing, spiritual and temporal;
and will be found to animate, refresh,
and invigorate for the discharge of every duty of every kind.

We live in much comfort, amity, and satisfaction;
and I hope some of us are not insensible of the great and capital
favour it is that our domestic tranquillity is lengthened out.
This is a favour that I am jealous too many do not properly estimate,
and yet the complexion of the times is such,
that it seems no way unlikely that the false rest, which many have settled in,
will be disturbed; and then the worth of peace, and tranquillity, and ease, and plenty,
will be known by the want of them.
Divine Providence, indeed, is all-sufficient to protect and deliver;
he is good and gracious, slow to anger, and long-suffering,
else it would seem that these poor islands would be, as it were,
swallowed up by such combined hosts of foes.
I say He is merciful and all-sufficient,
yet it is not amiss for us to commune together on the way, concerning these things;
and doubtless is acceptable to our great Preserver,
when in a right spirit we commemorate his benefits.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Mary.

[.signed-section-context-open]
Tottenham, 14th of 6th Month, 1781.

+++_________+++ is a sprightly, sensible woman; but would suit my taste much better,
if more of the diffident, the humble, the simple entered into her composition.
And even true genius and literary accomplishments
receive a softness and lustre from these qualities,
highly ornamental.
I hope I am not apt to force the subject of religion into conversation; (like poor Saul,
who would have the prophet conjured up for him;) but let advanced age, experience,
and parental affection say, religion, my dear child, is the safety, the happiness,
the glory of human nature.
By its sanctifying virtue, natural and improved abilities are kept in due subjection,
regulated and directed to useful purposes:
by this we have counsel and wisdom in dubious and intricate concerns;
by this we have resource and consolation in distress;
and by this we have (the greatest of all favours) the evidence, the assurance,
the earnest of a happy immortality.
Aspire after the knowledge of it, my dear child: with all thy acquirements,
endeavour to acquire this.
Remember Moses, who was exceeding fair,
who had the education of a court to polish his manners,
who was wise in all the learning of the Egyptians,
and whose poetical talents are left on record in his song;
yet had he given the preference to these qualities in his heart,
he never would have been the leader of the Lord`'s
people through the Red Sea and the wilderness;
but he chose rather to suffer affliction with the people of God,
than enjoy the pleasures of sin for a season.
So though no man knows where the visible part of him was buried, yet his memory lives,
and preaches loudly to us, to this day.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Sarah.

[.signed-section-context-open]
Newport Pagnel, 18th of 6th Month, 1781.

Where there is not the salt of religion, to me company is exceedingly insipid.
If we be truly enamoured with the great object of our entire love,
we shall be sick of the conversation of those who
are so far from being tinctured in like manner.
That which deserves the name of Christian friendship,
(or fellowship,) which is gendered and nourished by divine love,
cannot subsist between persons of such opposite spirits.
But, my dear child, if through the mercy of the Almighty, (for there we are to depend,
having not the least merit of our own,) if through his condescending mercy,
we are happily preserved,
having that eye open which sees a beauty in the most excellent truth,
the beauty of holiness;
if through the same mercy we suffer our affections to be separated
from earthly and raised to aspire after heavenly enjoyments;
as we thus take firm root in the life of religion, we shall grow in the branches;
and in due season put out leaves, and bring forth fruit,
which may convey healing virtue and food to others.
So men and women become as "`saviours on Mount Zion;`" but consider,
this is not an unstable, slippery footing, but Mount Zion which will never be moved.
There is no steady, profitable progress made in a journey,
if we be ever and anon halting, loitering, standing; forgetting what we are about, or,
even if we make some advances forward, and yet suffer ourselves again to be drawn,
as much, or perhaps more, in a retrograde direction.
Such a conduct is dangerous; no comfortable composure abides with us on the way,
and the night may overtake us, before we have completed the labour of the day.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 4th of 7th Month, 1781.

[.salutation]
My Dear Margaret,

Through the benignity of gracious Providence still extended to thy poor father,
I can again salute thee from my own home, that comfortable home,
which he has allotted me, among the sweets of domestic life;
and which I reached on the 2nd instant, under a tender sense of his mercies.
Indeed, his kindness has been "`very great to me in this last excursion, reproving,
instructing, encouraging, sustaining, and preserving;
giving me favour amongst his favourites,
whereby I witnessed the renewal of former amities, in a manner such as I would wish,
and the creation of new ones.
Joshua Pim told me in Dublin that his mother continued better.
I was greatly satisfied with her company.
The feeling manner in which she spoke of the inward comfort she had experienced,
I thought ministered life to my spirit,
and I sat with pleasure under the distillation of her speech,
as under the dropping of Gospel rain.
Behold, my dear child, the Omnipotent Friend,
whose support is sufficient for every trial,
and who is near to help in the deepest affliction.
Who would not by all means assiduously cultivate such patronage?

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Son.

[.signed-section-context-open]
Dublin, 1st of 11th Month, 1781.

[.salutation]
Dear Abraham,

We got well and in good time hither.
I hope this will find you also in good plight.
Storms and cross winds will sometimes discompose us on this sea;
and there is also a danger from the becalmed, indifferent state of mind.
To have one at the helm, that can not only steer the vessel safe,
but command the winds and waves, is a great acquisition.
We should, with the eye of prudence, keep a sharp look-out,
that no hidden rocks or shelves be in the way; but our dependence must be on the pilot,
and to him we must submit the guidance, or we shall not be safe.
For my part, I have been much tossed and agitated of late, on various accounts.
The hemisphere looks cloudy, and neither sun, moon, nor stars appear.
But I strive to get "`right onward.`"
You, my beloved children, are a great comfort to me, and, as you do well,
you will contribute much to my happiness.
Your task allotted in life is arduous and complex;
you will very much want (and I hope you are truly
sensible that you want) Divine Wisdom for your guide,
Divine Providence for your protector, and Divine Power to mediate for you.
From a sense of our own insufficiency arises a cry for help;
and in proportion to our sensibility and distress,
that cry penetrates the holy ear with effectual importunity.
The full, the self-sufficient, as they ask not, so they receive not;
as they do not feel themselves poor, they neither labour nor beg.
The Lord`'s poor are fed at his gate, but the rich and the full are sent empty away.

I very freely and readily accept of our Lydia`'s apology for not writing to me:
I know the source of her backwardness,
and it is among the many things which rivet my affection to her.
She is herself an epistle written in my heart, which I often read with delight.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Son-In-Law G.

[.signed-section-context-open]
Ballitore, 18th of 12th Month, 1781.

I would not be wanting to myself and family in taking
necessary steps for the recovery of my money,
according to the best of my understanding, and the advice of my judicious friends;
but I find that suffering my mind to be too much
occupied in contemplation about these matters,
hurts and unfits it for better things.
I acknowledge I am not wise in my generation about them; I am sensible of it,
(as also that it is a defect, and not any merit in me,) and therefore I apply,
when I can, to Him who has all power in heaven and on earth,
and without whose permission such events do not happen,
that he will be pleased to mediate in my affairs,
and that all things (what the world calls good and evil) may work together for the essential,
substantial good of me and mine.
In the active season of life, diligence in business, within the limitation of truth,
is not only allowable, but has the sanction of apostolic precept.
"`Provide things honest (i. e. decent) in the sight of all men.`"
And, "`if any man provide not for his own, and especially for those of his own house,
he hath denied the faith, and is worse than an infidel.`"
I often look back with a pleasing recollection to the industrious part of my past life,
in which I in some measure "`exercised myself to
have a conscience void of offence towards God,
and towards men.`"
My care and industry were blessed with competence; and if this now,
in the decline of life, be diminished, I hope that, through the same blessing,
a competence will still remain.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth Shackleton to Her Daughter Margaret.

[.signed-section-context-open]
Ballitore, 18th of 1st Month, 1782.

[.salutation]
My Dear Margaret,

Thy favouring me with the first letter after thy confinement
I take as a mark of great kindness and affection,
and I fear I shall make thee but a poor return for it;
for really this dismal news (the shipwreck of Edith
Lovell and Joseph Sparrow) has affected me so much,
that it is seldom out of my thoughts while awake.
Remember, we cannot pretend to judge for what cause it was permitted.
Edith was a near and dear friend, in the prime of life for public service, a humble,
devoted servant, the mother of a number of small children,
whom she appeared to be qualified to educate in the way that they should go.
Our dear Joseph, reared with care, and arrived at man`'s estate,
a dutiful and helpful son, an affectionate brother, a kind, sincere friend,
an example of sobriety and virtue, and likely to be of extensive service in the society.
How can we then but admire why such should come to an untimely end?
Yet, as we are short-sighted, and cannot penetrate into futurity,
it may be ordered so in unerring wisdom,
that they should be taken from the troubles and dangerous temptations we, who remain,
are subject to while here.
May their near friends and connections be supported under so great a trial.
My mind has been much affected with sympathy for his distressed mother,
and I have feared it might cost her her life; as he was not only her dear,
affectionate son, but also, I suppose, her friend and counsellor.
I wish, much for her, that she may endeavour to keep her mind as still as possible,
with her eye to Him who knows best what to appoint for us in tender mercy,
to the purifying our spirits,
in order that they may be fit to join the number of those
who live to praise and glorify his great name,
in a habitation eternal in the heavens.

I observe thy wise and prudent remarks concerning the education of thy dear little ones,
thy charge being now increased.
I think what thou mentionedst is just,
that to be led and governed ourselves by best wisdom,
can alone qualify us to train up our children in the nurture and admonition of the Lord;
and we had need keep close to this assistance, as we are frail,
and our natural part ready to interfere.

[.signed-section-signature]
Elizabeth Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to John Thorpe.

[.signed-section-context-open]
Ballitore, 24th of 2nd Month, 1782.

I have some faint remembrance that, when I had the pleasure of thy company,
we conversed a little about meetings for discipline.
The church should edify itself in love,
and when the most active and zealous members of a meeting are collected together,
there is seasonable opportunity for every one to exercise their several gifts to edification,
and by thus giving they may know an increase.
The discipline is a branch from the same stock as the ministry,
and by long experience has been found to be exceedingly
useful in the conservation of our religious society.
I need not enumerate to thee its many advantages.
The members of the church-militant are still coming on and going off the stage of action:
there must be a succession of clean hands to handle the discipline,
and there must be some time in learning, that they may have skill in the work;
so that those who are already qualified should be present, ready, and apt to teach.
The conferences also in monthly meetings, among ministers and elders,
should (according to my best feeling) be diligently kept up:
these should be holy convocations, solemn meetings.
Those of this class,
casting down their crowns before Him "`who is the head of all principality and power,
may, under his blessed influence, as iron sharpens iron, and diamond cuts diamond,
be made instrumental of help to one another,
and consequently of help to the monthly meeting at large.`"

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 11th of 8th Month, 1782.

The harvest of the world and the harvest of the church, conspire to occupy our attention.
For my part, I think I am of little use in either department; but in the latter I dare,
not (nor am I willing) to withhold any little assistance which I am capable of giving.
In allusion to such harvest-work, or works of agriculture, our Saviour saith,
"`No man having put his hand to the plough, and looking back,
is fit for the kingdom of God.`"
I wish, for myself, and those connected with me, to seek first this kingdom.
The refuse of our time and our talents will not be accepted.
Whole burnt-sacrifices, and victims without blemish, are the acceptable offerings:
the halt, and the lame, and that which died of itself will not do.

13th. Thy letter was most acceptable: it comforted and cheered us, to find thee so easy,
happy, and tranquil.
I was thankful for it, and enabled to make a grateful offering on thy account.
Surely, great are my obligations to Divine Providence, for many favours;
but in an especial manner for such a wife and such children as I am blest with.
The connections also of my children having been formed (I trust) under heavenly direction,
are a source of pleasing reflection and satisfaction to me.
I wish you all to trust in the Divine disposal,
and not lean (not to be biased by the will of the creature, or its plausible,
fallacious prospects) to your own understanding.
He that sitteth in heaven consults on the sum of things,--takes the whole, past, present,
and future, into one view; He is therefore the best and only sure counsellor.

17th of +++_______+++. No doubt thou wast pleased with the opportunity of being
personally acquainted with thy new sister Sarah Robert Grubb.
I hope the alliance between you will get the best, the purest, the strongest cement.
But if we would build a firm wall, we must not hurry it up too fast:
we must go on gradually, and allow the cement time to dry.
It is good to let truth create our friendships, guide us to the objects,
order us as to the growth, and limit us as to the degree.
Truth should be the alpha and omega of these intimacies, or they will not be permanent.
Another thing.
As best wisdom dwells with prudence, however near your union may be with one another,
it is not well to let it be too publicly manifest: it may raise jealousy in others,
cause invidious reflections, and be productive of many inconveniences.
Taking these little hints along with you, may you love one another most cordially, say I,
and may the Divine blessing sanctify your love!

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Son.

[.signed-section-context-open]
Clonmel, 8th of 10th Month. 1782.

Clouds filled with gospel rain, wafted along by the Divine Spirit,
compressed by the Almighty hand, and discharging themselves on the people,
is the perfection of instrumental help.
Yet to be looking too earnestly at these clouds,
and watching which way the wind (the spirit) is driving them,
is not the way for us to profit.
"`He that observeth the wind shall not sow,
and he that regardeth clouds shall not reap.`"

We have abundant cause to rely on that bountiful and gracious hand,
and to trust in that source of supply that has never yet failed.
Seek first the kingdom, was the precept of the Great Master:--first,
in the early part of life:--first, as the object of greatest value:--first,
as requiring the most diligent attention and pursuit.
This being, through heavenly help, put in practice,
there is no doubt but other less essential, yet necessary things will be added.
Time is short and fleeting.
A little will suffice for our quick passage.
One thing (as our Lord told Mary) is needful, absolutely needful: may we happily choose,
and be preserved to persevere in our predilection for that good part,
which is unmixedly good, which makes truly rich,
and is free from the appendages of worldly sorrow.

There is an infinite variety in the spiritual, as in the temporal system;
and in this variety is much of the beauty of the inward as well as outward creation.
Numberless are the gifts and graces which are in the heavenly storehouse,
all good and all perfect;
and these would doubtless be liberally dispersed
to the members of the visible church of Christ,
were the ground of their hearts prepared and made ready for the reception of them:
but an enemy has so far prevailed, that these gifts are withheld,
and many posts and stations in the house of God are vacant,
to the tarnishing of the splendour,
and deranging the comely and excellent order of the house.
And too frequently, when gifts have been bestowed,
they become sullied by a creaturely mixture; something,
which though plausible and subtle, is born of the flesh,
and profiteth nothing in religion.
There is often an affectation and imitation of the gift or manner of others.
This is a great error in judgment;
for everybody would certainly shine most by exercising his own gift,
and most effectually contribute to general service;
but to despise one`'s own and covet another`'s,
is (like the dog and the shadow in the fable) the way to lose the substance.
The variety of gifts, like the variety of chords in David`'s harp,
constitutes the harmony, more sublime and beautiful than a dull monotony.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah Robert Grubb.

[.signed-section-context-open]
Ballitore, 24th of 12th Month, 1782.

[.salutation]
My Dear Cousin,

Having on the 22nd instant received the two enclosed letters to forward,
it has been a stimulus to me to rise early this morning, to accompany them,
like a guide to travelling English friends.
I remembered as I lay in bed, that I was in debt for a long, instructive, affectionate,
obliging epistle of thine,
to which I have no sort of expectation of making any thing like an adequate return;
neither have I, that I know of, such emulation about me.
Honest friends, in entertaining one another, should not vie in elegance and superfluity,
but simply and cordially bring out the best they happen to have in the house,
for their guests; and though the fare may seem mean, yet if it be sound and savoury,
and served up by clean hands, there is no reason to be ashamed of it.
It is the affecting to appear something above our abilities that renders us contemptible,
and which, if persisted in, will be in danger of making us bankrupt.
But why these strictures?
They have no pointed meaning, my dear cousin: they are general observations.
I hope and believe we are both pretty clear of affectation, and superfluity,
and ostentation, though unintentionally I fell on this subject.
Love and unity, I trust, subsist between us;
and if admonition was necessary to be imparted,
I also trust we should receive it from each other,
without having recourse to any oblique insinuations.

They call our dwelling the Retreat.
It is indeed so in some respects; but annoyances of one sort or other will break in.
Flies are most troublesome in the shade.
To keep low and humble, to step cautiously and feelingly,
to watch diligently over the movements in our own minds,
to wait for that baptizing virtue which makes and preserves sweet and clean,
to be as good servants,
ready for every occasional duty which may be unexpectedly required:
this is the state we desire to be found in, and wish it was more our experience.
But we are poor, and desire the prayers and sympathy of our dear friends,
to whom we are united in the fellowship of suffering.

Accept of all our dear love, which indeed thou art in full possession of.
Whenever thou findest leisure and freedom to favour me with a line,
be sure it will be very acceptable to me.
If thou hast been at the province meeting of Cork, send me the history of it.
Julius Caesar fought the battles, and recorded the narrative of them, with the same hand.

[.signed-section-closing]
I am, my dear cousin, thine, very affectionately,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 10th of 1st Month, 1783.

I am obliged to my dear cousin for her kind, confidential letter.
Every communication I have with thee, I think, rivets thee more closely to me.
I find thy excursion to Cork has been productive of some uneasiness to thee.
What then?
It may have been, notwithstanding, a profitable journey.
If thy foot slipped, and the inward monitor was near to reprove,
and thou hast been healed by his stripes, there bound thy reflections:
the past is irrecoverable; kiss the rod in all humility,
and see and be a good child next time.
I say again, thy welfare is near my heart, and my desire is, that neither heights,
nor depths, things present, nor yet to come,
may be able to separate thee (who art separated to the Gospel) from the love of God,
and an entire, unreserved dedication of all thy faculties, in nothingness of self,
to the cause of Christ.
Our province meeting, lately held at Castledermot, was to me satisfactory.
As to the preaching, it was according to the complexion of the time, a day of rebuke;
but, for my own part,
I rejoiced in having my own spirit rinsed and cleansed by the baptizing power of truth.
Several of the servants ministered to us, all well, for aught I know; but Mary Ridgway,
that piece of beaten gold, beaten by the hammer of affliction,
was peculiarly honoured among her brethren.

I very much accord with thee in sentiment, on perusing the weighty contents of thy last.
I rejoice in thy diffidence, and in thy sense of the precariousness of thy standing.
I observe thy wise distinction between the strength
which is inherent in the constraining mission,
and the occasional capacity which may now and then be witnessed,
in the freedom of a visit to one`'s kindred.
I think, till this time, when I am writing,
I never understood the force of that passage relating to Gideon: "`Go in this thy might,
and thou shalt save Israel.`"
And this might was: "`Have not I sent thee?`"
Be cheered, my dear friend, and look upward:
I make no doubt but heavenly help and divine favour are near thee.
Read and apply the three first verses in the 6th chapter of Hosea.
Thou broughtest a part of them to my remembrance.
Thou hast not only my love, but the love of all my house.
Remember us dearly to thy husband; to thy worthy brother and sister,
where you at present quarter; and be assured I am, in sympathy,

[.signed-section-closing]
Thy truly affectionate friend and kinsman,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Son.

[.signed-section-context-open]
Dublin, 22nd of 2nd Month, 1783.

It was a good day to thee,
when thou wast solemnly and publicly united to our beloved Lydia.
I am a witness that the power of an endless life presided on that day.
May it be your frequent employment to wait for the renewing of that power to your spirits.
Divine love is the great bond of our religious society,
which pervades every living member of the body, and joins all together in an holy union.
I doubt not but you experience this at times, to cement you to one another,
and to all the living.

I wish you health and prosperity, and every blessing; but if He who has you, I trust,
under his care and keeping, sees meet to chasten with the stripes of affliction,
may you be so instructed by the dispensations allotted,
that you may be enabled each to say: "`Not my will, but thine be done!`"
My heart is often engaged for you, with tender solicitude.
Your track of life is an arduous path; thick sown with a variety of trials, probations,
and perplexities, and difficulties: may Solomon`'s wise choice be yours,
and may you happily obtain substantial wisdom to direct,
and substantial help and comfort to confirm your steps, and strengthen you in your way.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Mary,

[.centered]
Concerning his danger on ship-board,
coming from England with John Pemberton and William Mathews.

[.signed-section-context-open]
Athy, 23rd of 8th Month, 1783.

I had just lain down for the night,
when an everlasting night threatened the visible part of me.
The ship struck against a bank, which they called the Kish,
near the place where the Indiaman, they said, struck some months ago,
when near one thousand, I heard, perished.
She struck a second and a third time: it was awful!
I thought of poor Edith Lovel and Joseph Sparrow,
and knew not but their fate would have been ours.
For a few minutes I was held in anxious suspense, but preserved from abject fear:
in a few minutes she floated again, and we got off.
This was a preservation to be commemorated with humble gratitude!

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 25th of 11th Month, 1783.

My wife, son, and daughters Lydia, Mary, Sarah, and I,
attended our last half-year`'s meeting.
It was large, the season of the year and the state of our religious society considered.
Favour was, I think, in a good degree extended,
to those whose lot it was to burn incense in the order of their course,
who I believe generally moved in harmonious labour.
John Pemberton and William Mathews were there.
John seems concerned to have meetings in places where no friends reside:
William is not so much in that line.
Several friends are in sentiment that it would be full as
well if they travelled separately from each other.
They have each acceptable service here.
Our dear friend, Mary Ridgway, is an opulent merchant in this traffic,
and still increasing, I think, in wealth: when she was less substantially rich,
she made greater show; now that her substance is increased, she makes less display of it.
I honour and admire, as well as esteem and love, the woman.
Her life is a striking lesson, how effectual divine support is,
under the most poignant sufferings.

My wife and children join me in the salutation of dear love to you all.
Hoping, waiting, expecting, longing for thy promised packet, I remain,
as patiently as I can, thy truly affectionate kinsman,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth Shackleton to Her Husband.

[.signed-section-context-open]
Ballitore, 5th of 1st Month, 1784.

It gives me satisfaction that thou feelest support,
and a belief that thou art in thy place.
I am willing to give up thy company,
(which is very desirable to us,) for the promotion of righteousness,
as I appear now to be of very little use but to stick by the stuff,
and keep our outward things together as well as I can.
It is a strength and comfort to those who are going off the stage of action,
to hear of those who are in the prime of life for service in the church,
devoting themselves to it; and particularly those of one`'s own family.
I wish Samuel and Margaret`'s establishment in every good word and work;
and apprehend the way to be so,
is to keep low and humbly dependant on that all-sufficient Power,
which can enable the striplings, like David,
to make war successfully against the Philistine nature, both in themselves and others,
steadily labouring that self may be of no reputation;
and then I doubt not but they will be prosperous and useful in their generation,
and have wisdom afforded them to train up their dear children,
both by example and precept, in the nurture and admonition of the Lord.

[.signed-section-signature]
Elizabeth Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to J. T.

[.signed-section-context-open]
Ballitore, 14th of 3rd Month, 1784.

To be in a state of acceptance with our Creator,
appears to me to be the great object at which we should all aim.
As to myself,
the burden of my petition is much of late for Divine protection and Divine direction:
the cause of Christianity, which we profess to maintain,
is of all things most noble and most important.
I have lived now to the time of the decline of life,
and have done little or nothing in the promotion of this cause.
I much desire, at times,
that the small residue of my days may be spent under
more of the influence of heavenly wisdom;
that I may be enabled to act my future part more acceptably-- show
forth a more striking example of what it is to put on Christ,
and leave conspicuous and safe way-marks to the succeeding generation.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Deborah.

[.signed-section-context-open]
Foston, 7th of 7th Month, 1784.

[.salutation]
My Dear Deborah,

Having some leisure on my hands at this place,
I thought I would devote some part of it to thee,
well knowing thy affectionate regard and attention to thy near connections,
and the low opinion which thou entertainest of thyself.
These are qualities which never fail of preserving
and procuring the love and esteem of our friends,
and these I think thou possessest in a great degree.

May I and all mine dwell low in humble fear,
feeling daily after a sense of the operation of truth in our minds,
that we may not be as those who live as without God in the world; but,
witnessing from season to season, in this manner,
a renewal of our acquaintance with that which is good,
may be supported and enabled to run with patience the race which is set before us respectively.
In this world we shall, and must have trouble:
in the evidence of Divine approbation alone is true peace.

Mary particularly piques herself on being present at the yearly meeting of London,
where the first women`'s yearly meeting was established.
Remember us very affectionately to thy husband.
I much desire your welfare and happiness,
and that it may please Divine Providence to take you and your little family,
and keep you under his continued gracious care.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Foston, 8th of 7th Month, 1784.

I am often, I think,
favoured with a capacity to recommend me and mine to the protection of Omnipotence;
and I humbly trust the contrite petition and wrestling
travail of spirit is graciously heard and answered.
Indeed, if merciful help and regard were not renewedly extended to us,
what would become of us in any sense or respect?
But he who is Lord of heaven and earth,
and holds spiritual and temporal blessings in his hand,
perfectly knows and sees what we stand in need of,
and what is best and most suitable for us.
If, by his holy help and special grace, we be happily preserved in his fear,
walking acceptably before him, we shall do well, and want no good thing.
His spirit bearing witness with our spirits that we please him,
will bear us up above the little contingencies which are apt to perplex and annoy us,
as well as above the floods of temptation and tribulation,
which seem at times ready to swallow us up.
And if the counsel of perfect, unerring wisdom be,
that any shall be serviceable in his hand,
for promoting the great cause of pure and undented religion upon earth,
such may assuredly expect a double portion (the portion
of an eldest son) of trials and temptations,
and sittings, and exercises, in order to peculiar winnowing, and purging, and pruning,
and to a preparation and qualification, experimentally,
to minister to the various states of others.
"`I had satisfaction in attending the yearly meeting.
It was remarkable for the establishment of a women`'s yearly meeting, which I hope will,
in a course of time, and in the order of its course,
prove of service in our religious society.
The men seem to have slept a long time over this matter; but now,
like the rib which was taken out of Adam`'s side while he slept, I hope it will,
in process of time, become a true help-meet to the man in the discipline of the church.`"

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
Colebrook Dale, 4th of 8th Month, 1784.

This is the most extraordinary place I ever was in:
there is such a mixture of religion and worldly business,
human learning and Christian simplicity, among the people; such a native,
wild irregularity, subdued and cultivated by art and opulence, about the place.

I have my ups and downs as usual; but my heart is never so comfortable,
and I am never so well satisfied with myself, as when I am in the deeps,
with the billows passing over my head,
engaged in a travail of spirit for the promotion of Christianity,
and the welfare of mankind.
I sometimes venture, in private, to express something of my fresh feelings,
and to bring out of the store-house things that have been reposited there,
and are presently brought to hand; but my cry is for humility and wisdom,
that I may be mercifully preserved myself from falling,
and that I may not be tempted to exceed the life and authority of truth.
I know nothing more excellent, nor more desirable,
than the living virtue of it qualifying our spirits,
and enabling to move in the Lord`'s work.
I wish it, above all things, for ourselves: I wish it, above all things,
for our children; that they, as well as we,
may surrender themselves at the Great Captain`'s discretion,
make no terms of capitulation in yielding up the citadel of their hearts, only that life,
spiritual life,
may be granted them--that they may be taken into the service of their Lord.
There is no other service which is attended with such advantages:
there is safety and protection in it,
from the usurpation of other lords which have had dominion; there is maintenance,
clothing, and pay; there is honour, dignity, and immortal glory:
all these blessed privileges and rewards are involved in this important cause.
I believe our children are not insensible of this,
and I heartily desire that their obedience in all things
may keep pace with the knowledge communicated to them.
"`Hear and obey, and your souls shall live,`" is worthy of all acceptation.
First, to be diligent in waiting, in order to hear the still small voice,
which is of private interpretation to our several states individually; next,
to obey in submission and faithfulness the discoveries of the Divine will,
in the jots and tittles,
as well as the weightier parts of the law--in what concerns ourselves,
as well as in our relative duties to others:
so shall we be favoured with the inspiration of that exhilarating breath of life,
which makes and preserves us living souls.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to John Thorp.

[.signed-section-context-open]
Ballitore, 21st of 9th Month, 1784.

How little, how nothing is at our command!
However, it is our duty to endeavour to be always ready,
that if a ministering angel of good has in charge to impart any to us,
we may be found in a state capable of receiving it;
and if the prince of this world should also come with his temptations,
that he may be baffled in his designs.
One and the same state is necessary in both cases--a state of emptiness, nothingness,
and abasement of self.
This is our centre; and as each of us industriously acts within his proper circle,
and fulfils his reasonable duty,
we shall know (I believe) an extension of the cord of divine love and authority,
an increase of holy zeal and ability, and a wide field of labour.
For my part, I never expect to be worth calling any thing: I am satisfied to be nothing,
so I be but preserved from any thing that is evil; but I want thee, and such as thee,
to be what you ought to be, or, in other words, what the Master would have you to be.
Now I believe it is the Master`'s will,
that his servants shall be more and more acquainted with his good pleasure,
and the ministers of his word, as burning and shining lights.
I am indeed sometimes astonished at the beauty and
excellence delegated to some of this class,
though, like the planets,
they have no light of their own--none but as they derive it from the sun of righteousness.
And yet how liable are even such to become dim, and suffer eclipse,
`'shorn of their beams,`" and while they are preaching in words to others,
to become castaways themselves.
So that "`watch and pray`" remain to be the words
of counsel and indispensable injunction to all,
without respect of persons.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 20th of 8th Month, 1785.

Health is an extraordinary favour:
I think it is wonderful that the machines of our bodies
should go such a length of time without being out of order,
considering the complicated variety,
and minuteness and delicacy of the organs which compose them.
May we be enabled acceptably to acknowledge,
and often return due homage for the manifold mercies which we receive ourselves,
and also to intercede for divine protection and relief,
to be extended to others in distress and affliction of body and mind!
I doubt not thy frequent visits to such:
they are more becoming a Christian society--more befitting
the disciples of Christ to be exercised in,
than insipid, formal, cursory visits of show and ceremony, where light, superficial talk,
and an impertinent busying in other people`'s matters is indulged.
This is not the intercourse which the Lord has chosen for his people,
but that they should seek to visit one another in his name,
under the influence of his pure power,
and therein either keep to an inward travail of spirit for the arising of it, or,
in a proper freedom, maintain a conversation savoury and edifying.
This, I apprehend, is the way to grow in service.
Time is short, and is minutely to be accounted for.
The work we are called to, the spreading of the holy principle of Christianity among men,
is awfully important: where is the room then for idleness, supineness, and indifference,
among those who are called to be standard-bearers among the people?

Our poor nation is much destitute of instrumental help, in many places.
A living, sound ministry, accompanied and corroborated by irreproachable, wise,
and religious conduct and conversation, is a capital favour to the churches.

It behooves those who sit as judges,
to feel their way in determining concerning appearances in this line.
I have met with variety of opinions in these cases, but I ever found it safest for me,
where I could feel nothing, to remain detached and single,
and to be cautious of either encouraging or discouraging,
till I had an evidence as clear as might be expected in the matter.
And here, and in many occasional affairs arising among us as a religious society,
appears the necessity of divine wisdom illuminating our understandings,
and qualifying us to judge right judgment.
A sense of this has, at times, much humbled and prostrated my spirit,
with desire that whatever little, or however little I might be,
I might be what the Master would have me to be--I might be right.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Sarah.

[.signed-section-context-open]
Ballitore, 12th of 1st Month, 1786.

The intelligence received of the two Margarets is very pleasing, and, I hope,
causes grateful sensations.
Even thy scraps of paper, bearing that impression, are welcome messengers.
It puts me in mind of the ancient Romans,
who were so exceedingly fond of Augustus Caesar, in the latter part of his reign,
that it is said, I think, in their ordinary letters on business or friendship,
they generally subjoined, "`the emperor is well.`"

I am glad thou hast had this season of sojourn in Clonmel.
I hope it will have rivetted still more closely the
connection between thee and thy brother`'s house;
also between thee and divers dear, valuable friends and relations, in that place.
I rejoice to see my children delight in the company of the worthy and the good:
it is a sign that the dispositions and inclinations of the inward man,
are rightly modelled and turned: such intimacies add strength to strength, they are safe,
they are salutary, they are honourable; but a confederacy with the raw, the irreligious,
those who are in the spirit of the world, and enemies to the cross of Christ,
manifests unsoundness in the spiritual constitution,
by the vitiated taste of desiring and relishing food that is not fresh, plain,
and wholesome! "`Tis dangerous, and destructive to the tender, precious, life.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Joseph and Sarah Poole.

[.centered]
On the death of their son, who died of the small-pox, 12th month, 1785, aged sixteen.

[.signed-section-context-open]
Ballitore, 12th of 1st Month, 1786.

[.salutation]
My Dear Friends,

Having heard of the great trial which you have undergone, in the privation of your fine,
hopeful son, I had a mind to manifest my remembrance of you in your affliction,
by sending you a few lines;
although I seem to myself in a situation unqualified to administer any good,
and I know not what I could say on the occasion,
which reason and religion have not already suggested to you.
Both these heavenly gifts speak the same thing:
they tell you that there are many reflections which would tend to mitigate your grief,
and to alleviate the burden of your sorrow.
You had, I believe, much satisfaction and comfort in your son, when he was spared to you:
you extracted many gratifications from his society:
for a number of years he helped to make so much of your
pilgrimage through life more tolerable and pleasing to you.
It proved to be consistent with a wisdom,
far superior to our finite views and fallacious prospects, to remove him,
at his appointed time, from this earth.
He had been preserved, even in the slippery paths of youth,
from the evils that are in the world.
He had led such a life as rendered him fit for the awful change.
You had comfort in the life, and you have hope in the death of your son.
May it be the will of our great Creator, to sanctify this affliction to you,
and effectually support your spirits under it; that when he gives,
and when he takes away, you may be enabled to bless his name, and,
like obedient children, humbly and resignedly submit to all the dispensations allotted,
whether joyous or grievous.

My wife and children join in dear love to you both, with your truly affectionate friend,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Sarah.

[.signed-section-context-open]
Ballitore, 2nd of 4th Month, 1786.

Letters from my absent, distant children, do me good.
The observation of their good dispositions often weighs
my mind down in humble gratitude to the author of all good;
and yet, without keeping up the watch;
without seeking to be enabled to offer the daily sacrifice in the temple;
without dying daily to self, and mortifying the carnal will;
without keeping low and humble,
and in a state of absolute dependence on all-sufficient and only-sufficient help;
without this we all, both parents and children,
shall make nothing out in a religious way: we shall be but as a door on its hinges,
opening and shutting, and remaining in the same place; we shall be mere formal,
lukewarm professors of the faith of Christ, but never rightly-spirited,
noble advocates in his cause.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret

[.signed-section-context-open]
Ballitore, 1786.

It is well to be made rightly sensible,
that to have our expectation from the creature is vain and uncertain;
that frailty and disappointment are the characteristics of visible things,
and that that which is invisible and eternal,
can alone satisfy the longings of an immortal spirit.
I had a letter lately from William Mathews, from London,
He seems to think well of the person who came over to London,
from the people who seem to be under some degree of convincement in France.
He likewise mentions a considerable convincement in North America.
Known to the Almighty Author of all good, are his own wise and gracious purposes:
how near or how far off is the time for a more general spreading of the light of Christianity,
is among the secret things which it belongs not to us to investigate.
Neither know we as yet how this matter will turnout;
whether it be a clear and open vision that these persons are favoured with,
and whether faithfulness and stability will be added to right knowledge:
but of this we may be certain, that truth is truth, whether men receive it or reject it;
and that no cause ever did, or ever will exist,
more worthy of the entire dedication and devotion of all the faculties of the human mind.

I have been treated with my grandson`'s second letter.
I think he bids fair for being a good scribe.
I felicitate him on his beginning to learn French, and wish him good speed in it.
I observe many get a little superficial smattering in that language and soon lose it:
I wish it may not be the case with Abraham.
This is his season of life for learning languages,
and those things which chiefly occupy the memory.
This faculty is now in perfection with him, and should be fully employed:
it is compared to an arch, which is strengthened by the weight laid upon it.
In a few years the memory will rather decline, and the judgment ripen,
when arithmetic and mathematics will be in season.
I know it is the fashion with many, who do not mean to send their sons to universities,
to explode and decry Latin as an useless acquisition: it may, perhaps,
be unprofitable in this sense, that it may bring them in no money;
the concerns of civil life may be transacted quite as well without it;
the finest productions in that language are translated into the mother tongue.
French is more essential to accomplish the gentleman, to accommodate the traveller,
and is the most universal vehicle of verbal communication;
but Latin has been for ages past, and I believe will be for ages to come,
(if the world stand,) the ground-work of the literary part of liberal education.
It is like the root of all the most refined living languages;
and when a foundation is laid in this, the rest are readily learned.
In our own tongue, so many thousand words branch out from the Latin,
so many Latin words are adopted into our language and become a part of it;
and so many familiar Latin phrases and expressions
are constantly used in speaking and writing,
that an ignorance of Latin leaves one much in the dark, and, like bad spelling,
betrays an original defect in one`'s tuition.
An adept in Latin knows, as it were by intuition,
the powers and fitness of words derived from that fountain, and uses them accordingly;
he has opportunity of reading historians, moralists, poets, and orators,
in a language which no translation does any thing like justice to: translations,
compared with such originals, are like shadows compared with substances,
and like unanimated, compared with animated nature.
Do let Abraham learn Latin immediately: he may go on with his French at the same time.
The store of learning is no burden.
There are many changes in life: he may possibly be put to his shifts in future life,
and be glad to get his bread by his wits, like his grandfather.
When stripped of all, the Latin scholar can say: "`Omnia mea mecum porto.`"
+++[+++i.e. All that I have,
I carry with me]. I hope that my first-born grandson
will be permitted to cultivate that literary knowledge,
which, when kept in due subordination, is an useful ornament in society.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
Clonmel, 24th of 7th Month, 1786.

I think I can say, in truth, I feel an increase of tenderness,
and a disposition to do everything in my power to make thy last days easy and comfortable.
Thou hast been dedicated, in soul and spirit, body and substance.
The prime of thy days has been devoted to the promotion of the noblest cause;
and the affairs of this life, in which thou wast honourably engaged,
were transacted in due subordination,
and with reference to the great and principal object, the glory of thy Creator;
therefore,
in great mercy thou art released from a principal part of this world`'s cumber,
and the desire of my heart is oftentimes for thee,
that thy spirit may be visited with the rich, the blessed, infusion of heavenly joy.
And I am glad, as we advance to old age,
to feel an increase of pure desire for thy present happy tranquillity;
and a renewal of that love which first cemented our spirits together,
and was the original motive to that union,
which has (I trust by Divine appointment) long ago taken place between us;
an union which, I believe, has been blessed and sanctified.

I trust you at home are all under the gracious care and protection of kind Providence.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Sarah.

[.signed-section-context-open]
Clonmel, 7th Month, 1786.

You are all very dear to me.
I rejoice in the hope of your taking root in the Divine soil.
The Great Husbandman sees and knows all his plants, and the different species of them,
and what kind of ground is best for each.
We may observe some trees thrive best in a deep and rich,
and others in a light and sandy soil.
Some love a dry, and others a marshy bed: nay, there are some which grow, as it were,
out of the very rocks, where there is no depth of earth, and flourish amain:
so that hardness itself, if rightly endured,
(i. e. patiently endured,) is not always unfavourable to religious growth.
If it be of Divine appointment it is good; for whatever He ordereth is good,
and in season: but if our own misconduct, disobedience, or indolence,
has caused our hearts to grow callous and unfeeling,
I know nothing we poor creatures can do to help ourselves.
We must patiently wait till He, without whom we can do nothing,
is pleased to raise a will and desire in us to seek judgment;
and having happily found it, let us dwell under the corrosive operation of it,
till it performs a radical cure.
Then light and life, and a good day, is again experienced,
and an increase of holy fear and care not to offend again:
for if there be a frequent repetition of faults,
the spiritual delicacy and sensibility will gradually wear off;
estrangedness from the power and virtue of truth will ensue; the relish,
even for angel`'s food, will be lost;
and the spiritual constitution will be totally changed.

In this mixed state of existence, my dear Sarah,
we are liable to many temptations and fluctuations.
Retiredness of spirit, simplicity, and obedience, are all we have for it:
if this be kept to on our parts, we may be assured that He, with whom we have to do,
will not be wanting on his part.
His gracious design is to do us good, to bless us, and make us happy here and hereafter:
he is willing to enter into an everlasting covenant with us.
He will assuredly perform his part,
but if the conditions of the obligation be not also performed on our`'s,
the covenant is annulled, and anxiety, distress, and a tribulated path through life,
will be our portion, instead of that placid serenity and holy joy,
which often attend the minds of those who faithfully do their duty,
though amid the cares, and cumbers, and troubles, which must and will, at all events,
fall to our lot here.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Mary.

[.signed-section-context-open]
Ballitore, 11th of 8th Month, 1786.

We are much favoured, my dear children, by the countenance, kindness,
and friendship of many worthy friends;
and I believe we are all sensible that it is not by any merit of ours,
but purely through infinite mercy,
that we have been so preserved as to have the precious
unity of the living members of the church.
Should any of us slide off the foundation of conviction and religious feeling;
should any of us be caught by the dazzling splendour of the world, on any of its sides,
whether the riches, the fame, or the friendship of it; should any of us, in our hearts,
turn back into Egypt, that precious unity is immediately lost,
the rights and privileges of the saints are forfeited,
spiritual debility and decay ensue.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Mary.

[.centered]
Then on a visit at the house of Samuel Neale, who was dangerously ill.

[.signed-section-context-open]
Ballitore, 6th of 10th Month, 1786.

When thou hast opportunity, present Samuel Neale with thy mother`'s and my dear love.
He was our early and intimate friend: we often took sweet counsel together.
Our acquaintance was first formed, not in a slight, superficial manner, but in the deeps,
where the Lord works, and where his wonders are seen;
and it has been increased and strengthened through successive stages of life,
by many a cementing, humbling baptism.
He has not only been our own near and dear friend, but the friend,
and as it were father of our children,
to whom we know his love has flowed in a strong current,
to their great advantage and comfort.
So that we, to whom the welfare of our children is so dear, we,
who have no greater joy than to see them walk in the truth,
as they advance in years and experience,
to be sensible that the Lord Almighty is preparing them for, and engaging them in,
his actual service; we, surely, must highly prize such a friend,
and be nearly interested in his present trying situation.
However, we know in whose hand he is;
that hand which rescued him from the jaws of destruction, which led him, and fed him,
and preserved him in heights and in depths,
which raised him a signal monument of his mercies; and,
having brought him through many temptations and tribulations,
qualified and commissioned him to tell to others what the Lord had done for his soul:
this hand, though it might be permitted that his natural heart and flesh should fail,
is all-sufficient to uphold, sustain, and comfort the spirit,
and conduct it safely and happily into the mansion prepared for it.
But we cherish a hope that it is consistent with
Infinite Wisdom to prolong his stay awhile,
among his near connections, and the militant church, which, if it be the Lord`'s will,
we earnestly desire.
We charge thee with our very affectionate regards
to the dear and worthy companion of our patient friend:
her sufferings and anxiety on his account must be great.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 9th of 7th Month, 1787.

I am pleased that +++_______+++ has at last got into our right honourable row.
I wish him and his bride the best comfort in domestic life.
Thou canst tell them, my dear Margaret, from thy own experience, that,
though the conjugal state abounds in many endearing gratifications,
it has its own perplexities and disquietudes--that there is but one sovereign,
unmixed good, which is essentially necessary to sanctify the union,
to sweeten the attendant cares, and cause real and substantial happiness.
I wish our dear friend may get strength from her elementary dip,
and that her spirit may be often helped to get into the sacred pool,
when the angel of the Divine Presence shall have moved upon the waters.

I note what thou sayest respecting the stagnation of life among you.
I know not when I witnessed more of that stupid, torpid state,
than in our meetings yesterday: there seemed neither wind nor tide, but a dead calm:
however, if the ship be in order, the good pilot kept on board,
and his will be submitted to, no danger will accrue.

The wind will rise again when it listeth, the vessel will make its way;
and when patience hath had its perfect work, all will be well.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Birr, 4th of 11th Mo. 1787.

My present engagement is attending our dear friend
M+++.+++ D. desiring for her that she may be rightly guided,
in that line which the great Master wills;
endeavouring to make way for the performance of this service; and saying amen,
when I am able.
S+++.+++ dear S. does her part.
To be going about visiting prisons, like Howard, is a gloomy, uncomfortable task;
but it is a necessary and honourable employment.
Indeed, those who will be truly serviceable in the church of Christ, in their day,
must witness a state of very deep self-abasementmust
be willing to appear vile in their own eyes,
and in the eyes of others: all must labour long and hard,
and be content with bare subsistence, without looking for any other reward.

It is a trite complaint to say things are low.
They are indeed; but still, if each of us take heed to ourselves,
if we be diligent in waiting, and faithful in obeying, I believe,
through merciful condescension, our souls will live,
and we shall be acceptable in the sight of our great Lord and Master;
which is the perfection of our natures, and the end of our being.
So, my dear Margaret, be thou encouraged;
let the zeal of the Lord`'s house more and more absorb thee,
and be resigned and devoted to serve the Lord in thy generation, with thy body, soul,
and spirit, which are all his, and over which he has a right to an, absolute control.
I thank him reverently in spirit,
that he has allotted thee a husband who loves the truth in his heart,
and whose joy and delight it would be to see thee rightly
and conspicuously concerned in the promotion thereof.
Thou hast also a, sweet flock of children, graciously preserved and continued to thee;
thou hast many dear, select, and choice friends,
whose spiritual fellowship helps to nourish thy hidden life;
thou hast the means of a comfortable outward subsistence:
all these great favours call for a rendering something;
and this something roust be nothing less than all.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 25th of 11th Month, 1787.

No doubt thou hast been communicating with thy uncle Benjamin about the national visit,
and probably E. Pim would communicate to thee what I wrote to her respecting it.
I think we did as well as we were capable; and may say,
as thy grandmother used to say of her passage through life,
that it is well we met with no more scratches.
On the whole, I believe the service was generally satisfactory, to visitors and visited.
In some places where I expected truth would be much in dominion,
I found and felt things more low and flat than I imagined would be the case;
and in other places, from which I thought little good would come out,
I had cause to hope and believe that a seed was preserved alive,
which was well worth watching over and cultivating.
So that to judge by appearances, or former sensations, will not do:
the present feeling is what we have to go by.
I think you are much to be praised for your benevolence
to the poor sufferers by the late flood.
Acts of charity are noble, and acceptable in the sight of Heaven.
If it be at all lawful to desire riches,
it must surely be that they may be employed in such purposes.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 1st of 1st Month, 1788.

[.salutation]
My Dear Friend And Cousin,

By a letter my husband received from thee,
confirming what we heard of the awful undertaking thou hast before thee,^
footnote:[A visit to those professing Friends`' principles in France.]
(which, though now no secret,
I doubt not has long been so in thy breast,) I thought it would be but kind in
me to let thee know that I have felt sympathy with thee on that account,
as being different from other services in these days;
but the way thou hadst concluded to move in it,
appears to me as the counsel of best Wisdom.
I may say, that thy faithfulness and devotion of soul, in this and other services,
has at times done me good, and cheered my poor and often-afflicted spirit;
for what greater comfort can there be,
than to see and feel that a succession of testimony-bearers to the everlasting,
unchangeable truth is raising up amongst those who are in the prime of life,
willing to go forth under their Lord`'s banner, and in their Lord`'s armour;
not with carnal weapons; not with the wisdom, parts, or acquirements,
that any may be furnished with, as men and creatures, unless they be sanctified;
but with the weapons of his spirit, which, when humbly depended upon,
are mighty to the pulling down of the strongholds that
sin and Satan have built up in the hearts of many.

[.signed-section-closing]
I am, with much affection, thy true and faithful friend,

[.signed-section-signature]
Elizabeth.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 9th of 1st Month, 1788.

Henry Wilkins`' removal seems a loss indeed to religious society.
He had weight and experience, and I believe many good qualities and qualifications.
But these events are common, to be expected,
and to be borne with patient resignation by the survivors,
as being the dispensations of Him who doth all things well.
The capital grievance, the stinging, sorrow is, when any of the Lord`'s visited children,
young or old, fall away from their steadfastness, bring discredit upon themselves,
and upon the reputation of the spotless truth:
this is what I earnestly deprecate for myself, and for my beloved friends;
for we are no longer safe than while we watch unto prayer.
He who tempted the Master, be sure, will not scruple to attack the servant,
in whatever dignified station he may be.
As to thee, beloved cousin, I seem hardly allowed to touch upon the subject of the new,
the arduous, the awful service before thee.
I must leave it to thy own deep feelings; and as thou dwellest in the deeps,
and keepest upon the sure ground of the revelation of the spirit,
I have no doubt but that thou wilt be rightly conducted.
I believe such prospects of duty, when indubitably right,
are not always clear to the party concerned; clouds often intercept the view,
and the sun himself suffers an eclipse; the key of David locks up,
as well as unlocks the holy vision; but as the patience of the saints is exercised,
as the will of the creature is lost in the will of the Creator,
and as there is an abiding in humility, simplicity, and singleness of heart,
there is no danger but the great Shepherd will lead in and out, and provide pasture,
immediate sustenance, and provender for the service.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 9th of 2nd Month, 1788.

The last report concerning our beloved friend Elizabeth Pike was rather favourable;
so that we hope that worthy member of the church
militant will continue awhile longer in the warfare,
ere she be gathered to the church triumphant, the just of all generations.
It is a fine thing, a great favour that you had such kind friends, such attentive nurses,
such spiritual mothers to assist and comfort you in your various distresses.
It is likely some of them will soon be taken from your heads,
and carried (I hope by the spirit) into places which they know not.
The great head of the church knows his own wise purposes; whom, and whither,
and when to send forth, and whom to retain and employ in the long-cultivated vineyard.
May He be with them that go, and them that stay; for all have equal need of his help,
both for their own preservation, and renewed qualification for his service.
May gracious Providence strengthen in body, and in the spirit of the mind,
that his will may be done in, by, and through his servants;
that so the Great Name may be more and more honoured,
the knowledge of the truth extended, and the right way and worship spread among mankind.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to John Thorp.

[.signed-section-context-open]
Ballitore, 24th of 3rd Month, 1788.

I think, notwithstanding that there exists too much cause for the language of complaint,
respecting the degeneracy and depravity of the times,
that abundance of pains is taken in our religious society,
by the going to and fro of gospel ministers, publishing the way of life and salvation;
and by the laborious, arduous conflict maintained with transgressors,
in the support of our salutary discipline.
And I trust that He who sitteth in the heavens looks graciously down,
and beholds with approbation the well-meant efforts of a remnant in the cause of Christ,
and the promotion and spreading of his reign and government on the earth.
So that I wish there may not be in any a heart of unbelief,
nor a dwelling too much on the view of the gloomy side of things;
but rather that there may be a steady looking to Him who is omnipotent,
and an exercising and cultivating each the particular gift allotted,
according to the present ability, and in the will and time of the great Giver.

I am desirous for thee, my dear friend, that thou mayst look upwards,
from whence hath come, cometh, and will come thy help.
If I am not radically mistaken, thou hast received,
thou hast been honoured with a beautiful gift:
may way be made for thee to exercise it to the honour
of the holy Head and to the edification of the body,
in as diffuse a manner and degree as the Master willeth, and the church needeth.
For my part, I think it is awful to be entrusted with supernatural talents,
given for the edification of others.
If ever so usefully occupied, what is the trustee but an unprofitable servant?
but if the occupation and improvement, even of the one pound, be neglected,
displeasure is incurred, and loss and shame follow.
So that I wish us to be watchful and careful,
that we may not fall into temptation of any kind;
but that our hands may be free and skilful to build the Lord`'s house,
our feet unfettered and ready to run on his errands,
and our hearts replete with the joyful answer, of "`well done,
good and faithful servant.`"

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 22nd of 7th Month, 1788.

We were pleased with being at the province meeting of Wicklow: it was small,
but I think mercifully favoured.
My spirit was much dipped in secret travail, and I was satisfied, as I could feel and cry.
A few of us were appointed to join on the family visit in that quarter.
I hope I may say we were helped through that service.
I have heard of our beloved Elizabeth Pim`'s speaking in meeting.
I was glad that I was enabled, since I heard it,
repeatedly and renewedly to petition for her.
I do not find ability at present to write to her: I believe she is in my debt in that way.
I do not press her, but when she has a little to spare, I hope she will remember the poor.
I hope some of us are favoured with hearts of flesh, spiritual flesh,
which is nourished and strengthened by the communication of glad tidings of great joy,
and which is also pained and distressed with the afflictions of the gospel.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 11th of 9th Month, 1788.

I congratulate thee and thy husband on your return in safety to poor Ireland,
and make no doubt but that you experience at home that peaceful serenity of mind,
which follows a faithful discharge of duty.
It was a trying, arduous service which you were engaged in;
and to have been effectually helped through,
is cause of grateful commemoration of favours past,
as well as of humble trust and confidence in the same sufficient help, to abilitate,
to answer the requirings of the present and a future day.
You are now among the natural, native branches of the family;
you are not only members of it, but appointed stewards, and overseers of the household.
Your lot is also cast in a place where are many hopeful plants,
wholly I believe of a right seed,
which seem on the way of growing to be trees of righteousness,
that will bring forth precious fruit in their season.
I need not remind you what peculiar necessity there is for such as are
thus circumstanced often to go deep down for instruction and fresh qualification,
to behave aright in the church of Christ.
Many matters occasionally fall out,
which call for the exercise of wisdom and understanding
superior to that of the natural man,
and it requires a constant,
close sitting and dwelling at the Fountain-head of pure intelligence,
in order to be ready and furnished to speak and act with propriety and acceptance,
in cases of a solemn, weighty, and spiritual nature.
You have mine and my wife`'s warm wishes for your increasing in good,
and in a capacity to promote that cause, which is dignified by Heaven,
and dignifies all those who are so honoured as to
be dedicated and consecrated to its service.

I can see no cause for discouragement any way, with respect to opening the school.
The motives I believe were pure, disinterested, noble;
the object nothing less than the glory of the Creator, and the radical,
essential good of his creatures;
and yet difficulties and embarrassments may attend the commencement of the undertaking.
The institution, laudable as it is, may be sown in tears;
and the conductors of it may expect to go through good report and evil report,
as deceivers, and yet true.
Thy thoughts being low, and thy expectations not sanguine about this matter,
I look on as a good symptom, promising stability and duration.
A bright, glaring morning is often a prelude to a rainy day.
For my part, I do, from my heart,
wish this seminary of civil and religious education the best speed.

To the Shepherd of Israel, the bishop of souls, I heartily and tenderly commend you all;
and joined by my wife and children,
in a salutation of love to you and our beloved friends and kinsfolk there,
remain very affectionately thine,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth Shackleton to Her Daughter Margaret.

[.signed-section-context-open]
Ballitore, 26th of 9th Month, 1788.

[.salutation]
My Dear Daughter Margaret,

I intended to have acknowledged the receipt of thy very kind, intelligent letter,
the two last days; but the continual interruptions I meet with,
joined with my inability divers ways,
render it difficult for me to write at all as I could wish;
for it would be pleasant to me to converse with thee in this way, if I could.
I am often helpless, in a great degree, in body and mind;
at the same time admiring the kindness of my Preserver, from my youth to this day,
in doing so much for me and mine, and in affording at times a little help,
to keep in a degree of quiet resignation to bear what is permitted to fall to my lot,
in a spiritual or temporal sense, and, which is a particular favour,
the feeling my own worthlessness, poverty,
and entire inability (of myself) to do any good thing.
It must be that the reviving of ancient goodness in our society,
and the dear children giving way to the leadings of the pure spirit of truth,
bearing the cross, and despising the shame,
cannot but cause such as have any life left in them, to rejoice, and,
as it were with trembling, beg for their preservation;
that so the cunning device of the enemy of poor mortals,
may be seen in the light of the Lord, and they enabled to escape his snares,
if the mind be preserved in rooted humility, sincerity, and faithful devotion of soul,
to obey Him, who, with his dependent followers, ever had the victory;
then will joy and gladness possess the souls of those,
who have no greater joy than to see truth and righteousness flourish in the earth,
and a succession of testimony-bearers raised up.

You seem to be rich in faithful labourers, therefore you had all need to be faithful,
and not strive to live on the labours of others.
Our poor child Sarah, I wish may not meet with any thing to hurt her:
she has long been a steady, exemplary young woman.
I know it must have been very hard to her to appear in a public testimony;
but whatever she finds it her duty to put her hand to,
I wish she may not be discouraged from doing with all her might, and, like Gideon,
go forth in a sense of her own weakness.
We also heard of dear A. T.`"s amendment in health,
and appearing in a more public way than usual.

[.signed-section-signature]
Elizabeth Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah. R+++.+++ Grubb.

[.signed-section-context-open]
Ballitore, 9th of 10th Month, 1788.

My better half bids me remember her very affectionately to thee,
and to tell thee she thinks thou didst very well in coming to our province meeting,
that she had near unity with thy services,
and wishes thee to stand dedicated and devoted to answer every manifestation of duty,
whether of greater or, seemingly, smaller degree.
"`Use strength and have strength,`" is, in my opinion, a wise saying.
I believe many gifted servants have suffered loss by overlooking things as small,
too diminutive for persons of their growth and stature to stoop to;
thinking that they will leave them to others who are younger, or of an inferior order:
thus their inward man loses its agility and activity, its flesh becomes callous,
and its sinews become hard.
Continue, therefore, my very dear friend, cheerfully to submit to all kinds of labour,
which the Master may put thee to.
Labour is wholesome, and procures sweet bread.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 9th of 11th Month, 1788.

Thou wilt probably, from some one or other, have had some account of our national meeting.
We had neither T. G. nor S. N. there.
T+++.+++ G. was returned home from his visit to some parts of Great Britain,
and I understand purposed to have been at the meeting,
but for the critical situation that his daughter H. was in.
I suppose want of bodily strength, not want of inclination,
prevented our dear friend S. N. from attending.
However, other servants, and what is best of all, the Master himself was there,
baptizing spirits into a deep travail for the promoting of Christianity upon earth,
and furnishing prepared instruments to labour in
the love and in the authority of the Gospel.
Even our own dear Sarah lifted up her voice in the public concluding meeting of worship.
"`Open thy doors, O Lebanon, that the fire may devour thy cedars.`"
Both then, and at several private meetings in Dublin,
her effusions were I believe accompanied with divine life,
and acceptable to the living who were present.
Indeed, my heart has been made glad in the house of prayer,
and my spirit has waded in the deeps, on behalf of the visited youth of this generation:
the desire and petition of my soul has been,
that nothing might be permitted to hurt them,
nor mar the work of formation in and upon them; but that they may go forward,
and increase in the excellency of dignity, and the excellency of power; that so,
by and through them, under divine protection and direction,
the continued back-sliding of a degenerate people, may in a good measure be stopped,
and the Lord may be graciously pleased to return to the many thousands of Israel.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb

[.signed-section-context-open]
Ballitore, 23rd of 11th Month, 1788.

I would just simply say,
that all the near connections of my dear Margaret are much obliged by thy tender,
solicitous, affectionate care and attention to her, night and day,
in season and out of season; and having thus said,
I do not purpose to pain thee any more with a repetition of acknowledgments.
We are on a different footing, than to deal in such kind of traffic:
I shall therefore dismiss the subject with a wish, that whatever sorrows thou mayst have,
whether of this or any other kind,
thou mayst never want such a cordial friend and kind assistant, as thou hast been to her.

Abraham`'s children seem to be now finely over the small-pox,
which is a very great favour and relief to the anxious mind of their mother;
and I doubt not this merciful dealing of gracious Providence is an additional obligation,
weighing them both down, causing them to say:
"`What shall we render to the Lord for all his benefits?
May it have like good effect on all their near connections.
I hope our A. B. has by this time got a little from under the weight of the mountains,
and goes on simply and quietly in the performance of what she apprehends to be her duty;
not looking at the difficulties and dangers which may be before her in the road of life,
and so anticipating trouble before it is sent; but looking over them all,
to the recompense and glorious reward which is laid up at the end, for the willing,
faithful, obedient servant.
`'sufficient unto the day is the evil thereof.`"
And when difficulties and dangers present to her view,
let her remember the wise man`'s experience:
"`He that feareth God shall come forth out of them all.`"
And as I believe she is one of those, such, I trust and hope, will be her experience.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 24th of 12th Month, 1788.

[.salutation]
My Dear Margaret,

The last of thy precious letters, which has come to my knowledge, is of the 11th instant,
to thy mother.
I returned the 15th from Mountmellick,
having been invited to accompany Martha Routh and J. W. and the friends
appointed to perform a family visit to the friends in that monthly meeting.
I did not think well to refuse, so attended them till the visit was completed.
I trust a degree of best help was administered, and that no harm was done.
The women held out stoutly every way.
The business, I hope, may be said to have been well done;
but my expectations of consequent good fruit are not sanguine.
However, the gospel must be preached, the seed sown and watered,
and a patient travail of spirit exercised,
that the Lord of the Harvest may be graciously pleased, in his own time,
to add the increase.
How is our dear friend M. D. now?
Why, there is a fine host gone to Cork.
It was noble of cousin Sarah R. Grubb and her sister to venture there:^
footnote:[This alludes to a visit which Sarah R.
Grubb paid to the families of Friends at Cork.]
such exemplary devotion and unreserved dedication will, I trust,
accumulate large treasures for them in heaven,
let the success turn out as it will on earth.
The other worthies too, that embarked on the Pacific ocean,
in the glorious cause of the promotion of peace, will, I doubt not,
have their blessed reward.

Thou wilt, I know, like to be informed how our dear Sarah goes on.
She has several times lifted up her voice in our public religious assemblies, audibly,
feelingly, and tenderly.
In our afternoon meeting, 21st instant, she kneeled down, and in a very intelligible,
yet very affecting manner,
poured forth a solemn supplication to the great Lord of heaven and earth.
It was a time of true solemnity.
My poor spirit was at that instant wading in the deeps,
and her lively offering no way interrupted, but assisted my laborious travail.
When she has been faithful, she is cheerful, comfortable, and happy in herself; and,
indeed, I believe this is generally the case with her: her even, steady, humble conduct,
manifests the placid tenour and composure of her mind.
I have never yet spoken to her between ourselves on this important subject:
I leave her to Him who, I believe, has called and put her forth.
But frequent and fervent have been my desires on her account; and not on hers only,
but for others, to whom I am nearly united, both by nature and grace,
that you may do valiantly in your day, not looking about for little, mean subterfuges,
and pitiful evasions for self, but be willing to lose this selfish life,
that so you may find that life which is hid with Christ in God.

This is a day of revolting and backsliding--a day in which a vaunting, defying spirit,
has too much prevailed, and Israel, those who are truly the Lord`'s people,
have been discomfited and discouraged.
If those who have received gifts from on high,
and have in every respect been distinguished by peculiar favours,
both spiritual and temporal, will pusillanimously slink back,
or ungratefully refuse to comply with the clear requisitions of duty,
surely great will be their condemnation.
But I hope better things of divers of you: that you will, in the first place,
take diligent heed to yourselves, and then, as with the heart of one man,
advance under Divine direction and protection, against the common enemy.
So be it, saith thy tenderly affectionate father.

How is our dear Elizabeth Pim?
If I do not mistake, I had the last word with her in this way.
Assure her of my dear love.
Her letters are always particularly acceptable to me;
but I would not have her be uneasy about writing or not writing to me:
may she mind well the work before her! and that is enough for me.
Her preservation and her progress in the heavenly pilgrimage,
is the object of my solicitous desire.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 30th of 1st Month, 1788.

With my dear love, tell Elizabeth Pim I received her letter.
She ought, by this time, to have known me better, than to imagine that I could forget her.
She is like one engraven on the palms of my hands.
Indeed, I am as it were astonished, that people should pay me such attention,
and give me so many marks of their affectionate regard.
I wish for more and more of those humbling baptisms, which keep us down in the deeps,
and in a sense of our own unworthiness and insufficiency.
Cousin E. G.`'s salutation is very acceptable.
A+++.+++ and she are objects of our particular attachment.
I wish them to grow from strength to strength,
not only as to their own religious experience, but capacity for more extensive,
more weighty service in the church.
Good parts and dispositions, sanctified by the truth, may be, and ought to be,
and are designed to be solidly useful; and there is a danger of those losing ground,
and sliding backwards, who do not go forward according to divine appointment.

Our dear love to that family, always including thy aunt Taylor.

[.signed-section-signature]
Richard Shackleton.

--
