== Chapter III.

A further account of Abraham Shackleton.--Death of his wife.--
Various Letters.--Illness and death of Abraham Shackleton.

We shall now return to Abraham Shackleton.
After his release from the duties which he had faithfully performed in an arduous occupation,
he found himself more at liberty for the service
of that religious society of which he was a member.
Besides a constant,
regular attendance of the particular and general
meetings to which he more immediately belonged,
he paid frequent visits, in company with friends,
to meetings in several parts of this nation;
and several times attended the yearly meeting in London, even in the time of old age,
and when natural strength failed,
yet his spiritual as well as intellectual faculties witnessed no decay.
He did not appear in the character of a minister; yet, many times, in religious meetings,
in the families of his friends, and among his own household,
his words would drop from him with such sweetness and energy,
as carried with them an evidence that they were brought
up from the well of life and salvation.
Beloved and respected by all who knew him, for his unblemished life and useful labours,
he was to the last preserved in deep humility and diffidence;
preferring others to himself, walking among his brethren with all lowliness and meekness;
and exercising no authority in the church,
but in the fresh sense of the power of an endless life.
Edifying and instructive, indeed, were his words; but still more so his life and manners.
In the virtue of temperance he was an eminent pattern;
being remarkably abstemious in food, drink, and sleep; and was solicitous,
to enforce the practice of this virtue.
Solid and exemplary in his own deportment,
he was grieved when he observed levity of conduct or conversation in others.
He greatly enjoyed hearing anything good or commendable of his fellow creatures,
and uniformly discouraged all detraction; closely attending to,
and practising the counsel of his Great Master,
who enjoined that we should in all things do to men
as we would that they should do to us.
He delighted in retirement, and for that purpose frequently walked alone in the fields.
Even when he was in company,
the interior travail of his soul was visible in his countenance.
Thus he continued to devote the evening, as he did the morning of his day,
to the service of Him who gives liberally, and upbraides not;
and when from home on a religious account,
his mind was still tenderly turned towards those left behind,
as appears by the following fragments.

In the year 1760, Abraham Shackleton attended the yearly meeting in London,
and addressed his son during its sittings, from which the following is an extract.

Abraham Shackleton to His Son.

London, 2nd of 6th Month, 1760.

There really seems a good hand at work, to gather and bring things into better order.
Fifty-eight friends offered themselves willingly,
to visit the monthly and quarterly meetings in the nation;
and I hope they will have the hand of the Lord upon them, to work for Him.
I thought my heart was a little like Deborah`'s,
when the narrow path was not sufficiently occupied,
and those under the profession of truth had taken to by-ways,
that my very heart rejoiced, and was with the willing in Israel,
that offered themselves to the work.

To the memorable visit paid to the meetings for discipline in the nation of Ireland,
the following letter refers.

[.asterism]
'''

Abraham Shackleton to His Son.

Cooladine, 18th of 9th Month, 1762.

The friends from England are, Samuel Fothergill, Jonathan Raines, Isaac Wilson,
and William Rathbone;
some of whom signified they had been drawn from the nearest connections in life,
by the good Lord and Master, to visit us, in this poor desolate island.
The Master of our assemblies is with them, and the concern for our welfare,
in the very best respect, is great.
He is with them, even the shout of the Divine Majesty of heaven;
he is yet working and seeking by his instruments, and his good spirit immediately also,
to gather us near to himself.
Oh! that the children of men would keep steadily, deep to the root,
that they might bring forth right fruit,
to the honour of Him whose care for us is exceeding great!
As far as I could ever feel, none shuts a door in His house for nought,
so rich a rewarder is he: his peace, my dearest child, is enough.
Be careful never to be drawn forth into many unnecessary words;
may the right book of conscience be kept open by the finger
of Him that sees and watches perpetually over us for good;
may all our words and thoughts be brought thereto,
that we may live to Him that is everlastingly worthy.

The public meeting comfortably ended.
Isaac Wilson, and then Samuel Fothergill, laid before the meeting their concern;
and those that were not of the society, I mean those that did not profess with us, were,
in a prudent, tender manner, desired to withdraw.
And all that professed, though not in strict unity, were desired to stay.
Then, the men and women keeping their seats,
the clerk was directed to read the eleven queries, audibly and distinctly.
The overseers, in each particular meeting, gave a distinct, explicit,
and particularly clear answer thereto.
The friends, in the opening of truth, spoke excellently thereto.
Words fitly spoken, arising from the unmixed life, are, I think,
compared to apples of gold set in pictures of silver:
the expression was more than verified.
I do not expect to live to see another extraordinary visit of this nature,
and I heartily wish it may have the much-desired effect.

Abraham Shackleton

[.asterism]
'''

Richard Shackleton to His Father.

Ballitore, 21st of 9th Month, 1762.

Dear Father,

We received yours, dated at Cooladine,
and are glad that your report of this extraordinary visit
tallies with what we have already heard of that service.
It is also a pleasure, and perhaps will be a profit to us,
that you are yoked along with them.
Your letter to my wife, from Kilnock, was particularly agreeable.
I have many times thought, of late, of that king in Israel,
whose heart so rejoiced in the testimony of his God, that he forgot the man and the king,
and publicly exposed himself; appearing with the outward, visible,
and accepted signs of a priest unto God.
And who were they who despised him for it?
Such as had not an eye open to see the beauty and dignity of the sacred function;
which was not less glorious, but more so, than royal majesty.
But who are they whom the king will delight thus
to honour with proclaiming his name and truth,
and make the happy instruments of the salvation of others, and of their own souls?
Those who neither seek honour to themselves, nor shun shame.
I am, with true respect, your dutiful and affectionate son,

Richard Shackleton

[.asterism]
'''

Richard Shackleton to His Father,Then in the north of Ireland, with other Friends.

Ballitore, 20th of 2nd Month, 1763.

Last post brought us letters from cousin Elizabeth Dale.
She writes very sensibly about her situation.
As you are in a province where these mixed marriages are so frequent,
I could wish you had her letters with you: they might be of some service.
She writes:
"`To walk in a path of inward as well as outward affliction has long been my lot;
nor have I any expectation of much alteration for the better in this life.
Bereft, at times, even of the flatterer, hope,
my inward situation is perfectly known to no one person.
I am obliged frequently to appear serene and cheerful,
when my poor heart is torn with conflicting passions.
I have not a sufficient foundation in myself to support me under my daily trials,
and my attention is too much taken up and engrossed with the cares of this world.
I seldom get to meeting, my husband being unwilling that any business,
though ever so trifling, should be neglected on that account.
I have involved my poor children, too, in many perplexities.
May the Lord have mercy and compassion on them, who are innocent of my transgression,
and direct their feet in the right path, which I have forsaken, and turned aside from,
which has cost me my peace of mind!
You are a father of children--of daughters too.
It is my sincere desire that they may be preserved from falling into the like error,
and take warning from me,
who have not had one hour`'s solid satisfaction (I believe) since I married.
I once thought no power on earth capable of drawing me so far aside: secure,
and confiding in my own imaginary strength,
I dared at first to dally with the temptation; and am convinced, by sad experience,
that the most trifling digression from our known duty,
is a very great advance to the contrary.`"
Thus she writes to me.
All our dear love to you, presented by

Your dutiful and affectionate son,

Richard Shackleton.

[.asterism]
'''

Abraham Shackleton to His Grand-Daughters Deborah and Margaret Shackleton, At School.

Ballitore, 21st of 7th Month, 1765.

Dear Children,

When I hear of the unfair walking of several under the profession of truth,
(the very truth of God; a truth that will stand the test, through all generations,
to the end of time,) I am concerned for you, my dear children,
that you may fully answer the end of your creation,
by glorifying the Great Author thereof, and be lights to others,
that they may safely tread in your steps,
who are concerned to follow the self-denying Jesus,
who bade his disciples to take up their daily cross,
and follow Him in the strait and narrow way that leads to happiness.
Thus your words will be few, and convey something profitable to your school-fellows.
My ardent desire for your lasting welfare, not only your reputation among men,
which is to be regarded, but that you may grow in favour with the Most High,
whose presence fills heaven and earth, from whom nothing is hid,
makes me think of the beloved disciple: "`I have no greater joy,
than to hear that your children walk in the truth.`"

Abraham Shackleton.

[.asterism]
'''

From the Same to the Same.

Ballitore, 4th of 9th Month, 1765.

Dear Children,

Peggy`'s letter to your father, of 2nd instant, is before me;
and it is pleasing to hear of your health and welfare, and will ever be so to us.
I have been too much hurried with building up a part of my house,
and live in fear of losing the sweet communion inwardly with my Maker,
which is by far the best treasure; being the help afforded mercifully to us poor,
short-lived mortals, for a preparation for a never-ending eternity.
You know this, my dear children,
and I hope are not unmindful of this most important point.
Early piety, you have heard, is acceptable to God.
Be sure, with all your getting learning,
neglect not diligently to look for that fear which keeps the heart clean.

Abraham Shackleton.

On the 11th of the 4th month, 1766, died Rachel Carleton,
aged 78. Of this respectable woman, thus speaks her daughter Shackleton.
"`My mother went through much trouble, for a great part of her life,
which seemed to be allotted in great mercy, as she had something in her nature high,
though a prudent, careful woman in managing her household affairs,
and in training her children;
very much against dishonourable conduct in those who professed the truth; and was,
I believe, more in substance than in show.
Towards the latter part of her life she seemed gradually
to be brought into more of the simplicity,
and was of a tender spirit, very grateful to the Author of all our blessings,
for His kindness in making her latter days more comfortable than she could have expected;
my husband being an affectionate son, using his endeavours to make her happy,
and the company of him, his worthy father and family, seemed helpful to her.`"

In this year, also, died Roger Shackleton, the beloved brother of Abraham,
who had at different times enjoyed the satisfaction of his company in their native land,
and with whom he kept up a regular correspondence.
Roger Shackleton was a person of solid sense, great worth and benevolence,
much esteemed within and without the pale of his own society.
The archbishop of York valued his character, and was pleased with his conversation;
and some of his flock complained how little influence they had with him,
"`while Shackleton can persuade him to what he pleases.`"
He appears to have been a man of clear judgment, both in spiritual and temporal matters.
In a letter, on his brother`'s opening school,
after several judicious remarks on the best mode of teaching, he concludes:
"`And as to family charges, disappointments, and exercises, to do the best is a duty;
but to be uneasy at what cannot be helped is a fault; for this world,
and the things of it, are mutable.
So the chief thing of all, and the height of happiness,
is to have the mind turned to God; for the world is but the circumference,
and He the centre, and the nearer to him, the more of self-abnegation;
which state I desire we may all seek after, and grow therein.`"
(1725.)

The advice given to his young nephew, Richard, deserves consideration.
"`You may tell your son, I am glad to see he is so good a proficient in writing,
and other learning; and as for his casting about in his mind, that others,
educated for school-masters, often, in some part of their lives,
quit that business for others which offer,
which he thinks is discouraging to one who thinks for himself,
and is qualifying himself to acquire a living by what he is, through care and study,
improving in.
In the first place,
I think it is enough for a student to improve his
time in what his genius and future profit directs,
and when he is turned into the world he has a probable way of a livelihood;
and when anything falls in his way afterwards, that offers more liberty or advantage,
he may embrace opportunities as others do, or have done;
and if in his other projects he should miscarry,
then his fund of learning is a relief which other miscarrying tradesmen may lack.
So that there is, even in the light he sees matters in, encouragement to proceed steadily.
And I wish, as for my own children, that he may pursue the truth;
i+++.+++ e. seek for the knowledge of it in his tender years:
it is a better portion than an earthly inheritance from a family,
or any acquired parts whatsoever, and, as it is preferable to all things else,
it ought to be sought early; and where it is found and attended to,
has a happy effect on the mind, in governing and steadying it,
and in purging away all that is vile in the spirit or affections.`"
(1740.)

The account which he gives of the distemper among the horned cattle, in 1748,
conveys an affecting idea of that calamity.
"`Among horned cattle the contagious murrain spreads,
and makes great havock in this county,
as it has done for several years in other more southern parts.
It is within two miles of this city (York.) In one town, about nine miles off,
there are but three left alive; and people go four or five miles, it is said,
for milk for their families.
The distemper baffles all human skill and precaution;
so that His hand that delights in mercy, is severe in judgment,
no doubt to carry on the wise, good, and great ends of his providence.`"

The next letter, in order of time, is from

Richard Shackleton To Thomas Carleton.

Ballitore, 13th of 2nd Month, 1767.

Dear Cousin Thomas Carleton,

I seem, doubtless, unmannerly or negligent, in never making any reply, in writing,
to your kind and friendly invitation to your marriage,
not at all writing to you on that subject.
Be assured my silence has not been caused by inattention, nor lack of affection;
but a multitude of affairs, of various kinds, and lack of a fit disposition of mind,
not lack of inclination, prevented.
I now greet you and your spouse with my wife`'s and my dear love,
and sincerely wish you health and happiness,
and the renewed evidence of a Divine blessing upon your union.
You are now joined together, I hope, by the ordering hand of Providence.
You are advanced a step higher, into a more conspicuous station in life and business.
The author of every good and perfect gift has given you, my dear Thomas,
and I believe to both of you, a good share of natural capacity, and the means,
through frugality and industry, with his blessing,
of procuring a comfortable subsistence.
He has placed you in a great and populous city,
where you profess his holy and saving truth,
among a large number of others of the same profession,
who do not honour it as they ought in their lives and conduct.

Now, my dear cousins,
my mind is a little uncommonly engaged for your temporal and eternal prosperity,
and I think I see the path, and the only one which leads infallibly to it.
It is by humbly, diligently, steadily, and faithfully seeking to the Almighty Benefactor,
for his preservation and blessing to be over and about you,
and all that is under your hand.
Strive not either to be or to appear great;
nor stretch your wings beyond the circumference of the nest, which,
in the set ordering of all-wise Providence, is allotted for you.
Rather live under, and appear under your ability, than over.
You will experience safety and quietness in it.
The contrary is a temptation and a snare, and an inlet to many dangers of various kinds;
and often, with new beginners, lays the foundation of difficulties, straitness,
and embarrassments, which they are sometimes never disincumbered of,
till they are disincumbered of mortality.
Let us take a little view, my dear friend,
of the persons and families which have been up and down,
during our short time of observation; let us contemplate them,
not with an evil nor a pitiless eye,
but with an eye to the ways of that all-ruling Power, which resists the proud,
yet gives his grace additionally and manifold to the humble.
Let us centre down, and have our dwelling low,
in a conscious sense of our own unworthiness,
and insufficiency to direct our own steps and prospects,
either as to the things of this or a better life,
without his blessed protection and mediation.
Be truly humble, my dear Thomas; be frequent, and, as much as possible,
constant in feeling after a capacity to breathe in secret after
an acquaintance and communion with the Author of all goodness.
Be exemplary in your conduct and conversation, and exterior appearance and deportment,
as becomes the disciples, followers, and professors,
of the religion established by Him who was meek and low in heart,
and whose garment was without seam.
So will you,
in proportion to the purity of your intentions and
the cleanness of your hands in his sight,
gain the favour and approbation of Him who knows the heart,
and has all power in his hand to bless or blast at his pleasure.

I am concerned and desirous, my very dear friend,
that your determined conduct may be such, now in the setting off in life,
as that the good-will and approbation of Heaven may be to and upon it:
if you happily attain this, it must certainly be by being a pattern of humility,
steadiness, and plainness, among your numerous acquaintance in that city.
This may occasion some trials,
in which it will often be proved whether your attachment to the testimony of truth,
or to the spirit of the world, is most prevalent.
According to the free-will choice which you will be enabled to make,
will your ability to proceed aright be strengthened or weakened,
and finally the one side or the other get the victory.
The day of small things, and of little requirings of duty,
proportioned to the state of children, is by no means to be despised.
The cross to our own depraved wills is often to be borne, and many old friendships,
connections, habits, and propensities, of a hurtful or unprofitable nature,
will be dissolved or decay: in the room of which, new desires and affections,
new intimacies and society will gradually be formed.
But in all that he throws down, as well as in all that he builds up, the Lord Almighty,
as we rely upon him, and are faithful to his discoveries,
will be found to do everything right, and for our good, every manner of way.

I might perhaps write more on this subject, but I should rather be under than over.
I most heartily commend you and your dear wife to the grace and good spirit,
guide and comforter in your own hearts,
which is of itself entirely sufficient to lead you
safely through this dangerous and troublesome world,
to everlasting happiness;
and which I hope will be sealed in your minds to the rectitude of this little counsel,
and to the sincere love and unfeigned desires for your welfare,
in which it is simply given.
Indeed,
it is not very usual with me to feel such a flow of earnest and solicitous wishes
for the happy setting forward of any young couple of my acquaintance in life.
May the right love and unity increase among us.

Remember us very kindly to your father, and believe me, dear cousins,
your truly affectionate kinsman and sincere friend,

Richard Shackleton.

Thomas Carleton had married an amiable young woman.
His father (Samuel Carleton) and his friends were much pleased with the connection;
but how often are we taught that we have nothing certain while in, mutability?
The hopes which Samuel Carleton had cherished for his declining years,
were suddenly destroyed by the death of his son, who was taken off by a fever,
in about a year after his marriage.
The heart of the disconsolate father rested on the amiable young widow; but,
in the course of another year, he had to resign her also to an early grave,
she having fallen into a decline soon after the death of her husband.

Abraham Shackleton having gone to attend the yearly meeting in London,
was there taken ill.
The following letter is from Crewgate, five miles from Namptwich,
"`at the house of a kind friend, Thomas Mullenas,`"

27th of 6th Month, 1767.

My Dear Son,

I was taken unwell in London, on first day week, in the evening; but,
by the care of my kind friends, was so far recovered that I set out on the 17th,
and got to Namptwich in Cheshire; but being attacked there with an intermitting fever,
my dear friend, J. C. after watching and caring for me night and day for four days,
removed me to this kind family, where I lack no outward thing that I know of,
for my recovery.
According to my present sense I am mending; and may, if Providence, kind Providence,
who has not I hope left me destitute, please, set forward in a few days.

As J. C. cannot be prevailed on to leave me,
if I should be removed by death be sure let him not
be at any expense from our coming to Namptwich.
I wish his watching and caring for me, may not impair his health.

If I get not home, I am sure you will cherish all in your power your mother,
my faithful wife and dear companion.
And forget not her sister;
and I should think she might be placed with cousin D. Carleton:
there is enough to do justice to every one.
I have no doubt of your care in all things.
For your son, I hope you will have comfort in him, and in the rest of your children:
that will be only as they attend to the inward saving principle of grace and truth.
My dear love to your mother, yourself, your wife, and yours, and to enquiring friends;
wherein my dear and over-careful companion joins, your affectionate father,

Abraham Shackleton

Abraham Shackleton recovered, and returned to his family,
who were thankful for being spared this threatened trial.
His valuable wife, who was some years his senior, and debilitated by rheumatism,
could seldom leave her fireside,
where she received her friends with a countenance innocently sweet,
and engaged in cheerful conversation, denoting a truly humble mind.
She at all times freely gave up her beloved husband,
for the service of Him who had blessed them with his favour.

Margaret Shackleton was seized with a paralytic affection in her throat.
She saw her end approach, not only with Christian fortitude, but with Christian joy,
saying,
she "`was thankful to have passed through the wilderness of the world with so few scratches.`"
She desired her son and his wife to take care of their aged father,
and not let him work too hard,
(for he loved to engage in agricultural employments.)
She only regretted parting from him.
The last night of her life, while he watched by her bedside,
she conversed with him on past occurrences, in a very interesting manner.
The next afternoon, while he sat by the fire, he felt his mind so overshadowed with good,
that he rose and went to the bedside to communicate his feelings to his dear partner,
but her sweet spirit had just fled: and the young heart of her grand-daughter Margaret,
who was present, was also sensible of the sweet and sacred sensation;
and when some one wanted to soothe her, she said: "`O no; it is not grief.`"
She died the 4th of the 3rd month, 1768, in her eightieth year:
and Abraham Shackleton gave up housekeeping, and lived with Deborah Carleton,
who took affectionate care of him to the last.

Abraham Shackleton to His Children.

Dungannon, 17th of 9th Month, 1768.

My Very Dear Children, Richard and Elizabeth Shackleton,

Though I am personally separated from you at present, I do not forget you,
but am sincerely concerned that you may grow in grace,
and the inward and saving knowledge of God and Jesus Christ; who,
I have in some small degree, at times, since I left home, been made sensible,
would be a tender father to his obedient children.

I should have been pleased with a more particular
account of the health of relations and friends there,
than in my son`'s two last letters; though, as to my own part,
I often find it safest to say and write little.
At times I have been filled with fear for S. J.`"s son and daughter:
do you feel for them and for your own.
The temple of the heart ought to be kept clean and disencumbered;
the spirit of the world defiles and unfits it for
the reception and abode of the heavenly guest.

Abraham Shackleton.

[.asterism]
'''

Abraham Shackleton To a Relation

Ballitore, 12th of 10th Month, 1768.

It is certain, if we are not watchful and careful to step along in true fear,
during our pilgrimage through the wilderness of this world of dangers,
we shall suffer great loss, and let an enemy into our habitation,
who will sow one kind or other of evil seed,
and suffer the loss of the unity of the spirit, the inward guide,
which is the bond of such peace, as far too many are quite strangers to,
seeking only to gratify a carnal inclination.
And sooner or later they that do so must needs "`reap
corruption;`" when they that sow to the spirit,
taking good heed to that unerring guide, the experienced apostle tells us,
are to "`reap life everlasting.`"
And the fruits of the spirit are meekness and sweet peace and joy, even in this life.
Such are preserved by the rod and staff,
and are no strangers to the working out their salvation with fear and trembling;
and if they hold out in true faithfulness to the end of the race,
will not be surprised without the heavenly oil in their lamps, at the midnight cry,
"`The bridegroom comes,
go forth to meet him;`" they having been so wise as to keep their lamps burning,
and their lights (to others, edifying lights) shining.

I remember, my dear cousin, I felt good, inward good, in your house,
and this certainly is the saint`'s food; by this, the bread that descends from Heaven,
their souls are nourished up to eternal life.
The poor in spirit hunger for this, and he that tries and knows their poverty,
and the sincerity of their honest heart, fails not to fill and feed them in due season,
that they faint not; for his goodness and tender mercies endure forever.

You have children; tell them where durable riches are to be found:
watch over them that they may be fruitful vines growing by the sides of your house;
that so the Lord of life, who is continually watching over us for our good,
may have babes to praise him from one generation to another.
Oh! that I could see, while here,
the sweet-smelling myrtle and fir-tree succeed the thistle and thorn,
that only encumber the ground, and bring not fruit, like trees of righteousness,
to the honour of the good husbandman, who is looking for fruit.
Let us not, dear cousin, be unmindful to watch always;
and thus being preserved in our allotments,
we may be of some service to our children and others,
and have authority and true discerning to rebuke the stubborn, strengthen the weak,
and comfort the feeble-minded,
and be useful members of that spotless church whereof
Christ Jesus is the holy head and high priest.

My son and his are a comfort to me in my old age,
and join me in true affection for you and yours.

Abraham Shackleton.

A gentleman,
whose extravagance and dissipation had reduced him to a languishing state of health,
was surrounded by those who had not courage to inform him that his life was in danger.
Elizabeth Shackleton was greatly concerned to hear this,
and imparted her feelings to him by letter, as follows:

Elizabeth Shackleton to +++_________+++.

It will undoubtedly appear very strange to +++________+++,
to receive a letter of this kind from a simple woman,
and perhaps be a subject of ridicule;
but if you knew what has passed in my mind within these three days about you,
I believe you would give some attention to it.
I heard you were very ill; not likely to be long in this life.
I felt compassion and concern for you,
and would have been glad to be with you at that time, that I might endeavour,
if it were possible, to persuade you to seek your own good at His hand,
who created you in his own image, for a purpose of his glory, and your own happiness;
gave you strength of body, a rational understanding,
a sufficiency of the good things of this life for
your own support and the relief of others,
and, above all favours, a gift of his divine and saving grace,
to instruct and lead you safely through life; for the apostle declares,
"`The grace of God, which brings salvation, has appeared unto all men,
teaching us that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly, in this present world.`"
Now I desire you will examine your own heart,
whether you have been thus led by this grace,
or whether you have turned from it into wantonness, excess, and profaneness,
not regarding the fear of the Almighty, who is the dread of nations,
and to whom you are under so many and deep obligations;
who could have cut the thread of your life when in your full strength, if he pleased,
yet has spared you in mercy, to see if, you would return to him.
And now, perhaps, the abuse which your constitution has got, may cause nature to fail,
and your body to return to its original dust;
when the part in you which is of eternal duration,
must appear before the impartial judge of quick and dead,
there to receive a reward according to the deeds done in the body:
therefore I beseech you,
as a Christian--as a fellow creature--as one who has felt
something of the terrors of this just judge for evil,
that you will lay aside all intemperance.

Consider these things seriously,
and humble yourself in the sight of the great Lord of heaven and earth,
before whom kings must bow, and the potentates of the earth lay down their crowns;
that so you might find mercy with him who wills not the death of him that dies in sin,
but rather that all should repent, return, and live;
which is manifest in the expressions of the prophet.
When personating the Almighty he says: "`Wash, make yourselves clean,
put away the evil of your doings from before my eyes; cease to do evil, learn to do well,
seek judgment, relieve the oppressed, judge the fatherless, plead for the widow.
Come, let us reason together, says the Lord: though your sins be as scarlet,
they shall be white as snow; though they be red as crimson, they shall be as wool.`"
And though you may have gone great lengths in that road that leads to destruction,
yet it seems my business to persuade you not to be discouraged,
by thinking you can not find mercy from turning to the Lord, who would have mercy;
and to our God, who would abundantly pardon.

I have no view in writing these things, but the ease of my own mind,
that I may be clear of your blood; and the good of your immortal soul,
whose welfare I wish as my own, and am, your true friend,

Elizabeth Shackleton

Ballitore, 20th of 1st Month, 1769.

It is said, that the person to whom the above letter was addressed,
was much affected thereby, and had it read to him repeatedly as he lay on his deathbed;
also, desired that it might be sent to another gentleman, who, he said,
needed such advice as much as himself.

Abraham Shackleton to Margaret Shackleton

Dublin, 30th of 4th Month, 1769.

My Very Dear Grand-daughter,

Your welcome and acceptable letter was received.
There are two worthy living ministers of the gospel of our Lord and Saviour Jesus Christ,
arrived in this city from my native country; they exhort us to abide in the littleness.
My very soul, and everything within me that is worth notice, says amen to it.
I think I have been stripped to the very root since I came to town; but,
thanks to Him who, though he hides his face for a moment,
will never totally forget his little flock, he appears in the needful times,
and his hand is filled with consolation.
Let him be your chiefest joy, my dear, and then you will step wisely in your pilgrimage;
little minding what people think of you, if you have but the smiles of his countenance.

My health is much better this morning; and if I should not live to see you,
and the rest of you there, who are near and dear to me, I trust, through mercy,
to be gathered to the generations of those gone before,
whose robes are happily washed in the blood of the Lamb.

I am, with endeared affection to your aunt, brother, sisters, and my friends there, yours,

Abraham Shackleton

[.asterism]
'''

Abraham Shackleton To Deborah Carleton

Dublin, 2nd of 5th Month, 1769.

Dear Cousin Deborah Carleton,

After a sinking, low, distressing season of inward poverty this morning,
a degree of consolation springing up, and you therein,
and your extraordinary care of me in my old age and widowhood,
being brought into remembrance, I venture to address myself to you in a few lines,
wishing you better health than you have had of late, and,
what I am sure is far more desirable,
that you may be favoured with divine and heavenly peace:
this is what sweetens all our bitter cups.

My health of body is pretty much better these two days,
and I am thinking of setting forward with my friends, towards the yearly meeting.
Whether I may be favoured with strength to return to poor Ireland, is hid from me:
I cannot see it.
However, I desire humbly to confide in Him, who is able to help to the last,
and in every difficulty.

My dear love attends my grandchildren, and if I should not live to see them again,
I wish them well.
They have tender and religious parents and friends also to watch over them.
Oh! religion is a heart-work indeed: may we all diligently, in very deed,
labour for that peace that passes the understanding of the natural, unregenerate man.
Our meeting is now quite over: it has been a season of consolation and inward advantage,
I hope, to many.

And now I desire, my dear friend, that grace, mercy, and peace,
and the fruits of the spirit, may be enjoyed by you,
and abundantly multiplied in your breast.

Abraham Shackleton

[.asterism]
'''

Richard Shackleton to His Father, (then in London.)

Ballitore, 14th of 5th Month, 1769.

Dear Father,

We were much pleased to find, by yours from Chester, that you got safe over,
and had such a ready passage.
We should have been more pleased if you had been
a little more explicit about your own state of health.

It is true, my present situation is among the pots; yet I am a prisoner of hope.
I am indeed an impotent man, nor is there in me, nor in the powers of my nature,
any capacity to crawl near the salutary waters, much less to impart of them to others.
I can say of a truth, I am glad to see my equals, my familiar friends and acquaintances,
become my guides, take the lead,
and grow from strength to strength in the great Master`'s cause.
It is my earnest desire that I may never injure it;
but having waded here through many deeps,
(unknown to mortals,) I may be so preserved in my sorrowful pilgrimage,
as that I may at last lay down my weary head in peace,
and be admitted any where within the door of perpetual rest.

You will feel while at London whether your strength of body and
draught of mind seem sufficient for you to make a tour into Yorkshire:
if these unite,
no doubt it will be a reciprocal satisfaction to you and our relations there,
to have that visit performed, and such an opportunity of taking a mutual (perhaps final,
solemn) leave.

With sincere desires,
that if this attendance of yours at that great and solemn assembly be the last,
it may be particularly distinguished to you by the
renewed seal and evidence of Divine favour,
making green, fresh, and signally honourable in your old age, I rest,

Your very affectionate, dutiful son

Richard Shackleton

[.asterism]
'''

Richard Shackleton to His Son

Ballitore, 4th of 11th Month, 1769.

My Dear Child,

We leave our large family, and great charge, not for any private, temporal gratification,
(which yet at times might be lawful,) but from as firm a persuasion as our state,
etc. admit and require, that it is our duty, both private and relative,
to go to these solemn assemblies, in order to worship our great Benefactor,
to whom such homage is in all reason due,
and to lend a hand or heart to help forward the general good of our community,
in exciting to their religious duties.
On this solemn account we go.
We leave you, dear child, at home,
expecting your care and assiduous assistance in our absence.
I trust you will not deceive or disappoint us in these hopeful
expectations which we have formed of you.
I often bow the knee of my soul, in prostrate gratitude to the Father of spirits,
on account of the pleasing prospect which his goodness has afforded me of you,
my dear children,
being likely to embrace the offers of his merciful visitations to your tender minds.
Prize them, I entreat and charge you, as your chief treasure: cultivate that field,
and it will yield you a plentiful harvest, even the crop of all necessary,
present benefits; and, what is infinitely more valuable, of eternal life.
Be sober, dear child; be vigilant against a crafty adversary; love retirement,
practise it; feel after something that is supernatural, to help, preserve,
and comfort you; and you will grow from one degree of grace to another,
and in favour with God and good men.

Richard Shackleton

[.asterism]
'''

Abraham Shackleton to His Grand-Daughter Deborah

Dublin, 8th of 11th Month, 1769.

You are your father`'s first born;
may the God of her who proved serviceable to her people,
dwelling under the notice and blessings of the Almighty, and under the palm-tree,
bless you in all your undertakings, and make you a good example in the family,
and a happy instrument of good in the church of Christ; and that the daughters of men,
together with your religious parents and friends, may bless God on your account,
says your aged, affectionate grandfather,

Abraham Shackleton

P+++.+++ S. I hope to remain waiting upon Him that is waiting to be gracious to sincere souls,
and feeds them, as they steadily look up to him, with food convenient:
they know his rod and his staff, and what it is to be fed with food convenient.

The following letter (without date) was written by Abraham Shackleton to Samuel Neale,
previous to his embarking for America, where he went on a religious visit,
in the year 1770.

Although I am one of the least of my Heavenly Father`'s children,
several times since I saw your letter to my son,
I had it before me to salute you with a few lines.
I find He, that, in his abundant mercy and lovingkindness,
when you walked in the broad way, gratifying your corrupt appetite, visited you,
and fastened the crook of love on your heart, and reconciled you to himself,
is now sending you forth to call to others;
even to rebuke the disorderly and comfort the feeble-minded,
that many may be brought into the Shepherd`'s fold,
and experience true peace and fellowship with the Father and his Son Christ Jesus.
I trust the Lord, who is leading you forth, will be your consolation and strength,
and your dwelling-place be in him, in your passage to that once wilderness country,
both by sea and land, by night and by day; and may he arm you, my dear friend,
on the right hand and on the left, and anoint your eyes with eye-salve,
and give you true discerning; that you may not be cast down on the one hand,
nor be hurt by the flattering, fawning spirits on the other.
It is settled with me to say, may the Lord of the Harvest,
who ministers seed to the sower, be with you in your steppings along,
and feed you with food convenient for you;
keeping in a sense ever mindful of his instructive rod and his supporting staff,
well knowing that the unity of the Holy Spirit is the bond of the saints`' peace.
I have been greatly pleased formerly, when favoured with your company,
to observe the watchful care that clothed you,
even in the times of enlargement and liberty of spirit,
lest any word or unguarded expression should inadvertently pass,
to wound or administer offence, in any wise, to the least babe in Christ.
It is in true friendship I mention these things,
well knowing the monstrous red dragon is as busy as ever with his tail,
to draw down the bright stars from the heavenly habitation.

Abraham Shackleton

[.asterism]
'''

Abraham Shackleton to His Grand-Daughter Margaret

Dublin, 5th of 5th Month, 1770.

My mind is mostly centered among those who are begging their bread,
and had rather be honestly poor, than filled with unwholesome food,
and lose my appetite for that which nourishes the soul up to eternal life.
At times I thankfully acknowledge,
to the praise of the bountiful hand that satisfies the hungry babes with proper sustenance,
I have partaken with the poor of the flock, of what keeps me from fainting,
and encouraged to hold on my way in watchful fear.

I long that you may be watchful, and grow in the root of life:
there is true and real comfort to be experienced.
My love and best wishes attend you all.

Your affectionate grandfather,

Abraham Shackleton

[.asterism]
'''

Richard Shackleton to His Daughter Margaret.

Dublin, 8th of 5th Month, 1770.

Dear Child,

I have your agreeable letter: your grandfather also received yours.
We are in usual health.
The concluding meetings are to be tomorrow.
It has been with me as is usual in my attendance here.
The several dispensations which we are under in our religious pilgrimage,
may be compared (I think) to the various turns, roads, and lanes in a journey.
I am at present, and have been for many years, in one long lane:
when I shall get out of it I know not.
The believer is not to make haste.
The great point is to make straight steps,
and keep steadily right on our way in the right road, without loitering,
looking unnecessarily behind, or, in the impatience of our own spirits,
pressing too hastily forward.
Indeed, I find the road of this life so bestrewed with difficulties and dangers,
and myself so exceedingly weak, and unable, by my own powers,
to preserve alive my own soul,
or even to succeed in my temporal transactions by reason of my peculiar incapacity, that,
under this sense, I cannot but commit me and mine, with great earnestness,
to the protection and help of Divine Providence.

I have been several times a little in company with your sweet friend, as you call her,
(Elizabeth Pim.) I have found my spirit renewedly and nearly united to her and her sister,
since I came to town.
There are too few here of their stamp.
Too many are taken up with foolish, trifling gewgaws, quite unworthy of the noble,
rational mind, formed by its great Author for far higher contemplations and enjoyments.
For lack of spiritual exercise, they have lost their spiritual health;
they have no appetite for sound, wholesome food;
their vitiated taste must be gratified with something
that gives a little momentary pleasure,
but fills the body with distempers.

Your affectionate father,

Richard Shackleton

From the Same to the Same.

Dublin, 6th of 11th Month, 1770.

I greatly desire the welfare of some of my young friends in a very particular manner;
but the warfare between the spirit which is not of this world,
and the spirit which is of it, is great and difficult:
the situation of some makes it more so to them.
And the Being, who is the source of all our happiness in time and eternity,
is a jealous Creator, demands (as is his just right) the whole heart,
and will not accept of a partial sacrifice: he requires the prune, the best,
a whole burnt offering.
May you, my dear child,
steadily resign yourself in all humility to be guided in his wisdom,
so will you be preserved an exceeding great comfort to me, a blessing to the family,
a way-mark, a good example; and an ordinance of help to your near and dear friends,
whom you love, and by whom you are beloved.
Thus you will be preserved out of the evils which are in the world, and the perplexities,
perturbations, and troubles consequent to them;
you will grow from stature to stature in the experience of good; and though,
in taking this cup of life,
(which is a cup of mixture,) you may expect to meet with trouble,
yet you will still find and feel the reward of your diligence, faithfulness,
and obedience to be peace.

My love to you is such that I could willingly enlarge,
but I am seldom in a situation fit for this manner of converse, when I am here.
And besides, there is an unction which teaches all things that are necessary;
truth in the inward parts, to which I refer you as the most sure counsellor,
fully capable to instruct you in all things appertaining to your spiritual progress,
and to bring all things to your remembrance in due course;
supplying abundantly the lack of instrumental help,
and making up every deficiency to those who are acquainted with it.
And without we become acquainted with it,
all other advice and assistance will stand us in little stead.

Your affectionate father,

Richard Shackleton

[.asterism]
'''

From the Same to the Same.

Ballitore, 18th of 12th Month, 1770.

My Dear Margaret,

I received yours yesterday morning: it was very acceptable,
as it conveyed variety of intelligence.

The capacity for writing on the best subject, I know well, is not in our power,
and better not meddle with it when it does not come freely.
Your grandfather has been poorly for several days past.
It is quite uncertain, altogether in the hand of Providence, how it will turn out.
It may be a means of his translation from earth to heaven,
or it may prove a renewal of health and strength to him.
I know, on hearing this, you will be uneasy at being from him.
But content yourself in patient resignation: if he grows worse,
you may be sure we shall soon send for you.

Richard Shackleton

The last illness of Abraham Shackleton continued some months,
with intermissions which gave hopes of his recovery, but these hopes were soon overcast.
He suffered great pain at times, which he bore with exemplary patience, saying,
that he was mercifully dealt with.
The national meeting falling out at this time,
his son and others of the family attended it.

Richard Shackleton to His Father.

Dublin, 27th of 4th Month, 1771.

My Dear Father,

Though I am not agreeably circumstanced, in several respects, for writing at present,
yet I look upon it as my manifold duty to send you
a line of short intelligence about our meeting today,
seeing you were disabled from being present in body with us.
Your absence, as well as many other vacancies which have happened,
and the lack of that solid weightiness which should
clothe the spirits of those who sit in such a meeting,
was cause of humiliation and distress; yet I humbly believe,
that a degree of that which only makes a living soul, reigned over all.
The accounts received from the three provinces,
were much in the usual strain of language, not worse; but I think, if any alteration,
rather more agreeable than of late.
My brother (school-master) John Gough, I hope,
enlarged in his peculiar gift to general edification.
Our friends Samuel Fothergill and John Stephenson opened, I believe,
in pertinent counsel and remarks, accompanied with gospel authority and evidence.
The former had it on his mind to propose in the meeting,
the holding of a general meeting of conference, collectively for friends of both sexes,
in which the London queries should be read, which is accordingly agreed upon,
to begin at nine o`'clock on second-day morning.

We received Debby`'s letter this afternoon:
I fear that they will have trouble at home about A. W. Perhaps the accession
of his present complaint may hurry him out of his poor decayed body.
May he have a place of rest prepared for the poor spirit.
The righteous has hope at his death, a period that inevitably awaits us all;
and those who go off before us,
precede us that follow by a very short interval of fleeting time.
My wife and daughter join in dutiful and cordial wishes for your restoration,
with me and many more.

I remain, with dear love, your dutiful and affectionate son,

Richard Shackleton

[.asterism]
'''

Abraham Shackleton to His Son.

Ballitore, 28th of 4th Month, 1771.

Son Richard,

He from whom we have everything that deserves to be called truly good,
this morning has been pleased to open a little nook
for poor me to sit and wait among his servants,
that at times are mercifully favoured with some small
degree of help and strength to wrestle for the blessing,
and the continuation of a sense of his presence to accompany
through their pilgrimage to the very end of it.
Oh, my dear son, sincerity of heart is necessary, and is, I am sure,
too much lacking among the professors of the very truth,
as it is manifested and revealed unto a small remnant in this very poor nation.
Alas! my son, in the sense I have at present of the declension,
their number is become so very small, that a skilful child might write them.
I think, while I see the tares, the grand enemy has sown in this drowsy state,
fastening to the weighty grain, or endeavouring to do it,
and choking thorns and fowls of the air making sore
devastation among the seed of the kingdom,
I think I see you sitting close by the willing in Israel, whose hearts,
through infinite mercy, the Lord is moving upon,
and stirring up to work for him in the day afforded.
Though at this time my mind chiefly points to yourself, I by no means forget my daughter,
your consort and fellow-labourer, to whom remember me dearly; also be sure,
with much affection, to Samuel Fothergill and John Stephenson.
Nor do I lack love for my other friends, to whom you may present it.

Your father,

Abraham Shackleton

P+++.+++ S. Since I wrote the above, I have to acknowledge the receipt of your letter,
and am much obliged to you for the intelligence thereby imparted to us,
and hope you there will still continue to remember us you left at home.
I believe I should be exceedingly glad to see my endeared friend Samuel
Fothergill if it should be so ordered that he came this way;
but much desire that nothing may unfit or render him incapable
of attending his more weighty service at London,
where I have understood he intends going.

Abraham Shackleton

[.asterism]
'''

Richard Shackleton to His Father

Dublin, 30th of 4th Month, 1771.

My Dear Father,

I was favoured with yours of the 28th instant,
and in hopes it may afford some entertainment,
would give you a further detail of our meeting, if I could remember it;
but as one billow succeeds another,
so one exercising opportunity follows so closely upon another,
in my deep wadings and weary steppings along,
that I cannot always retain particulars in my remembrance.
The meetings have been uncommonly large and crowded.
It has been almost wholly the lot of our friend Samuel Fothergill to burn incense publicly.
He is, indeed, carried on wonderfully.
His Master dignifies him, and exalts his testimony through him:
he is made like the show-bread on the altar--some sacred symbol that is eminent,
conspicuous, attended with a degree of glory,
in order to attract and engage a people too much outward, and,
if possible by instrumental means, enamour them with the beauty which is in the truth.
Such is the mercy and condescension of the Creator, who uses various means, in wisdom,
that his creatures may not perish forever; and leaves all without excuse,
that their perdition may be of themselves.
The London queries were read and answered yesterday,
in the meeting of conference of Friends of both sexes.
Samuel was beautifully drawn forth upon this occasion, as usual.
The public meeting today, was very large and Samuel was concerned in testimony,
also feelingly and fervently in supplication;
I thought the meeting for discipline in the afternoon yesterday was flat;
this afternoon more lively: I have had pretty close employment upon committees,
etc. so that, at home or abroad, there seems little rest to the sole of my foot.
Neither is it in oil that I dip it when it does rest;
but if it returns to the ark of the testimony, and sinks or swims along with it,
I may be satisfied.

I am, dear father, your affectionate, dutiful son,

Richard Shackleton

During the continuance of Abraham Shakleton`'s distemper,
while it was any ways suitable for him, he struggled to get out,
to sit with Friends in their religious meetings,
waiting therein for a renewal of strength to his inward man; and when prevented,
by the progress of his disorder, from attending meetings,
he was visited in his own apartment by many Friends,
to whom he was often drawn forth in sweet counsel, to the tendering of their spirits,
under the influence of the precious sense and power which accompanied his words.
Many were the seasonable opportunities of this sort, and many the sensible,
weighty expressions that dropped from him, in the course of his painful, tedious illness,
which reduced him to very great bodily weakness.
His flesh, indeed, exceedingly decayed,
but his spirit was constantly renewed and replenished with heavenly oil;
so that his lamp burned bright to the very last;
and in holy confidence of a happy change, a little before his departure,
he said to his relations about him, "`I have no cause to grieve,
neither would I have you.`"
Yet he mentioned, in true humility, that he had nothing to trust to,
but the mercies of the Almighty.
His mind was often favoured with inward joy; and one night, after much bodily pain,
he was so filled with heavenly consolation, that, with a melodious voice he said,
"`I am well: I feel no pain: I feel good.
Oh, the elders! the elders! they should dig for the arising of the well of life,
as with their staves in their hands.
Spring up, O well, and I will sing unto you.`"
At another time, in a manner similar to this, he uttered these words:
"`Those that are faithful to the end shall receive a crown, a crown that fades not away;
but rebellion is as the sin of witchcraft.`"

The night before his decease, a young man,
about whom he had several times been anxiously concerned, being brought to his bedside,
though his speech faultered, he spoke in a living, sensible manner,
with the authority of truth on his spirit.
And to one of his own family, who was present,
he addressed himself in a most affecting and encouraging exhortation,
as if taking a last and solemn farewell.
The next morning, though his speech grew worse,
he spoke in a tender and cordial manner to some of his family.
Some of the last articulate words he uttered,
were expressive of the help and comfort which he felt;
and even when his speech quite failed,
his manner and gesture were such as those who were intimately acquainted with him knew
he would often use when his excellent spirit felt the power of truth in dominion.
He departed this life in great peace, the same day about noon, the 24th of 6th month,
1771, aged seventy-four years; and after a very large and solemn meeting,
to which his remains were brought,
they were interred in Friends`' burying-ground in Ballitore, 27th of the same.

His son long felt and long lamented the loss of such a father--such a friend;
and that sorrow, which he indulged in secret, in the chamber where he had seen him die,
sometimes burst forth at his own table, surrounded by his friends.
The mantle of the departed worthy seemed to have descended on his son, who,
deprived of his precept and example, endeavoured yet more closely to follow Him,
to whose service both had been dedicated.

Long was the loss of this exemplary and venerable man felt,
even by a wider circle than his own connections.
On this occasion his former pupil, Edmund Burke,
thus writes to Richard Shackleton "`I am heartily
affected with the subject of your last letter.
I had a true honour and affection for that excellent man.
I feel something like a satisfaction in the midst of my concern,
which I had not in the same degree before,
that I was fortunate enough to have him once more under my roof before his departure.
He was indeed a man of singular piety, rectitude, and virtue; and he had,
along with these qualities, a native elegance of manners,
which nothing but genuine good-nature and unaffected simplicity of heart can give,
and which they will give infallibly, be the exterior forms what they may.`"

The following is an extract from the Testimony, concerning Abraham Shackle ton,
of Ballitore, Ireland, 1774.

Reverent, awful, solemn and teaching to the thoughtful beholder,
was his deportment in religious meetings.
His humble spirit deeply and patiently waited (sometimes watched
and waited long) for the resurrection of divine life:
when this was present, he had all things; when this disappeared,
all comfort seemed withdrawn.
And, indeed,
as he seemed beyond most men to take little satisfaction
in anything but the precious truth itself,
so, we believe, he was beyond most men favoured with the overshadowing of it.

And John Griffith, in his Journal, page 274, 1760, says of him:
"`I met with my good friend, Abraham Shackleton,
who travelled with me most of the time I was in that nation,
(Ireland.) Of him I think it may be said, as was of Nathaniel:
"`Behold an Israelite indeed, in whom there is no guile!`"
He was a great comfort and help to me;
and though he did not appear publicly as a minister,
yet he would drop tender advice at times, in families, in a very affecting manner.
His whole conduct, looks, and deportment, were so leavened and tempered with good,
that I looked upon him as a preacher of righteousness wherever he came.`"
