== Chapter IV.

Letters on different Subjects, between the Years 1773 and 1780, inclusive.

Richard Shackleton To Samuel Carleton.

You have so far coincided with my sentiments.
Now let me further add, in my humble judgment it will not prove to your advantage,
for several reasons, to spend time unnecessarily in Dublin,
when your affairs will be settled there, so as that you can handsomely leave it.
Many inconveniences attend an indolent life any where, especially there.
Come as soon as you can into the country among your friends, where are wholesome air,
opportunity for exercise, and, in some places, wholesome conversation;
of which last I would not be supposed to mean as if I thought the city entirely destitute.
You are heartily welcome to my house, and need be in no hurry, but at your own leisure,
and after due consideration and trial,
fix your head-quarters where you may think most proper;
like the bird disencumbered and raised high from the earth, that sings up in the air,
and looks down and chooses what spot to alight on.
Thus may you, dear cousin, being more unfettered from the cares of earth,
soar nearer to heaven, making melody in your heart,
and anticipating the joys of that happy place.
So shall your last days be your best days; and after all your troubles, conflicts,
and besetments, which I believe have been many, and of various kinds, you will,
through the infinite goodness of our great Benefactor, find and feel sweet peace at last.

Accept of the hearty salutation of my father, wife, sister, and children.
I am, dear cousin, very affectionately yours,

Richard Shackleton.

After the death of Abraham Shackleton,
Samuel Carleton came to live with his cousin Deborah.

Richard Shackleton to His Daughter Margaret.

Ballitore, 24th of 1st Month, 1773.

May you, dear child, be preserved in simplicity and nothingness of self;
in humility and lowliness of mind, seeking diligently after, and waiting steadily for,
the inward experience of that which is unmixedly good.
This is the way to be helped along, from day to day,
through one difficulty and proving after another, to the end of our wearisome pilgrimage;
having recourse, like the hunted hart, to the brook by the way,
when pressed by our spiritual enemies.
By this, my dear child, the predecessors in our family, who lived in the truth,
were enabled to wade through their afflictions,
and knew that overcoming which entitles to the glorious, eternal rewards.
Many are the favours which you, my dear daughter,
have received at the hand of the great Giver.
What need I enumerate any of them?
your grateful heart is sensible of them.
May your branches, weighed down with humility, gratitude, and all fruits of the spirit,
bend towards the root which sustains every tree of righteousness,
and from which its sap and life is supplied and derived.
By humility and lowliness of mind, many temptations are avoided, and incumbrances escaped.
It is a safe and quiet habitation, into which the devil cannot enter;
and his emissaries view the dwelling with derision, and turn from it with contempt.
So the heavenly guest has more free admittance, and uninterrupted abode;
and the bread eaten in secret administers invisible but effectual support.
I am, dear Margaret, your affectionate father,

Richard Shackleton.

In this year Dr. Leland published his history of Ireland,
and Richard Shackleton received a letter, with the signature of the author,
requesting his opinion of the work.
The style of the letter gave no very favourable promise of the abilities of the historian.
Richard Shackleton sent a civil reply, disclaiming any pretensions to critical judgment,
and soon after received the following letter from the real author.

Dr. Leland To Richard Shackleton.

July 2nd, 1773.

Sir,
My absence from Dublin prevented me from receiving your favour till this day.
Whoever he was that took the liberty of addressing a letter to you in my name,
and whatever were his intentions, I account myself obliged to him.
He has indeed been guilty of an unprovoked incivility to us both;
but he has been the means of introducing me, in some sort, to one,
of whom our common friends have often spoken with the utmost affection and respect,
and with whom I exceedingly wished to be acquainted.
I know not in what terms the request was made,
that you would give your opinion of my book; but I beg you will allow me to repeat it,
with sincere esteem, and a very just sense of the value of your opinion.
I shall return to Dublin in the course of next week,
and my first care shall be to send a set of the History of Ireland
to Mr. Jackson`'s. If you do me the honour to peruse it,
I must entreat you will not send it back, but accept of it,
as a small mark of my sincere regard.

The book has been read in England, and received with more favour than I hoped for.
Here it has had a few attentive readers; but as to the public in general,
I was ever persuaded, that in this kingdom, at least,
their voice would be determined precisely in the manner you mention.
I am sorry to say that you will find it very incorrectly printed.
Believe me, with very sincere respect and regard,

Sir, Your faithful and most obedient servant,

Thomas Leland.

[.asterism]
'''

Richard Shackleton To Dr. Leland.

Ballitore, 17th of 10th Month, (October,) 1773.

Dr. Leland,

I had the favour of writing to you some time ago,
and handed you the original mock letter which gave rise to our correspondence.
I have not had the pleasure of hearing from you since,
but perused your history with the best attention which I was capable of.
I am much obliged to you for the book,
and for the entertainment and instruction it has afforded me.
Good history casts such a light on all sides, and upon such a multitude of objects,
and is so nearly concerned with religion and morality,
that he certainly deserves very well of the public, who contributes,
in so great a degree, to their pleasure and profit,
by presenting them with a work of this kind.
Your history, without doubt, has cost you much painful labour:
there must have been much pioneering, much fable and falsehood to clear away;
and when this has been done,
but scanty and bare materials left to erect a comely edifice.
However, the cement is so good, and the several parts so aptly joined together,
that we see a complete, well-finished, though not a magnificent structure;
a structure which, in my opinion, will last,
although a flood of calumny and false criticism should assault it.
I only speak my own unbiassed sentiments:
I have neither opportunity nor leisure to ransack and examine the stores
from which the great leading historical events have been drawn;
but I have all along particularly remarked such a diligent,
wary investigation of the reality of facts and characters,
that I attend to the narrative with the satisfaction which a man feels, who is persuaded,
from the cautious veracity of his author, that what he hears is true.

A history of our own country is in some respects like a history of our own times;
it necessarily, by some means or other, touches so nearly particular families,
that it is no wonder if individuals are piqued in some cases,
whose family pride or interest is concerned; and, taking offence at a part,
decry the whole work.
Self-love sits close to us,
and we do not like to see an aspersion he even on our own family names.
Different sentiments also in religious matters,
cannot fail of operating variously on those who read such a history:
these sentiments being interwoven among our earliest prejudices,
and fast rooted and rivetted by our judgments or our feelings,
are not indeed easily shaken, but very sensible of any rude attack.
On this account I am also of the number who think some part of your history exceptionable.
The expression which I wish to be altered is cited below.^
footnote:[Vol.
iii. p. 504. "`But those called Protestants were chosen from Quakers,
or other enthusiasts--from the poor, the profligate, and contemptible.`"]

I know very well that the people called Quakers have their frame and organs,
and are subject to like passions with other men;
and that through the deceivableness of unrighteousness, and delusion of a subtle enemy,
who is transformed into an angel of light,
they may be mistaken and led astray in their religious exercises, unless,
according to the apostle`'s advice, they watch and be sober;
unless they patiently wait and watch for the appearance of Christ by his spirit,
in their hearts, who told his then present followers,
"`without me you can do nothing;`" and who encouraged his future
followers to expect the same aid by the promise of "`Lo!
I am with you alway, even unto the end of the world.`"
Unless they thus wait, they may run before they are sent,
and offer the sacrifice of fools: and unless they be sober and steady,
keeping to the feeling sense of divine truths, and under the guidance of divine wisdom,
they may, as well as others, follow the imaginations of their own brain,
instead of immediate revelation, be deceived themselves, and deceive others.

These dangers, my friend, I frankly confess attend us;
but I also hope and believe we are, in general, happily preserved from them.
I do not think that we deserve to be caricatured in the lump,
with the denomination of enthusiasts.
However,
this does not cause but that I hold both the author
and his history in great respect and estimation.
I admire the celebrated writers of the Augustan age,
who yet looked on the primitive Christians in their time, as a contemptible,
insignificant sect; and thereby proved the truth of the apostle`'s observation,
that the world by wisdom knew not God.

I hope you will excuse the liberty which I take in thus expressing myself:
I assure you it is not without sentiments of real regard and esteem.
I am persuaded that Dr. Leland has pondered deeply on the most interesting subjects,
and knows that a religion which does not enter into a man`'s feelings,
and influence his life, can be of no service to him: it is inanimate, dry, and formal.
Yet, as a man`'s feelings can only be rightly known by himself,
can often with difficulty be explained to others,
and often cannot at all be comprehended by them, it may be necessary that a people,
dissenting from a national religion and way of worship, established by law,
should give some reasons for their dissent, and a rational account of their faith;
I therefore hand you herewith a treatise on our religious principles,
which I beg leave to recommend to your solid perusal;
and whether you will approve of it or not, I request that you will accept of it from me,
as a token of my sincere regard, Who am, respectfully yours,

Richard Shackleton.

[.asterism]
'''

Dr. Leland To Richard Shackleton.

November 23rd, 1773.

Dear Sir,

It is not without sincere regret that I have been so long diverted
from my purpose of acknowledging the favour of your last letter,
and the obliging present that attended it.
A variety of cares and occupations, on my appointment to an extensive parish in Dublin;
and some intervals of languor and depression,
occasioned by the remains of those nervous affections which
I contracted by making more use of my pen than my horse,
are the only excuses I can make for so long a silence.
Let me at length entreat you to accept my cordial
thanks for a letter so flattering to me,
and which confirms me in the respectful sentiments I had entertained of the writer.
I am particularly gratified by the candour and kindness
of your remarks on the difficulties I encountered,
both in collecting and selecting the materials for my history,
and the appearance of veracity that it bears.
My task was indeed laborious,
and whatever violence I might do to prejudices and prepossessions,
I considered myself as an evidence before the tribunal of the public,
and as solemnly bound to declare the truth, to the best of my knowledge,
as we should have been had I sworn and you affirmed.
The consequence has been, in this kingdom, as I supposed:
my representations have not given entire content to any party.
I have been already attacked from different quarters, but with so much impotence,
so much frivolous and captious folly, and so shameful an ignorance of the subject,
as are perfectly mortifying;
for I confess I should have liked to have been called
out by an ingenious and plausible critic.
Forgive a little ebullition of vanity,
when I declare I felt somewhat of the ardour of a much younger and cleverer fellow.

Optat aprum autfulvum descendere monte leonem.

And now,
none but the most ignoble beasts of the field have deigned to take any notice of me.
But I am abundantly consoled by a number of such testimonies as yours;
and in a country where Irish parties are little regarded,
I have received a great deal more than justice.

But I cannot sufficiently thank you for the truly polite, ingenuous,
and candid manner in which you have urged your objection
to one particular expression that escaped me.
If it be Quakerism to enforce the momentous distinction between the vital,
influencing spirit of Christianity, and the nominal and formal profession of religion,
I have ever been preaching Quakerism, and God grant I may live and die a Quaker!
But instead of entering into certain discussions,
in which I might not express a difference of sentiment with the same politeness,
or to give it a more honourable name, with the same spirit of meekness,
that you have done, I at once plead guilty,
and acknowledge that no religious sect should ever
be generally included in any one invidious appellation.
Had I received your favour before the octavo edition was printed off,
the expression should not have continued in it:
I must take the first opportunity in my power of correcting it.

Farewell, my dear Sir, and believe me very gratefully and respectfully,
your obedient and affectionate servant,

Thomas Leland.

[.asterism]
'''

Richard Shackleton to His Son.

Dublin, 7th of 5th Month, 1776.

Religion, which is an acquaintance with God in spirit,
is the noblest principle which man is capable of.
But the activity and energy of it is not at man`'s command.
We are to be quiet, passive, and not seek to stir up our Beloved till he please.
Let us abide at home (in the house) till intelligence arrives that the Master is come,
and calls for us.
Men, willing and running of themselves after the knowledge of religion,
as they do after discoveries in natural science, bewilder themselves,
and effect nothing that is profitable.
Patiently wait, and quietly hope, is the lesson which we should learn.
How dry and like ashes our minds are,
when the flame of religion (I mean the active present virtue of it) is extinct.

You have, my dear Abraham, a weighty charge devolved upon your youthful shoulders.
You have great occasion for wisdom.
I am, indeed, your affectionate father,

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Wife.

London, 1st of 6th Month, 1776.

This is a time and place for deep feeling, weighty, concise speaking,
and close attention to a variety of church-business.
It seems that this yearly-meeting is larger than common,
and indeed it is an awfully-splendid sight to behold.
To be sure, many come, perhaps, in a light mind and vain curiosity,
to the general meeting of business: however,
there is a noble appearance of valuable friends, of deep spiritual wisdom and experience.
Men of great capacities speaking like children, glorying in being servants of the church,
and despising all treasures in comparison of those laid up for them in heaven;
contemning every connection, comparatively, except a connection with Christ,
and those ties which are confirmed and sanctified by his spirit.
William Dilworth, William Rathbone, and Isaac Wilson are here, endued with gifts,
and exercising them in the beauty of holiness, to the edification of the church.
There are young people here, of such a number and sort,
as would do your honest heart good to see them.
In the effusion of love and life, and in the torrent of a powerful testimony,
in the meeting of business,
Isaac Sharples proposed a nomination for a visit to the counties and places in England.
The representatives from Ireland prevailed on the meeting to extend the visit to Ireland.
It was very agreeable to see what numbers of the first rank
and eminence voluntarily gave in their names for the service;
others were nominated by their friends.
Some, who were backward in offering themselves at the first sitting,
gave up their names afterwards,
and seemed as if they dared not go home til! they had made that sacrifice.

There were, I believe, threescore and ten valuable friends given up to this service,
who are to divide themselves and separate to the work.

Richard Shackleton.

[.asterism]
'''

From the Same to the Same.

London, 6th of 6th Month, 1776.

I have been these two last nights at Edmund Burke`'s, in Westminster.
They have been very kind, and he is indeed an admirable man.
I thank Divine Providence that my relish (I hope prevailing, uppermost,
permanent relish) is for other things.
Indeed, the distraction occasioned in the mind,
by being of necessity occupied by two different objects,
causes a disagreeable sensation in a spiritual constitution weak as mine.
People may judge and think of me, some better, and perhaps some worse than I deserve;
but He that sees in secret, at the same time that he knows my infirmities,
and that I am as a reed shaken with the wind, sees also, I trust,
the sincerity of my heart, and prepares many an offering therein.
The more any of us are impregnated with the seasoning virtue of true religion,
the more savoury is our conversation and mutual communication.
And, indeed, all of us, young and old, have need, in each of our departments,
to feel after and witness its efficacy: we need it for food, we need it for cleansing,
we need it in prosperity to limit and preserve us,
we need it in adversity to sustain and console us.

Richard Shackleton.

In this year Richard Shackleton gave his second daughter, Margaret,
in marriage to Samuel Grub, and, on her settling with her husband in Clonmel,
he writes thus:

Richard Shackleton to His Wife.

Ballitore, 28th of 7th Month, 1776.

I suppose you are very busy settling poor Peggy in her new habitation:
the parting with her, and assigning her over into another family,
and unto a distant place, has caused a sensation new to me.
After a connection has been formed by nature,
strengthened by the most endearing ties of religion, friendship, and affection,
and improved by long acquaintance and familiarity,
a separation of this sort comes near the heart, and affects our finest feelings.
We, I include my dear sister Carleton, formed her (or rather the Great Master formed her,
and made us instrumental in his hand to model her) to be of use and service in her generation,
in the place allotted to her.
We might not expect to keep her always to ourselves.
May she be the Lord`'s, and in body, soul, and spirit devoted to his service,
whom she will experience to be the best of Masters; and I am persuaded that her honest,
worthy husband will further her, all in his power, in every good word and work.
Their preferring the duties of religion before all things,
giving it the preference on every occasion, rejoicing when it flourishes,
and sorrowing when it suffers,
is the way to draw down the Divine blessing on their heads,
and to cause them to be as happy as is consistent with human condition.
Debby and Abraham assist finely in their departments;
and if our M. and S. be spared to us, and we to them,
I doubt not but they will be a comfort to us.
When I say this, it is with a hope that they will bend their minds the best way,
live in an awful reverence of their great Creator, and, above all things,
fear to offend him.
Without witnessing a sense of religion to leaven their spirits,
their company and conversation would be but insipid and unsavoury to us;
and they would ever be in danger of falling into snares and many temptations,
which are laid by the adversary of mankind for incautious, giddy youth.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Mary.

Ballitore, 30th of 7th Month, 1776.

As my dear Mary bespoke me to write to her, I think to send her a little scrawl.
I hope your dear mother and you have been bravely since you left us,
as (through favour of kind Providence) we generally are.
I do not doubt but you receive many civilities and marks of affectionate
regard from your friends and new relations there.
People who are civil themselves are generally treated with civility,
but the froward meet with those of their own stamp.
For my part, when I was lately in England,
I did not not know what to do with the peoples`' kindness.
Indeed, I believe I should have been in danger of being hurt by it, but for one thing.
I had got, by long experience, some knowledge of myself,
and I well knew that of myself I was poor, weak, unstable, ignorant, insignificant;
and that if I had any little capacity to step aright, or drop a word to edification,
it was no merit of mine, it was by the grace of God; a name, my dear,
which I would not make free to write,
but that I feel a solemnity unexpectedly cover my spirit,
while I thus hold converse with you.
You also be careful, my beloved Mary, to centre deep in humility and abasement of self:
it is the tree which takes deep root downwards,
that is most likely to stand against the storm.
This is the spring-time of your life.
May your tender, innocent heart he open to receive the precious seed,
which I trust the great and good Husbandman will condescend, and has condescended,
to sow therein; may He also be pleased to water it with the visitations of his love,
immediately and instrumentally; may he guard and protect it from every noxious thing!
You see how your elder sisters have made choice of religion, as their principal treasure.
You also be a wise child;
and whatever natural abilities it may please the great Creator to endue you with,
or whatever acquisitions or improvements you may make of those natural gifts,
by contemplation, reading, or converse, you are only acceptable in the sight of Heaven,
(however man may estimate you,) as you take heed to the grace in your own heart,
to be restrained by its restraints, to do nothing contrary to its gentle remonstrances,
and to obey, in humility and simplicity, its leadings and requirings.

My dear child, above all things be humble, be humble.
Humility goes before honour: it is the humble whom the Lord teaches of his ways.
We have in each of us a certain something, appertaining to self,
(it is of the flesh,) which profits nothing in the work of religion.
This fleshly part is pleased, and nourished,
and swells with the praise and commendation of fools; for wise men would not puff up:
and we have need of frequent retirement to the gift, the grace in our minds,
that in the tranquil, cool hour of the day, not inflated by vain knowledge,
or perturbed by passion, we may, in the stillness of all flesh, hear what this monitor,
this good spirit, this faithful witness, says to our states.
Perhaps when, figuratively speaking, all men speak well of us, this heavenly, sure,
unerring word of prophecy, which preaches to our own particular states, as individuals,
will condemn or reprove us.
This is what we are to go by, and judge and estimate ourselves by; and not by the crude,
superficial, hasty, partial judgment of capricious mortals,
whose favour veers about like the wind.
My mind is often exercised on behalf of my children.
You are the children of many prayers.
You have hitherto been a great comfort to your dear mother and me,
and we have no greater joy than to see you walk in the truth.
It is neither in our will, nor in our power, to do great things as to this world for you.
We are not like many others who have large possessions and lucrative business.
Providence, in the wise distribution of his favours,
has allotted us a lower rank in life; yet, with industry, care, and prudent economy,
he has enabled us to procure a sufficiency.
And indeed a great redundance is not desirable:
the Up of truth has pronounced how hard it is for a rich man to enter the kingdom.
A little sufficiency of the things of this life, enjoyed with moderation,
and under a renewed sense of the divine blessing, is all that I think we should wish for;
and when obtained, should be cause of deep, and humble,
and fervent gratitude to our Great Benefactor.

So, my dear, I have unexpectedly written you a long letter, instead of a short scrawl.
I was writing to your dear mother, and whatever was the meaning of it,
I could not enlarge as usual to her; so I turned to you,
and found greater facility and fluency.
Not that I think my letter to you is anything extraordinary, as to its value,
or that I had any extraordinary influence to write it.
But so it fell out: these things occurred, and I venture to pen them down,
in a degree of freedom of mind.
And, indeed, without such freedom,
we should be cautious of writing or speaking on the solemn subject of religion.
Our own spirits, as human creatures, may agitate other matters;
but the spirit of Christ in us, should more or less open our understandings,
and give liberty, when we meddle with the things of his kingdom.
Perhaps I may not very often again, at least for some space of time,
converse with you on this awful theme; but whether present or absent, speaking, writing,
or silent, be assured I am, with the closest feelings of paternal love,

Your truly affectionate father,

Richard Shackleton.

[.asterism]
'''

From Richard Shackleton to His Wife.

Ballitore 1st of 8th Month, 1770.

We are not to judge by outward appearances.
There may be great exactness in keeping to the letter of the discipline, and a good form,
when either the overcharge of temporal concerns, or indolence of spirit,
or permission of wrong things in their families,
may preclude the flowing forth of good to individuals;
and when several of such individuals are collected together,
sometimes darkness and heaviness will be felt, more than light and life.
I am persuaded your honest, faithful heart, loyal to your sovereign,
true to his testimony, and zealous in his cause,
is approved of by Him who knows the heart; and if you do not go a good gait at last,
I do not know what will become of some of us.

Richard Shackleton.

[.asterism]
'''

From Richard Shackleton to His Son.

Dublin, 2nd of 11th Month, 1776.

We may expect good cheer in good company, but may be disappointed.
It is our great loss, as ta people, that we so much stand looking one upon another.
"`You men of Jerusalem, why do you stand looking one upon another,
Jesus whom you seek is not here`"--is not to he met
with by looking for him after this manner.
"`If you seek him, you shall find him.`"

We profess and hold forth a spiritual, supernatural principle, as the essential,
vital part of religion; enabling us both to live, (be spiritually alive,) to know,
and to will and to do, as Christians.
The world denies this principle, so stumbles at the threshold.
It is hard, perhaps impracticable, by dint of reason,
to convince even rational men of things which are above reason, which are supernatural.
They must be convinced by supernatural means,
even by the effects of that power which they deny these effects,
to be seen and felt in the lives, conversation, and word and doctrine,
of the professors of truth, who live in, and are guided by the power of it.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Margaret.

Ballitore, 28th of 3rd Month, 1777.

My Dear Margaret,

Though I have not written immediately to you for a long time past,
as the intelligence communicated to your dear sister Deborah
seems to answer the end of writing to you both;
yet I believe you are thoroughly persuaded of the warmth of my affection for you,
and the solicitude with which I wait your approaching trial.

You are among most cordial and affectionate relations,
and have all the means of help at hand, which prudence may think necessary,
or competence can procure.
Cheer up, then, my dear child, trust in Almighty help,
be not too anxious about contingent circumstances, nor look too far before you:
live a day, an hour, a minute at a time, as well as you can, and leave the future.
Sufficient for the day is the evil thereof.
We are creatures but of a moment,
so that in husbanding and improving the smallest portions of our time,
consists our greatest wisdom.
I embrace you with sincere affection.

Your tenderly affectionate father,

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Son-In-Law.

Ballitore, 25th of 6th Month, 1777.

My Dear Samuel,

With great pleasure yesterday evening I received yours,
giving account of your dear wife being on the recovery (from a
fever.) I hope you will have to continue us like favourable reports,
till she is able to confirm them with her own hand.
I am in sentiment with you, that this trial may have been permitted for good purposes:
we may see thereby, and by numberless instances,
how uncertain is the state of human prosperity,
and how soon the fairest buildings of our imagination,
our schemes and our hopes may be dashed to pieces.
We live in a world, where, from a multitude of causes,
we may be made most wretched and miserable, and miss of a place of rest hereafter.
What need have we then to walk awfully in humble thankfulness,
when we enjoy all the necessaries and conveniences of life,
and when this life is rendered by our Almighty Benefactor not only tolerable,
but comfortable: yes, when in the infinity of his condescending goodness,
he is graciously pleased to superadd to his temporal favours,
the visitations of his Holy Spirit, to prepare us for,
and afford us an earnest of eternal salvation.
May you, my dear children, keep your vessels, your hearts, clean and empty,
waiting in abstractedness of thought and nothingness of self,
that these vessels may receive some of the blessed infusion, which will preserve you,
will strengthen you to go through the duties of this life with alacrity,
and qualify you to be of some service in the church in your day.
I have unity with you both, in your baptisms, in your dedications,
and in your resolutions that you will choose the Lord and his service,
and not the world and ks spirit, for the lot of your inheritance;
and the petition of my heart is for your growth and
establishment in the most precious truth.
Amen!

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Margaret.

Ballitore, 3rd of 8th Month, 1777.

My Dear Margaret,

I am glad once more to receive a letter from your own hand.
I wish us to be preserved thankful receivers of the many favours conferred upon us.
May we be still kept in a sense of our weakness, and wretchedness,
and insufficiency without Divine protection and assistance,
that we may look and lean to the Lord, who is omnipotent and omnipresent, and,
from one season to another, cultivate an acquaintance with him,
through the means which he has allotted for that purpose,
his spirit placed in our hearts; by the operation of which,
petitions and offerings are prepared, and ascend with favour and acceptance,
to our common Creator and Benefactor,
who is worthy of a whole burnt-offering from each of us;
even a total dedication of our all to him, from whom we have all,
and by whose special goodness and mercy we yet remain, I hope, in degree alive,
in every respect, to make mention with gratitude and reverence of his excellent name.

Richard Shackleton.

[.asterism]
'''

Elizabeth Shackleton To Her Daughter Sarah Shackleton.

Ballitore, 15th 8th Month, 1777.

Your father, Mary and I, set out for Moate, fourth day week.
Our journey was attended with some little difficulties,
but we were greatly favoured in getting safe home; and,
as our motive for going was to be found in the way of our duty, I hope it was acceptable.
The public service of the meeting seemed chiefly to rest upon that faithful servant,
Elizabeth Robinson, though most of the ministering friends who were there,
had acceptable service also.
All tended to the one thing; that is,
to promote reformation among the professors of truth,
that they might become possessors of it; which would be of more real value to us, by far,
than any or all earthly enjoyments.
So, my dear child, seek early and late for this pearl of price!
Forget not the constant, inward watchfulness unto prayer,
that you may be preserved from the many temptations that await you on this stage of life.
Beware, lest your mind, through unwatchfulness,
be too much drawn away after trifling objects.
I do not mean admiring the beauties of the creation,
which leads to adore the Power that caused them to be;
neither the improvements of sensible, useful members of civil society;
but many things that may present in variety of company, conversation,
etc. though I hope you are not in the way of such things, as many other young people are,
who are much to be pitied.
And those who are favoured with a careful education,
have cause of humble thankfulness to the Author of all our blessings,
that he was pleased to cast their lot in the way to be directed aright,
while so many of our brethren, by creation, remain in darkness;
not being directed to look to the light, to be their leader,
and the anointing to be their guide.

Elizabeth Shackleton.

[.asterism]
'''

Richard Shackleton to His Son.

Dublin, 4th of 11th Month, 1777.

It is a capital favour to have a sound mind in a sound body.
Indeed, the favours conferred on our house are very great and very numerous:
the principal is the Divine visitation,
which I wish may be embraced with due gratitude and humility by us all.
It is a holy thing, not to be trifled with,
not to be put in competition with any other thing;
not to be put off with a "`Go,`" and tarry yonder,
and "`at a convenient season I will call for you;`" but received with open heart,
and into the uppermost chambers there.
Next, health of body.
Then, kind, and tender, and dear relations and friends,
and the means of procuring every necessary of life.
Let none of these favours escape our notice,
but be the subjects of our grateful contemplation;
that so He that delights to do his creatures good, in blessing may continue to bless us,
and to protect and help us.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Margaret.

Ballitore, 18th of 7th Month, 1778.

Your account of your visit to the widow Rigg was very agreeable.
The sick room is often a profitable place.
When the favoured of Heaven are in the furnace of affliction, the Son, the Comforter,
is often sensibly among them; and where he is, it is good for us to be.

Richard Shackleton.

On the 22nd of 7th month, 1778, that respectable woman, Deborah Carleton,
died at the age of sixty-five.
The following letter gives ample testimony of her estimable character.^
footnote:[In the almost maternal Care which, as has been before remarked,
Deborah Carleton extended towards Richard and Elizabeth Shackleton`'s children,
she was aided by an excellent servant, Elizabeth Widdows,
whom she brought up from a child; who was religiously inclined, had a good understanding,
and was not without some literary taste.
She assisted her mistress in giving a bias to the minds of her interesting charge,
in favour of what was good and honourable; and was justly esteemed and beloved.]

Richard Shackleton to His Daughter Margaret.

Ballitore, 27th of 7th Month, 1778.

Our loss, to be sure, is great, in your beloved aunt, Deborah Carleton,
as she was both a sensible and sincere woman.
She was watchful over our interests, and over the interest and welfare of our children,
with an anxious, tender, affectionate solicitude; and,
as she had long experience of the world, was very capable of advising respecting it.

The children, as might be thought, mourned,
and will mourn the removal of so near and dear a friend, relation, guardian, assistant,
instructor, and companion; but the dispensation will, I trust,
be of benefit to their spirits, and time will wear off the keen edge of grief.
She died the 22nd, and we interred her remains yesterday,
after the rise of the forenoon meeting.
It was concluded best not to bring them to the meeting.
The dead was not there; but, through infinite kindness,
the living who attended were favoured with the baptizing power and presence of the Lord.
Our dear friend James Gough came from Dublin on the occasion,
and had a good time in testimony at the meeting: in testimony again and supplication,
with renewed evidence of good, at the grave.
The exemplary life and good qualities of the deceased were spoken to,
in allusion to Cornelius the centurion: "`Your prayer is heard,
and your alms are had in remembrance in the sight of God.`"
And it is the crown of our comfort,
that not only her passage out of this life was made so easy,
that at the last she seemed only to cease to breathe;
but at the solemnity of her interment,
there was felt so strong and well-grounded a hope of her
translation from a painful body to a place of rest and happiness,
which hope was borne testimony to, I think in a good degree,
of the life and authority of truth.
Our invaluable, steady, sincere friend, Elizabeth Pike,
who is so hard to be prevailed on to pay visits, or stay unnecessarily from home,
has continued with us ever since, and does not purpose to leave us till tomorrow.
I think I never knew such another, (man or woman,) for firm, steady friendship:
her company is of great use, and a consolation to your mother.
She came with intention to administer comfort to my dear sister;
but that comfort was reserved for her survivors.

I doubt not the kindness of your friends and relations in visiting you in your trouble.
Give all our dear love to them all.
I love them that love you.
Elizabeth Pike joins us in dear love to you.
May kind Providence bless and protect your little ones,
says your truly affectionate father,

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Son.

Ballitore, 13th of 2nd Month, 1779.

I hope to be at the solemnization of your marriage,
and trust that if we keep to a right preparation of heart,
the Great Master will favour us with his presence.
You sayst, and truly, that solemnity causes inward strength;
but the heart must witness a preparation for the solemnity.
This preparation of heart, this cleansing our way,
is only effected by taking heed thereto,
according to the dictates of the in-speaking word.
Keep pace with this, and in all your previous transactions do nothing contrary to this,
and I doubt not but you will be strengthened to go
through the public part which you have still to act,
in a manner suitable to the occasion.
Remember the advice which Mary gave at that honourable marriage,
to which both Jesus and his disciples were called: "`Whatever he says unto you,
do it;`" and the consequence was, that the plain, simple water-pots for purification,
were made to contain most excellent wine.
You are both very dear to me: I love you both as one.
You are the companions of my thoughts, and subjects of my prayers.
You must bear with me then, if, with parental tenderness and affection,
I earnestly recommend to you the path which leads to present and future happiness.
It is not a path in which the world walks,
for the friendship of the world is enmity with God;
but it is a path of holiness and self-denial; it is a path of lowliness and purity;
but it is a path in which is found substantial peace.
May you walk hand in hand through life in this path,
encouraging one another in every good word and work,
true helpmates in prosperity and adversity; "`looking unto Abraham your father,
and unto Sarah that bare you:`" i. e,
calling to your frequent recollection your ancestors, male and female,
from whom you are descended;
men and women devoted in all their noble faculties to the cause of truth,
which is the cause of genuine Christianity: worthies whose names are of sweet memorial,
and will very probably be transmitted, with real honour, to latest posterity.
"`Mark the perfect man, and behold the upright; for the end of that man is peace.`"
And it is the end which we should still keep in view.

Richard Shackleton.

On the day on which his son was married to Lydia Mellor,
Richard Shackleton wrote to his wife.

Dublin, 23rd of 2nd Month, 1779.

My Dear Love,

This day is over: it is near nine o`'clock.
It has been a memorable day, to be commemorated by me and mine with humble gratitude.
The meeting was solemn and favoured.
The spirit of your poor husband prostrated in reverent, humble gratitude,
and baptized in the deeps.
Surely if this connection was not of the Lord,
surely his power would not be so evidently felt in the solemnization of it.
Gratitude, my dear, gratitude has overcome my heart for this addition of favour.
We have had this evening a good, religious opportunity after tea,
in which dear James Gough was, I think, well concerned;
as he was remarkably in the public meeting, both in testimony,
before the parties took each other in marriage, and afterwards in supplication.

Lydia is really an engaging young woman.
I hope we shall have comfort in her, and that she will do her husband good, and not evil,
all the days of their living together.

Richard Shackleton.

By this marriage another branch was grafted into the stock of this family;
a branch bearing good fruit, in every sense of the word;
worthy of her descent from Margaret Fell, (Fox;) and helping to fill the vacuum,
and heal the wound, caused by the recent loss of a beloved relation, (Deborah Carleton).
On his son`'s marriage, Richard Shackleton resigned the school to him,
and retired to the house where his father had lived.

It may not be unappropriate to make a short mention here, of some of those domestics,
by whose upright conduct and fidelity Richard Shackleton`'s pious concern
for the right ordering of the family had been essentially promoted.
A young friend from the county of Wexford was servant
to Richard Shackleton and his first wife:
she was a person of much simplicity and little cultivation,
but truly wise in having "`chosen the good part,`" which was "`never taken from her.`"
She married James M`'Connaughty, who also settled in the family.
This worthy couple had no children,
but they loved those of their master with nearly
the same affection as if they had been their own;
and this love was fondly returned, and a tender respect paid to their memory,
by those whose infancy they had cherished, and whose youth they watched over for good.
James, after some years, took a mill of his master, and removed to it, obtaining,
in the country, the title of "`honest James.`"
He died in 1780, of a short illness, and his widow returned to her master`'s house,
where she survived him ten years.
They had been blest with mutual happiness in each other,
and with the protection of Him whom they loved above all.
For several years the station of housekeeper at the
school was also filled by a religious friend.

The dwelling which became the residence of Richard and Elizabeth Shackleton,
when they relinquished the important charge that had devolved upon them,
received from Richard Shackleton the name of the Retreat.
Here, loosened from the ties,
and released from the responsibility which had in
some degree limited their general sphere of action,
they became still more dedicated to the service of the society.

In 1779, Sarah Newland, a valuable friend and approved minister,
was concerned to visit the meetings of Friends throughout this island.
Richard and Elizabeth Shackleton who knew her worth, her patience, and her trials,
united in the general concurrence of her friends with her prospect.
They did more: they yielded to a like impulse,
and gave her their company and conveyance for travelling.
It was an arduous undertaking;
but in simplicity and singleness of heart they accomplished it.

In this journey, Elizabeth Shackleton`'s notes mention several friends then living,
above eighty years of age.
Among them, Joseph and Abigail Smithson, who, feeble and aged as they were,
accompanied them some miles to the next meeting; John Wright of Ballinelay,
who had built a new meetinghouse at his own expence, and gave to Friends a lease of it,
and of a piece of ground for a burial-place.
She concludes, 4th of 8th month, 1779: "`Got well to Ballitore,
with humble thankfulness in our minds for the many
favours and preservations afforded to us,
and for the blessing of peace in the discharge of this office of friendship and duty.`"

During his absence from them,
Richard Shackleton enlivened his family by his pleasant and instructive correspondence.

Richard Shackleton to His Daughter Deborah.

Dungannon, 13th of 5th Month, 1779.

My dear child, I am going about espousing the concern and engagement of another,
for the propagation of true religion,
and sometimes feeling some degree of engagement in my own mind for the same.
You may, therefore,
expect that my letters should contain and convey some religious matter and tincture.
But I seldom find any opportunities, of a religious kind,
more deeply and solidly beneficial to my spirit,
than those which I meet with in my seasons of private retirement at home.
To this assiduous, diligent waiting for, and seeking after,
the resurrection of a divine life, inwardly stirring in their own minds, I,
above all things, recommend my dear children, as the surest way to be preserved,
as well as to grow and thrive in religious experience.

Richard Shackleton.

[.asterism]
'''

From the Same to the Same.

Lisburn, 18th of 5th Month, 1779.

There is a number of young people up and down, hopeful and promising,
who do not prefer the tinsel vanities of this world,
to the substantial comforts of Divine favour.
They are not compatible together: the idol which the uncircumcised nature worships,
cannot stand where the ark of the testimony dwells.
We must choose which we would serve; and on making a right choice,
and persevering therein, depends our everlasting happiness.
Oh! my children, be wise, and make glad the hearts of your tender,
affectionate father and mother, who watch over you, with solicitous care, for your good.
Be humble and be meek, that you may be taught of the ways of the Lord,
and your understanding guided in sound judgment.
So will you be as happy as the condition of mortal man can be;
in yourselves feeling renewedly the evidence, assurance,
and earnest of a blessed immortality,
and you will come up successors in the maintenance of the noblest cause which ever was,
or ever will be upon earth.
No honour equal to that of being the servants of Christ;
no wages of such high value as he liberally bestows.
The time hastens, with unremitting speed, which will decide on each of us.
The past is irrevocable, the future uncertain; therefore, Now is the acceptable time,
and Now is the opportunity which should be laid hold on,
and diligently improved by us all, and each of us.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Mary.

Ballitore, 29th of 8th Month, 1779.

Paul Kerma`'s family have been in a fever.
The mother recovered; the father`'s state still doubtful; the son, their only child,
the prop and comfort of the family, a fine, hopeful youth, has just now expired.
Surely this is a vale of tears.
We had need take care of health while we enjoy it:
we ought to be exceedingly thankful for it, as well as for the tranquillity,
public and domestic, and those necessaries and conveniences of life which we still enjoy.

Soon after the date of the above,
the daughter to whom it was addressed was seized with a fever in Dublin,
at the house of the kind family friends, Joseph and Elizabeth Pike,
where she experienced such kindness as claimed and excited strong emotions of gratitude.
Her mother and sister came to her, and attended her through a dangerous illness.
Her anxious father on this occasion thus expresses himself.

Richard Shackleton to His Daughter Deborah.

Ballitore, 16th of 9th Month, 1779.

Your letter, my dear Debby, be sure alarmed us yesterday,
though couched in the most moderate terms.
We hardly know sometimes how dear persons and things are to us,
till we are in danger of losing them.
I know, and at times feel the instability and uncertainty of visible enjoyments.
I am sensible that we have not long to stay together on this earth.
Our conflicts and troubles here will soon be over; and if,
through the mercy of Divine Providence, we be preserved from evil while here,
our souls will be centered in rest and peace hereafter.
It therefore becomes us all to seek after resignation,
and submission to that high and holy hand, which does all things well.
Perhaps, by this dispensation of affliction and pain,
he means to reduce the creaturely part in our dear child; to purify her spirit,
and prepare it to offer those sacrifices without blemish,
with which he is always well pleased:
sacrifices not kindled by the fire of her own lively imagination,
nor offered upon an altar raised by any artificial tool; but those spiritual hymns,
and songs, and melody, which are of divine origin, and still tend towards their original,
ascending and descending, like Jacob`'s ladder,
which had communication between earth and heaven.

In the tenderest manner whisper in my dear child`'s ear, that I love her very dearly,
and hope in due time to embrace her in my fond arms;--that the neighbours, and friends,
and relations here are very inquisitive about her;-- and
that her speedy recovery is the subject of our earnest desires.
It seems unnecessary for me to say further, while her tender and excellent mother is near.
I need not bid you do all in your power to keep up your mother`'s spirits;
but I charge you, endeavour to support your own.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Wife.

Ballitore, 9th Month, 1779.

I am thankful that through all, and through all my own many infirmities,
I have a place in the hearts of the generality of my friends;
having been preserved from retaliating evil for evil,
but still endeavouring to overcome evil with good.
And I am thankful that, as to natural things, the little meal in the barrel,
and the little oil in the cruise has not, through the favour of our great Benefactor,
yet failed; nor is the spring of humble, and I trust, holy gratitude dried up in me,
for the capital favour of such a wife and such children as I am blessed with; but,
on the contrary, I may figuratively say,
rivers of grateful tears run down my eyes for the same.
If our dear Mary be restored to us, it will be a particular additional favour.

Remember me, in the most affectionate and grateful manner, to Joseph and Elizabeth Pike,
whose house we trouble, not only as an inn but a hospital.
I can do little in return for such manifold favours;
but I have prayed that retribution may be made them for their kindness,
by Him who has all power to bless.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Son.

Ballitore, 1779.

I rejoice, and partake,
and join in the harmony which you mention to subsist in our family.
Each of us has the high fit, the low fit, and the cross fit;
and if there be not mutual forbearance and condescension, we shall lose peace on earth.
In music there are not only different chords and strings, but stops and pauses.
Let us seek to be ordered and modulated by the soul of harmony, Divine love;
and if we cannot go forward in service,
and find our own minds not under present qualification to help others,
let us stand still till we renewedly feel and know that good is present with us.
Thus minding our stops and movings, the locking and unlocking of the key,
which opens and none can shut, and shuts and none can open,
we shall walk wisely and usefully in our several lots in life.

Richard Shackleton.

Elizabeth Shackleton to His Wife.

Ballitore, 26th of 9th Month, 1779.

If you and dear Mary were at home, I think we should all be very comfortable together,
now our Debby is returned.
I do not speak at random when I thus speak.
I know wherein true comfort consists, and I know what an uncertain world we live in.
I trust our dear Mary will have learned also, by the things which she has suffered,
what is the greatest good--the good part;
and that she will be enabled to dedicate her all, to consecrate every faculty,
and devote the whole body of her affections,
to Him who has been bountiful and gracious to her.
Her duty, respect, and love, reflected back from Him,
to those who have a right to claim them here,
will then come with sweetest influence and acceptance.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Margaret.

Ballitore, 29th of 12th Month, 1779.

I have just received account of the death of my dearly beloved friend, Jane Watson,
of Rathrush, who departed this life in great quietude, without sigh or groan,
yesterday about noon.
She was my very dear friend.
I feel for her loss,
but the situation of her health made her stay hardly desirable on her own account.
Killconner is now "`emphatically poor.`"
Sally is poorly in health--has hurt her constitution, I believe, by her dutiful,
affectionate, tender, assiduous care of her excellent mother, for so long a time.

Richard Shackleton.

From the Same to the Same.

Ballitore, 26th of 2nd Month, 1780.

My Dear Margaret,

I received yours of the 18th, at my return from the quarterly meeting of Mountmellick.
That meeting was large, and I think, as to instrumental help, favoured.
James Gough and Mary Ridgway had, in my apprehension, good times.
What a wonderful blessing to the church is a living ministry! and how precious a thing
and admirable it is for a human creature to be qualified to speak in the name of the
Lord! and for human nature to be influenced by a supernatural power!
The frequency of such appearances among us, like those of the sun, moon, and stars,
and the process of vegetation, by the familiarity, takes off from the astonishment;
but still, great and marvellous are the works of the Almighty.

Richard Shackleton.

After spending eight years in Ballitore, in improving and pleasing society,
the comforts of which were increased by the placidity and cheerfulness of his own temper,
Samuel Carleton died, of a slow, but not very painful illness,
in great love and sweetness of mind;
thankful that he had been so long favoured with health,
and not repining at the loss of it.

Richard Shackleton to His Son.

Waterford, 20th of 3rd Month, 1780.

It is well to be useful members of civil society,
and to endeavour to provide well for our families,
in whose society we enjoy many comforts;
but the subordination of things is greatly lacking among many:
primary considerations rank only as secondary, and secondary usurp the place of primary.
The Hp of truth has settled the order, which man has reversed in his conduct.
Christ says, "`seek first the kingdom;`" and assures,
that necessary appurtenances and appendages shall be added.
May you, my beloved children, united as you are in flesh, being united in a right spirit,
seek first, principally, most earnestly, the favour of heaven,
that you may happily be objects of divine notice and help.
Solid, and arduous, and complicated are your duties and engagements;
and you never can fulfill them acceptably to God and man,
without the Lord`'s blessed mediation, guidance, and protection.
I often desire it for you, in humble prostration,
and trust that in like manner you seek it for yourselves.
As you allow the leaven of holiness and pure and undefiled religion,
to operate upon and leaven your minds, you will infallibly do well.

Should you unhappily forget what hand it is that feeds and supports you,
and depend on your own sufficiency for preservation and prosperity, you are gone,
my beloved children, and the joy of your father is gone with you: therefore, be humble,
be watchful,
be diligent in renewedly seeking and feeling after the evidence
of divine favour and approbation upon your spirits,
every day and every night, as you pass along, and as each day and night revolves;
that so God Almighty may bless you, instruct and assist you to live to his honour,
and to the honour of the great and high profession which we make among men.
So be it.

Richard Shackleton.

In 1780, Richard Shackleton was again at the yearly meeting of London;
and from that time to the end of his life, constantly attended that solemnity,
with the exception of the year 1786, when he set his son at liberty to go there.
Richard Shackleton had made several valuable acquaintances,
when he was in England in 1776, some of whom were young in years,
with whom he maintained a correspondence.
His friends and he rejoiced to meet: he was much comforted in their company.
The hospitable house of J. E. was open to him and most of the friends from Ireland,
who experienced great kindness from that meek-spirited, excellent friend,
and his worthy wife and family.
When he went to York, the vacuum left by the death of his uncle,
seemed filled by the brotherly attentions of William Tuke, who,
with his excellent wife and children, received him with true affection.
On his way to, and sometimes from London,
his visits to Abiah Darby combined a variety of comforts:
his cheerful and improving society was duly appreciated
by those whose natural tastes and acquirements were similar;
but far nearer were their spirits united, by the sweet influence of perfect goodness,
which drew them to mingle together in rejoicing and in suffering.
The venerable mother, her daughters, Mary, Sarah, and Deborah, (the devoted Deborah,
a mother in Israel,) are all names dear to those who knew them;
and here the repose of age, and the activity of youth,
united to promote the love of the Creator, and the happiness of his creatures.

In this year his daughter Deborah accompanied him,
previously to her marriage with Thomas Chandlee, of Athy,
a small town six miles from Ballitore.

Elizabeth Shackleton To Her Husband.

Ballitore, 12th of 5th Month, 1780.

I observe your excellent remarks concerning the kind protection of Him,
who has been with us through life, and the good cause we have to trust in his mercy,
who knows our hearts; and how sensible we are of our own inability to provide for,
or preserve ourselves.
And I hope our dear children will reap the advantage of the tender
and unremitting concern of their affectionate father.
If they do not, they must certainly have more to answer for than poor,
neglected children, many of whom are to be met with, even in our own society;
and I wish the parents of such might consider the great trust reposed in them,
lest the burden of their negligence should be insupportable at last.

Elizabeth Shackleton.

[.asterism]
'''

Richard Shackleton to His Wife.

Butler`'s Court, near Beaconsfield, 25th of 5th Month, 1780.

The yearly meeting being over, I went to see Edmund Burke.
Having given him notice of the hour of my intended visit,
he had come from the House of Commons, and was ready, with his family, to receive me.
The friendship, the freedom, the cordiality with which he and his embraced me,
was rather more than might be expected from long love.
I could not well avoid coming with him to this place, which is most beautiful,
on a very large scale: the house, furniture, ornaments, conveniences,
all in a grand style.
Six hundred acres of land, woods, pleasure-grounds, gardens, green-house, etc.
For my part, I stand astonished at the man and at his place of abode:
a striking parallel may be drawn between them; they are sublime and beautiful indeed.

I awoke early this morning, as usual, and was glad to find no condemnation; but,
on the contrary, ability to put up fervent petitions, with much tenderness,
on behalf of this luminary.

Dr. Fothergill moved, to my great satisfaction, to have the yearly meeting stationary,
and not regulated by the anniversary of a moveable feast.^
footnote:[The time called Whitsuntide.]
It is to be taken into consideration at the next sitting of that great and solemn assembly.

Richard Shackleton.

[.asterism]
'''

From the Same to the Same.

Bristol, 10th of 6th Month, 1780.

There are dreadful accounts coming here daily from London,
of an insurrection of many thousands of the populace; putting down Romish chapels,
and breaking open prisons, and doing great damage to the persons, houses,
and furniture of individuals, nobility, gentry, etc.
Our friend, Edmund Burke, most happily (by the interposition, I trust,
of Divine Providence) escaped out of their hands,
for I suppose they had him a while in their power.
He pleaded his own cause with the mad multitude;
and the Controller of all things so overruled their wicked, desperate, furious spirits,
that they let him go unhurt.

Richard Shackleton.

[.asterism]
'''

From the Same to the Same.

Clonmel, 4th of 9th Month, 1780.

I venerate the name and character of an ambassador of Christ;
and I also am disposed to think favourably of those whom, after long experience,
I have deemed valuable friends: therefore, feeling little or nothing any way,
I stand as it were neuter in my judgment,
and find it best for me not even to give a liberty to thought,
nor to meddle in other folk`'s matters.
Our high and holy profession is a great house, built not for man, nor by man,
but for God;
and supernatural wisdom must qualify for servants and officers in this house,
or it will be dishonoured, and the Master be displeased.
Too much backwardness, and too much officiousness, are equally offensive.
My desire is, my dear love, for us and for ours,
whom I have many times found ability to dedicate to the service of this house,
that the great Master of the family would instruct us to
perform our several duties acceptably before him,
if he should honour us with any of his commands; and if not,
that he would be graciously pleased to preserve us from evil,
walking in lowliness and simplicity, yet acceptably before him.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Sarah.

Clonmel, 7th of 9th Month, 1780.

It would not be grateful, in every sense of the word, to force Mary away with us:
you must learn resignation and patience.
I hope it will not be long before you meet with joy;
that joy and placid serenity which can only be had under the canopy of conscious innocence.
The contrary beclouds the mind,
and prevents any satisfaction arising from the most pleasing, natural gratifications.
Conscious guilt gives every object, how agreeable soever in itself, a gloomy, sable hue:
it damps, it depresses, it debases.
By the mercy of our great and common benefactor,
I hope and believe all my dear children are preserved, in a good measure,
from any great mixture of this alloy.
May the holy leaven have room to continue so to operate,
that the whole lump may be sanctified; then the joy will be full.

This place is very agreeable; rendered still more so by the little prattling babes,
among whom I stalk about, like a sort of patriarch,
while they call me "`granddaddy,`" and present me with their little offerings.
Yet still home, and the dearest of all earthly objects attracts me home.
I hope your mother is satisfied with my stay,
and that you all exert yourselves to make her comfortable,
and my absence tolerable to her.
She deserves every mark of duty, affection, respect, and attention from you.
She also needs your assistance, and the defects of memory and recollection,
and depredations of time, to be supplied and made up by your more youthful activity.
The good dispositions of my children are the joy of my heart,
and weigh it down with humble gratitude.
The prospect which opens for my dear Debby is indeed
highly pleasing and comfortable to me,
as I have a peculiar regard for the young man,
whom she has no cause to be ashamed to tell the people she designs to marry.
It is also my long settled belief, that,
if kind Providence grants this my dear child health, she will be a very loving,
valuable wife--a help-mate in every respect, both civil and religious.
So that Thomas Chandlee will I hope be happy, as I really think he deserves to be,
in domestic life.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Deborah.

Clonmel, 8th of 9th Month, 1780.

I am pleased you have got one step towards your solemn engagement, I hope, well over.
The benediction of our good old friend Robert Leckey was grateful to me also,
as well as to you.
I hope you will often, both severally and unitedly,
seek for the immediate descending of that blessing
which makes truly rich and adds no sorrow with it.
The riches of this world, accumulated even by honest industry,
without having the great Disposer of all things in view,
and acting about the affairs of this life in His holy fear,
are often the means of inexpressible perplexity and disquiet,
sometimes of the most dreadful evils.
Whereas a looking, a leaning, a humble dependance on Him that feeds the ravens,
and in the concatenation of the events ordered by his Providence,
caused the same ravens to feed his prophet,
is the way to procure the divine blessing to be superadded,
and prevents that sorrow which works death to the innocent, happy, composed life.
But though I thus indulge a freedom of writing, I think I well know both your hearts,
and that they are in that place where treasures of
a far more noble kind than any this world can afford,
are laid up for the poor in spirit, the simple and honest-hearted,
and those who think little of themselves, can say little for themselves,
yet are diligent in waitings for ability to walk in that way which leads to life everlasting.
We have, each of us, our foibles as men and women,
and have each of us occasion to be industrious in watching unto prayer;
that the droppings and distillings of good may fall upon our branches;
strengthening and fructifying the holy plant, and destroying,
by its sacred virtue and influence, or at least correcting, those frailties of the flesh,
which, like messengers of Satan,
are at times sent to buffet even those who are well-minded,
and in a good degree partakers of Divine regard and notice.

If we neglect a proper care of our bodies, disorders will hurt them;
if we omit to seek for spiritual nourishment, our souls will be in danger of perishing;
and if we exercise not our reason, to cultivate and improve our natural understandings,
to form us and our manners so as to be pleasing and profitable members of society,
our spirits may, in our progress through life, contract dispositions,
which in course of time may be inveterate and hard to be removed;
dispositions which will much disqualify us for filling
our several departments in life with propriety,
and with ease and satisfaction to ourselves and others.
I write freely to you, my dear child, because I love you;
because Divine Providence has favoured you with a good understanding,
both natural and spiritual; and because you are now going to leave your father`'s house,
and to be the companion of a worthy, a sensible, and a religious man:
therefore I would not be lacking on my part to do everything in my power,
in every respect, for your happy and comfortable settlement;
and having done my duty to the best of my poor abilities,
leave the rest to our Almighty benefactor, whom I pray to bless you together,
with every spiritual and temporal blessing,
which his unerring wisdom sees best to indue you with.

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Son.

Clonmel, 11th of 9th Month, 1780.

My Dear Abraham,

Your letter of 6th was and is indeed very grateful to me:
it is such incense as (through the abundant mercy of our common gracious
Benefactor) I was favoured with ability to offer to my father,
and such as, through the continuation of the same mercy,
I trust you will know the pleasure of receiving from your own offspring.
It is remarkable how in the moral world,
the crime of irreverence to parents is punished in its own kind,
and the iniquity of the parents, in this line, visited on the children,
from generation to generation.
In all sins the crime begets its own punishment; but in this,
the crime begets the punishment in its own likeness.
By the unmerited kindness of Divine Providence I have experienced
the contrary causes producing the contrary effects,
in a similar manner.

You will hear with pleasure from me a confirmation
of your sister Margaret`'s happiness here.
When I say happiness, I do not mean it in the vague,
superficial sense in which I frequently observe that term employed.
I think her happy, because I think her good.
And yet both these epithets are to be taken and used with a comparative limitation,
and reference to human condition.
She does us much honour, however, in this place,
by her conduct as a member of civil and religious society:
she is nursing a beautiful babe: she has reared two other fine children;
and she is a true helpmate, in every sense, to a very worthy, honest, active man,
who is an affectionate husband, a good father, and prosperous in business.
I trust in the munificence of Heaven,
which is graciously pleased to shower down its favours upon us who are unworthy of them,
that we shall have the like grateful acknowledgments to make respecting our dear Debby:
indeed, the sense of my obligations to our Almighty Benefactor,
on account of my dear children, often humbles my heart, and weighs me down,
as fruit-bearing branches, over-loaded, bend towards the parent earth,
which supplies the nourishment to the tree.

Though Lydia and I have not corresponded this time,
yet I trust we are as epistles written in each other`'s hearts.
I am, my dear Abraham`'s affectionate father,

Richard Shackleton.

[.asterism]
'''

Richard Shackleton to His Daughter Margaret

Ballitore, 1st of 12th Month, 1780.

We took our final leave of our dear friend Robert Leckey, the 19th. He died the 22nd ult.
We had a favoured season with him,
in which Sarah Newland ministered to him in a sweet and lively manner.
I believe his spirit is happily at rest, after a long life of integrity, humility,
fidelity to the testimony, benevolence, and humanity.
His funeral was very large.

Richard Shackleton.
