== Chapter VI.

[.chapter-synopsis]
* Letters
* The illness and decease of Richard Shackleton
* Death of Elizabeth Shackleton

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 21st of 1st Month, 1789.

My mind is often humbled in deep thankfulness, on account of several of you,
my beloved children, who are not only preserved to walk in the truth,
but called to bear testimony to it; and my earnest and affectionate desire is,
that you may be faithful and obedient to the clear manifestations of duty,
and of the divine requirings.
This is what will render you comfortable and happy in yourselves,
and be as a Goshen to you in the midst of Egyptian darkness: you will have light,
cheering light, in your dwellings.
But the contrary has a contrary effect: instead of the conscious answer of "`well done,
good and faithful servant,`" there will be a fearful looking for of judgment,
divine favour will be withdrawn, and the spirit left solitary in a dry pit: no,
even the lawful gratifications of this life will lose their relish,
the cup will be embittered;
and the cross occurrences which fall out will cut with a keener edge,
and the hurts and wounds made by them will be in danger of rankling and festering,
instead of being presently healed.
So may we all be mercifully preserved a family, a field, which the Lord has blessed,
and will graciously delight to bless.
A little time, and all will be over with us here:
eternity and its prospects should be the object of our contemplation,
and have all their due weight and influence with us.
I sent your message of love to our friend Elizabeth Pike.
That wise lady`'s answer was: "`We accept your daughter Grubb`'s love:
she seems as a piece of myself.`"
Is not this multum in parvo?
+++[+++i.e. much in little].

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
Waterford, 19th of 5th Month, 1789.

It is thirty-five years, this day,
since a former beloved companion was translated from earth to heaven.
The loss was grievous, and the outward prospect melancholy;
but the great Controller of events, in the plenitude of his goodness,
was pleased to make up that loss to me and mine,
and to brighten that gloomy aspect of things, by adding Hue, his precious gift,
to my family.
In you we have found a wife, a mother, a daughter, a superintendent, a counsellor,
helper, and friend; and I trust we are all thankfully sensible of the favour.
I do seem at times as if home was not to be my constant place of residence,
and as if the comforts of domestic life were folded up; so that I apprehend, at times,
it is best for me to leave home,
and be in the way of witnessing that some religious service goes forward.
On these occasions I have ever found you willing to encourage, release, expedite,
and accommodate me to the best of your power, which I gratefully acknowledge.

Your children will, I doubt not, care for you now in the decline of life;
and I trust Almighty help and favour will be near for your comfort and support.
Remember me affectionately to our dear Sarah.
A petition was begot in my heart for her this day in meeting,
that she may be preserved in the training of Infinite Wisdom,
and grow to be useful in the church of Christ,
according to the extent of the designation of her gracious Master, whose she is,
and whom I believe she serves acceptably.
If she finds in her heart to write me a line, it will, doubtless, be acceptable;
but I would not have her be uneasy if she does not,
for I shall not be uneasy on that account.
I wish her never to give to others that which is only for herself,
nor to keep unprofitably and detrimentally to herself,
what may be given to her for others.
If it will be any encouragement or satisfaction to her,
I can freely say I have near unity with her sweet effusions,
and her deportment and conduct preaches loudly (I wish I could say effectually) to me.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Hubberston, 23rd of 6th Month, 1789.

Now, my beloved companion and dearest friend, for your satisfaction I may inform you,
that I have been quite satisfied in my mind with this excursion,
which I have ventured to take, not rashly,
but as seekingly and as feelingly as I well could;
and I hope Divine Mercy has cleared the way for it,
and will be near to preserve and support every way.

Along with innumerable favours heaped on my unworthy head, I am, I trust,
thoroughly sensible of my own manifold weaknesses and insufficiency; and this sense,
renewed and confirmed to me from time to time, is cause of deep thankfulness to me;
for I love the low and tender and helpless state, in myself and others.
This is what the eye of Messed regard is graciously towards;
this is the field which the Lord has blessed and will bless.
While I write thus, you and our beloved S. are particularly in my thoughts,
and I crave the help of your spirits, and your intercession on my behalf.
I hope our beloved child is in sound health of body and mind; that she goes on,
in public and private life, in simplicity and godly sincerity.

The believer, the true believer,
whose hope and confidence is in the fresh supplies of everlasting strength,
makes not haste, but patiently waits for the former and the latter rain:
the former to fructify, and bring to maturity the heavenly harvest;
the latter to replenish and reward the fruitful soil, and prepare for another crop.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 27th of 6th Month, 1789.

I am glad your honest Samuel was so well pleased with his excursion,
+++[+++the Yearly Meeting in London.]
He seemed to enjoy it.
You mention his apparent increase of flesh,
I trust he has also witnessed an increase of spirit in the course of his tour,
by the opportunities of instruction and observation which he has had.
We sometimes grow, I believe, and do not know that we grow; as we may decline,
and not be immediately sensible of it.
So it is said of Samson: "`He wist not that the Lord was departed from him.`"
Your husband is possessed of that humility, simplicity, and integrity,
which will not fail of making way for him;
and as he diligently cultivates a renewal of inward strength, by frequent retirement,
I doubt not his becoming, in time, a father in the church,
as he is much a father in his own family.
I am pleased to find he got well home.
His brother Robert and his suite getting home the same day, made it,
as cousin Sarah said, like running a race.
I wish you all to run legitimately, without emulation or justling,
and all to receive the prize.

This Clonmel is a wonderful place: it is an awful thing to live in it.
There is such an assemblage of choice spirits,
and such a necessity of each one being a good example to the others,
lest any should improperly indulge themselves in another person`'s liberty.
But, if it were even Paradise itself, so long as it is on earth,
Satan will contrive to get into it, and, if possible, will defeat, deform, and defile;,
so let us watch and be sober,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 22nd of 8th Month, 1789.

[.salutation]
My Dear Cousin,

I have been writing to some great folk, and dispatched my yearly epistle to your mother.
I now turn to one of the little ones,
whom I am glad to be enabled to salute with renewed affection, and to whom I would,
with all willingness, hand more than a cup of cold water, in the name of a disciple,
if I had it to give.
We are, very emphatically, called Friends; and friends we should be to one another,
not sparing friendly advice and reproof, and taking a willing oversight of one another,
as keepers of one another, and so profitably conjoined in harmonious labour.
If then we should not withhold reproof and correction in proper season,
why should we withhold encouragement, and the expression of strengthening unity?
If I have anything to write to you at this time, my dear friend,
it is in this line--the line of encouragement to hold on your way.
Continue in the littleness of self,
and you will continue to witness an enlargedness in the service of your great Master.
And be not weary of well-doing: consider whose cause it is which you are engaged in,
of infinite importance and consequence;
and how much depends on every one who is sent on any expedition,
or who has any part to maintain, faithfully and firmly discharging their duty.
To give way in a little is to weaken in the general; but every one doing his own part,
the whole is strengthened, and the work completely and uniformly carried on.

We have recent intelligence of the sudden decease of our dear friend, William Rathbone,
of Liverpool.
He is a loss in number and in weight, of the living members of the church.
I believe he was an honest, faithful, diligent, sensible, useful friend,
and leaves a considerable chasm in that quarter.
Our dear friends, Martha Roth and Company are, it is likely,
rolling now on the vast ocean.
Though the winds roar, and the billows toss, yet may their devoted minds be kept calm,
in sweet, serene composure.

Farewell, my beloved friend; may you take deeper and deeper root in humility,
and in the experience of the divine life, for your own preservation and nourishment,
the more you advance in religious stature, and spread wide your fruit-bearing branches.
Remember me affectionately to your honest husband.
I am glad that you are joined to one who will encourage, make way for,
and help you in every respect.
The whole plantation at Suir Island, trees, saplings, and underwood,
have all my warm wishes for their growth and prosperity.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 16th of 12th Month, 1789.

When we prescribe for such as you are, we must also take in the mind,
which often affects, and is affected by the organs of the body.
Be an obedient child.
Now a child does not reason a great deal,
nor puzzle itself with the consideration of probable consequences;
its duty and its praise are, simply to do as it is bid.
This is acceptable to the great Father of the family in heaven and on earth;
this is uniting in the chorus, in the blessed harmony; this is not interrupting,
confusing, or retarding the great work of "`glory to God,
and good-will to men,`" but it is promoting and forwarding it,
according to the Divine will.
"`The stars in their courses fought against Sisera;`"
and of whatever degree in the heavenly host,
my beloved friend, you may esteem yourself to be,
(and I am sure I care not how little that is in your own eyes,) be encouraged
to persevere in unreserved dedication of all to the cause of Christ.
The kingdoms of this world seem in an unusual ferment;
and the bottom on which the false religions of it are founded, is altogether slight,
precarious, and uncertain.
Who knows how near the hour may be,
when it shall please the Omnipotent to rend the veil
which obscures the spiritual sight of mankind,
and to reveal himself to the human species in a more general way?
saying, as at the beginning of the creation, "`Let there be light, and there was light.`"
May you, who are called and chosen, and furnished for the Master`'s service,
be disencumbered, and ready willingly to run on his errands, with an "`Here am I,
send me;`" diligently attending to the fresh pointings and directions of wisdom,
in the course of your service.
So will the great and glorious work be likely to prosper in your hands,
and your peace will run down as a river in the present life,
bearing and supporting your spirits till you are conveyed
to the ocean and fulness of everlasting peace and joy

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 5th of 2nd Month, 1790.

We are mercifully favoured here with pretty good health, except our sweet,
dear little Peggy, who does not yet rub through her complaints;
but as diligent means are used for her restoration,
we cherish a hope it may prove consistent with the Divine will to bless the same.
However that may be, submission and resignation are our duties.
Much severer trials may yet await us,
than the translation of the spirit of an innocent child,
from a scene of conflict and danger, to everlasting safety and happiness.

I think you are quite right in paying all proper attention
to the facilitating your husband`'s leaving home,
and getting the benefit of solemn feasts as well as yourself.
Those who are often much hampered with worldly cares
are necessarily covered with the dust of them.
They need to be often shaken from this dust,
that it may not lie so long as to sully their garments.
Turning the back to the world for a season, and giving up to those solemnities,
I believe, are often attended with beneficial consequences.
The women dwell more ex-officio in the quiet habitation,
are less exposed to the spots of the world.
I am glad to be well assured that your husband and you earnestly
seek each other`'s improvement in the best things,
and are as desirous each for the opportunity of the other`'s spiritual advantage,
as his or her own.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 11th of 2nd Month, 1790.

[.salutation]
My Dear Cousin,

Your last written communications to me, dated the 1st day of this year,
were very acceptable.
The extracts of letters received from France, and from our dear friend Rebecca Jones,
were a highly-pleasing treat;
and all this furnished at a time when you were wading in the deeps,
engaged with sore conflict of mind, and wrestling for a mixture of condescending mercy.
To think of fitting out an entertainment for me in such circumstances,
was an argument of true friendship and true humility;
and your increase in these two respects, is a particular object of my desire for you,
both for my sake and your own.
Well, dear friend, you were helped over that mountain also,
the visit to Kinsale and the prison there.
I congratulate you thereupon, and expect you will be still further instructed,
disciplined, and modelled, by these further sufferings and rejoicings;
so that you will become more and more an obedient child, ready at a beck to run,
and do the will of your Father who is in heaven.
I was, and am also glad at heart,
that our beloved E. P. is so completely reduced and moulded--so willing to be anything,
as well as nothing.
Well, it is certainly the most spiritually-politic way:
it saves the poor creature a great deal of trouble, to give up at once;
not to be trifling and tampering about articles of capitulation,
but surrender at the discretion of the conqueror.
Salute that dear child, for my wife and me, with much affectionate nearness.
I wrote to her in answer to her last.
If she has any good news to tell me, I care not how soon she communicates it;
if the contrary, I have a heart willing to share in her troubles.

How closely are even the favoured of Heaven sometimes tried,
about the means of providing outward necessaries! that their diligence in worldly
business and their fervency of spirit may be stimulated at the same time;
that they may be stirred up to exercise an assiduous, prudent care in their occupations,
and yet be taught that the fruit of their labour depends
altogether on Him who alone can give the increase.
There is a need of more fathers and mothers among us;
such as seek not the sordid gain of preeminence; but who,
though men in religious understanding, are children, as to a humble, happy,
tractable disposition of mind: such as are meek, compassionate, benevolent, forgiving,
preferring others before themselves; or, in a word, such as have put on Christ,
and keep on them that blessed clothing.
I hear with much satisfaction, one good report or other of some of you thereaway.
I wish the babes and sucklings may be strengthened to do their part;
for a great deal depends on that class thriving, and doing their duty.
To be mercifully preserved from material injury, in passing through the child`'s state,
affords good hopes of arriving at the measure of stature and capacity,
designed by Infinite Wisdom.
I like the last communications from France which you sent me.
When you hear from that visited, agitated country,
I doubt not you will be kind enough to communicate.

Desiring your continued increase in good, and expecting to be favoured with a visible,
manual token of your remembrance, when a favourable coincidence shall fall out,
with dear love to you and cousin Robert,

[.signed-section-closing]
I remain your very affectionate kinsman,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to John Thorp.

[.signed-section-context-open]
Ballitore, 14th of 3rd Month, 1790.

It is not a time for servants who have been trained in a holy discipline,
fitted and prepared by various previous dispensations,
instructed to know the Master`'s will, and practised in the performance of it:
it is not a time for such to be as idle, indifferent spectators, serving themselves,
and neglecting the Master`'s business.
The cause which the Son of God introduced upon earth,
which he promulgated by his own authority, confirmed by miracles,
and sealed by his blood; a cause which involves in it life and immortality,
and everything that is truly good in time and in eternity;
this is certainly to be faithfully espoused, and diligently promoted among men,
according to the ability imparted.
So thought our predecessors, and left behind them a most striking example of diligence,
fortitude, perseverance, and patience in grievous and long-continued sufferings.
They knew that the term of this life was short,
and that what they had in commission to the people
of that generation was of infinite importance;
so that they lost no time in delivering their Lord`'s message,
and forwarding his business with care, fidelity, and dispatch.
"`Go and do likewise.`"

I gratefully accept the salutation of my honoured friend, Sarah Taylor,
and I also accept her excuse for not writing to me.
She has done what she could, (I believe,) through a long life,
in a far more noble and useful line;
and I would not begrudge her now to sit down and
eat the fruits of her industry--to tarry at home,
and divide, among her friends and neighbours,
the precious spoil won by her honest services.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Sarah.

[.signed-section-context-open]
Ballimurry, 14th of 4th Month, 1790.

I cannot say when I shall get home.
I mean to do all about staying and going, as well as I can;
and I have a hope that a way will be cast up for poor, blind me, that will be best.
I have been hitherto mercifully and graciously helped; and therefore,
if I be preserved from evil,
I trust the same kind hand will continue to support and direct.
It is my principal dependance.
I have little or no confidence in the flesh, in my own talents, abilities, or contrivance.

My poor families with you are the subject of my deep travail,
with earnest desires for your help,
and for the interference and blessing of Heaven among, and upon you;
particularly and especially your dear mother is the object of my faithful,
affectionate solicitude, who so generously and freely gives me up,
and takes care for me at home and abroad.
So may we be united and bound up together all in the spiritual relation,
mercifully taken and kept under the notice, and forming,
and direction of the heavenly hand,
all children of the same everlasting Father and Friend.
And may you, my dear Sarah, continue to be an example to us all in watchfulness,
innocence, simplicity, and dedication.
Look not too far before you;
take not into your view and contemplation too great a field of labour at a time,
which may intimidate and discourage you; but whatever little matter you find to do,
do it in the present might.
As was said to Moses, "`I Am has sent you.`"
Then retire to your own closet, and hearken to the secret intimations whispered there,
endeavouring to shut out all the redundance of reasoning and imagination,
which will be apt to intrude and mix there;
remembering that that which is born of the flesh is only flesh,
and profits nothing there;
flesh and blood not being capable of entering into the spiritual kingdom.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
London, 2nd of 6th Month, 1790.

Did I mention that this yearly meeting ordered a commodious place to be purchased,
and edifices to be erected here,
for the more convenient reception and holding of the yearly men`'s and women`'s meeting?
for which purpose they directed ten thousand pounds to be raised.
Though this was only an external matter,
yet it was carried through the meeting with such unanimity, dignity,
and nobility of spirit, that all within me was prostrated in thankfulness,
as at the footstool of the throne as when the outward temple was to be built,
and the people offered so willingly.
I more and more find this yearly meeting lie close to my heart.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.centered]
On her setting out on her second visit to the continent.

[.signed-section-context-open]
London, 5th of 6th Month, 1790.

[.salutation]
My Dear Cousin,

I+++.+++ P. informing me that it was necessary to send the enclosed letter under a cover,
I thought I might as well write a few lines on the cover, as send it empty away.
I therefore take the opportunity of saluting you with my best love,
and intimating to you the continued increase of near affection for you.
I believe that the more any are devoted and dedicated
to the promotion of the Christian cause,
and the more diligently they labour therein, that they feel in a stronger degree,
not only the effectual help of the Great Master to their spirits,
but the help of the spirits of their friends, brethren, and sisters.
And as you have set such an example of unreserved submission to the divine will,
and obedience to the heavenly call,
I doubt not your being borne up through the service before you,
to the glory of the great Name,
and the propagation of the blessed gospel of Christ among men.
Rejoice then, my beloved friend, that you are honoured with a part of the ministry;
continue to let it be as your food and drink, your ordinary food,
to do the will of Him who sent you, and to accomplish your allotted share of his work.

I love to reside in the humble valley, and that the precious dew may lie upon my branch.
And thus I wish you, my beloved friends, enlisted, accoutred, engaged,
and committed in the most glorious cause which ever dignified human nature;
that in the nothingness of self, and abasement of the creature,
you may receive your fresh supplies of spiritual
ability from the sole source of all right,
religious qualification.
And if in some places there is not an ear to hear, no opportunity to scatter, go forward,
bearing the precious seed.
I am ashamed to take the liberty thus to write to my superiors;
but interpret it as the effusion of simplicity and love.
Do let us know how you get on every way.
Many are deeply interested in your welfare, and among those,

[.signed-section-closing]
Your truly affectionate friend and kinsman,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore 8th of 7th Month, 1790.

[.salutation]
My Dear Margaret,

I have indeed abundant and renewed cause of thankfulness to our Almighty Benefactor,
for his gracious protection still extended,
and his safe conduct of a very poor and helpless creature, home to my family and friends.
I have also humbly to acknowledge the daily supplies every way afforded,
profitable to me, for doctrine, for reproof, for correction,
for instruction in righteousness: thus the rod and the staff, administered in wisdom,
alternately rectify and regulate, assist and comfort;
and so poor pilgrims move along under repeated convictions
of their own infirmities and insufficiency,
and under a renewed experience of continued mercy and divine aid.
The yearly meeting of London seems like a home or habitation to my spirit.
I am dipped there, I trust, in some degree, into the state of the Christian cause,
and engaged in a travail, and secret,
silent wrestling for a blessing on the endeavours of the
faithful in this day for the promotion of it:
this I look upon as my principal business there, though a good deal of other matter,
relative to church-affairs, falls to my lot besides,
and calls for diligent exertion of my best abilities.
Upon the whole, my dear Margaret, I do hope this most important cause gains ground;
and that, though there still remain some fruitless, sapless trees in the wood,
yet a great number of promising young plants have taken strong root downwards,
and are shooting vigorously upwards.
Much depends on their preservation from any annoyance--on their upright growth,
and bearing each their own kind of fruit in due season.
My journey to and from London, and temporary stops at sundry places,
as well as some few excursions in the neighbourhood of London,
were generally attended with satisfaction to my mind.
I renewed precious amity with old surviving friends;
and I met with opportunity of cultivating a pleasing
and profitable intimacy with some new ones.
I saw my friend Burke, had him awhile to myself, and admired and loved him afresh.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Carlow, 19th of 7th Month, 1790.

[.salutation]
My Beloved Cousin,

My wife and I, and several of us of this monthly meeting,
have been engaged a little at home, in a degree of like labour as engages you abroad.
We have been endeavouring to dress the garden already enclosed,
the soil of which is indeed poor enough, and weeds enow, rooted and running to seed,
in danger of disseminating their own prolific species,
to the deforming of the garden and the annoyance of the hopeful plants.
You are occupied in the wide and wild field,
where there is abundance of rough work to be done, access to be gradually made,
rubbish to be removed, stones to be gathered out,
and the gospel plough and harrow to be introduced.
I have at times been favoured to meet with you there in spirit,
and to desire a blessing on your work.
In so large a field of labour,
your work may indeed seem small and contemptible in your own rational view; but,
as it is said, "`Everything has a beginning,`" be not discouraged; do your part,
and that is enough for you.
Sow the seed in faith, and leave it under the blessing of the Heavenly Husbandman:
other labourers may be sent hereafter into the field, in the progress of the work,
with different tools and instruments, for further service.
The present time, the present might and ability, diligently and rightly employed,
are the most likely means for the business to be effectually promoted,
and for the securing and establishing your own peace, the precious penny,
the inestimable reward.
My fellow-labourers have left me here, as I am so far on my way to Youghall,
where the province meeting is to begin, the 25th instant;
and where I expect to meet with old James Christy, and John Gough,
and several other friends, in order to essay a beginning of the national visit,
which has been appointed here.
I understand John Gough has lately had an alarming paralytic stroke,
which nearly deprived him of the use of one side for some time;
but was so far recovered as to be able to attend their late quarterly meeting near Charlemont,
where he had very acceptable service,
appearing with increasing brightness in his Master`'s cause, who, I trust,
will strengthen him every way for this fresh service.
I love to see people so devoted, so dedicated, so set upon promoting the cause of Christ.

I hold myself much obliged, as I have been much gratified,
by your kind communication from Amsterdam, of the 1st instant.
Continue, my dearly beloved cousin, so to favour me; for you are precious with me,
and your preservation, and perseverance in well doing,
are among those subjects of solicitous travail which are interwoven with my best feelings.
Peace be to you, and peace to your helpers!
The Lord has helped, does, and will help you.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 23rd of 11th Month, 1790.

[.salutation]
My Beloved Margaret,

It was very kind, in your situation, to take the trouble of writing.
We feel indeed for you, and wish it were in our power to afford you any relief.
We have none to send you except our advice, and that I believe you have no occasion for;
for you know where to look for help, and who it is that can say "`peace,
be still;`" and the storms in the moral, as well as in the elementary world,
obey his voice.
But it is often easier to give advice than to take it:
it is easy to recommend resignation; but when the trial comes home to us,
and the exquisitely tender feelings of nature are affected; then to say with the heart,
"`Your will be done!`" is to overcome indeed.
And yet such a victory over humanity may be gained,
and is often gained by the Lord`'s children, in their pilgrimage through this life;
and being strengthened by his love and his power, they can,
in all humility and gratitude, kiss the rod which chastises them, and bless the hand,
which in perfect, though unsearchable wisdom, both gives and takes away.
Our sympathy with you, my dear child, is strong; and our hope, I trust,
is not of the hypocrite, which perishes; our hope is, that you will, in the Lord`'s time,
be raised out of those pits of distress, and having been made a witness of deliverance,
will have experimentally to testify to the sufficiency of that arm of everlasting Power,
which could deliver in such sort,
and to encourage other travellers in the like tribulated path, to hold on their way.

Your son Abraham is in good health, through favour of Providence; a fine, sensible,
well-disposed boy, who, I trust,
will be a comfort and assistance to his worthy father and you.
When I speak of comfort,
I must consequently think of our dear Sarah R. Grubb whom
to have so near you must be pleasing and strengthening.
It is strikingly remarkable, of how singular and manifold service one person is,
whose good natural understanding is imbued with divine wisdom, and who,
in all humility and devotedness, goes on in simplicity, doing the great Master`'s will.
How great then must be the use, and how powerful the effect,
when many such are combined together, assisting and encouraging one another,
and assisted and encouraged by the Head of the church.
So that every individual should look well to themselves,
lest their failure to come properly forward should not only be to their own great loss,
but to the impoverishing and debilitating of the
general effort for promoting the common cause.
I hear that account has been received of the release of our dear friend, William Mathews,
from this warfare.
Now, my dear M. with the one heart of two parents affectionately
solicitous for your happy release,
in due season, from every burden, and that all sorrows may, in the Lord`'s time,
be changed into joy, I bid you most tenderly and cordially farewell.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to S. G.

[.signed-section-context-open]
Ballitore, 25th of 11th Month, 1790.

[.salutation]
My Dear Samuel,

This morning we received the account of my sweet
little grandson`'s transit from earth to heaven;
a happy exchange indeed for him,
without undergoing the troubles and running the risk of length of days.
But I know your tender heart will be grieved, and that such trials deeply affect you.
Let this reflection comfort you:
that your children thus removed are safe and well provided for,
and that you will have no tears to shed for their misconduct.
He who does all things in perfect wisdom, and knows what is best for us all,
thus orders respecting us, that we may by his humbling, refining dispensations,
be made what he would have us to be.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Sarah R. Grubb.

[.signed-section-context-open]
Ballitore, 27th of 11th Month, 1790.

[.salutation]
My Dear Cousin,

I often crave to be preserved from stealing, and taking the great name in vain; that is,
from unwarrantably and illicitly meddling with religious subjects;
and I hope it is under some of this awful covering and salutary fear,
that I endeavour to keep up a correspondence of this sort,
with a number of dear and intimate friends.
I consider that we have "`gifts differing according
to the grace that is given to us;`" that I have,
when at home, some leisure time; and that I find I have neither a cast, nor liking,
nor capacity for many ordinary affairs, which occupy many people`'s time and talents:
they attend to that which pleases them, and which they understand.
Why may not I attend to that which pleases me, and in which I wish to improve;
provided I neither hurt myself, nor anyone else?
I know that, as good economists, we should have a storeroom in our house,
in which things not needed for present use should be carefully locked up;
and that frugality and industry are very necessary qualities,
as the means of exercising liberality in due season.
To be frugal, not parsimonious; liberal, and not lavish;
is what I think we should endeavour to learn.
But why all this preface?

As I lay awake this morning, you occurred to me; and no wonder,
as you are the frequent companion of my thoughts; you seemed to me rather poor and low,
like myself, and I thought I would try if I could converse with you in this manner.
I do not need to make a flourish in praise of poverty; as some people,
instead of bowing down under, and bearing the cross,
appear to me to ride exultingly and ostentatiously upon it; but I want just to manifest,
by this little token, my sensibility and affectionate sympathy with you.
Neither do I need to give you advice on the occasion.
I am not so vain and foolish as to think you stand in need of my advice.
You are a trained servant,
and are acquainted by this time with your Master`'s ways and manner.
You have, though young in years, been long under his holy discipline,
and know that much exercise, conflict, and probation is continually to be gone through,
in order to be made "`perfect, thoroughly furnished unto all good works.`"
You have drunk deeply of divine consolation,
and you have known a walking in the light of the Lord; yes,
your path has been for a season as the shining light.
No wonder then that in turn you should not only be stripped of your priestly robes,
but compassed with the troubles and perplexities, which belong to us, as being flesh.
I believe, indeed, that those who ascend to the greatest heights of the holy hill,
and as instruments are made most eminently useful;
I believe that those have to descend proportionably into the lower parts of the earth,
and have the greatest need to experience a being buried with Christ,
by baptism into death.
Such is the frailty and fallibility of our compound natures,
that the great Author of them knows there is a necessity for our
undergoing repeated humiliations and abasement of self,
that we may know and feel, and be made thoroughly sensible of this important,
essential truth: that "`we are not sufficient of ourselves even to think any good thing,
as of ourselves, but our sufficiency is of God.`"

It is a considerable comfort to us, that you, my beloved cousin, are got home,
while our dear Margaret has been so tried.
She has lost her little John.
We are in anxious expectation about her, but our hopes overbalance our fears.
We trust that our gracious Benefactor will be mercifully
pleased to bring her through her dreaded conflict,
and restore her to her family, to her friends, and to the church;
which stands greatly in need of well-qualified, experienced, devoted, active members,
who have witnessed the dispensation of preparation for acceptable service.

[.signed-section-closing]
Farewell, my beloved friend and cousin.

29th. This letter has been delayed; and we have, since it was written,
received the glad tidings that our dear M. had increased her family,
for which I desire to be favoured with a thankful heart.
By Elizabeth Pim`'s letter, I find several of you were bound for Cork.
I might indeed have thought of the quarterly meeting being to be there.
Once more, and evermore, my dear cousin, farewell!

[.signed-section-signature]
Richard Shackleton.

--

The following letter, dictated by Sarah R. Grubb, four days before her decease,
in reply to the preceding from Richard Shackleton concludes this interesting correspondence.
Sarah R. Grubb was seized with a fever while at Cork, and died the 8th of 12th month,
1790.

[.embedded-content-document.letter]
--

Your salutation met me, though apparently out of course, in the right time;
being under impressions which make time and circumstances of little account,
compared with the unlimited consolations of the Spirit,
or a preparation to receive them at the Divine hand.
My soul, though encompassed with the manifold infirmities of a very afflicted tabernacle,
can feelingly worship, and rejoice in nothing more than this,
that the Lamb immaculate is still redeeming, by his precious blood, out of every nation,
kindred, tongue, and people; and making a glorious addition to the church triumphant,
whose names will stand eternally recorded in the book of life.
I express not these things from a redundancy of heavenly virtue,
but from the soul-sustaining evidence that, amidst all our weakness,
and conflicts of flesh and spirit,
an interest is mercifully granted in Him who gives victory over death, hell,
and the grave.

[.signed-section-signature]
Sarah R. Grubb.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to Robert Grubb.

[.signed-section-context-open]
Ballitore, 28th of 12th Month, 1790.

[.salutation]
Dear Cousin Robert,

I doubt not but you have had many affectionate, sympathizing,
consoling salutations from your numerous friends, in your present solitary state;
and should these be withheld,
yet you know where and in whom are hid all the fresh springs of true consolation,
as well as all the treasures of wisdom and knowledge;
yet I had a mind to throw in my mite of comfort,
having myself been tried in like manner with the privation of a bosom-friend,
and partner in the cares and comforts of this life, and a faithful, religious help-mate.
Infinite Wisdom indeed has seen fit to "`take away from you the
desire of your eyes with a stroke;`" but the reflection of your
having been favoured with so excellent a companion;
the recollection of the many pleasant, profitable seasons which you had together;
and a sense of the spiritual benefit which has accrued from your near connection,
must be at times attended with a savour,
and consolatory feeling which sweetens the bitter cup.
Your tender care of this eminent, honourable servant;
your attention to her needs of every kind;
and your constant promoting and assisting her in her progress in
the great work and service in which she was engaged on earth,
must also be a source of solid satisfaction to your mind,
in the frequent retrospect which you will have to take of
the time of your journeying together in the road of life.
So that I wish you, my dear cousin Robert, to be cheered, to look up,
to be encouraged to attend to the civil and religious
duties of the remaining part of your day;
and to endeavour, by your own spiritual growth in the root of Divine life,
and improvement in holy experience and right capacity for religious service, to make up,
according to your measure, in some part,
the great loss which the church militant has sustained,
by the translation of this noble and splendidly-useful instrument from earth to heaven.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 25th of 1st Month, 1791.

May we all be preserved objects of gracious, condescending regard;
and if it should please Infinite Wisdom to give any
of us an understanding in spiritual things,
and to qualify us at times a little to handle them, let us,
in all humility and reverence,
receive the commission and command as a favour far
transcending all worldly honours and emoluments;
let us not slight, nor regret, nor repine at the heavenly gift,
but gratefully attend upon it, and use our diligent endeavours to improve it,
to the honour of the giver;
that so our lives may flow on as comfortably as is
to be expected in this mixed state of existence,
under the renewed evidence of Divine approbation;
that we may leave vestiges and way-marks to the succeeding generations,
which they may safely and happily follow; and having had the high honour of being,
in any degree, engaged in the promotion of the reign and government of Christ on earth,
may be eternally happy with him in his heavenly kingdom.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 2nd of 3rd Month, 1701.

[.salutation]
My Dear Margaret,

Your mother received yours of 26th ult.
and though you do not speak out, I cannot but think that you dared not stay at home;
so give up cheerfully, and come to this north country.
People may talk of the weight and influence, and respectability of age;
but if younger persons do not go forth in the service, and exert themselves,
the cause will suffer.
I am not for dragging you, my dear child, from your domestic concerns,
which are various and important; but if truth gently draw you,
and whisper that a duty is to be done,
I would have you follow its leadings and secret monitions.
He that made is all-sufficient to preserve: the kine, indeed,
must be allowed to low as they go; the natural part,
to regret the parting with the inexpressibly tender connections left at home;
but the ark of the testimony must be taken out of the land of the Philistines,
and blessed will they be with whom it rests.
So, my dear Margaret, be not dismayed, but if you have heard the call, go forth,
though it may be weeping: bear and scatter the precious seed,
according to heavenly direction, and there is no doubt but peace will be the crown.
Your sister Sarah holds herself in readiness to go with Mary Dudley.
I hope it is right, but I am sure it is a close trial to us.
I feel a soft part in my nature: nature must get vent.

[.signed-section-signature]
Richard Shackleton.

--

[.offset]
In this year, (1791,) Mary, third daughter of Richard Shackleton,
was married to William Leadbeater.

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth Shackleton to His Son-In-Law Leadbeater.

[.signed-section-context-open]
Lurgan, 13th of 4th Month, 1791.

[.salutation]
Dear William,

Having written to your mother, and the rest of our children in Ballitore,
I thought it would not be unacceptable to you to be remembered likewise in this manner.
So, my dear William, trouble comes to all the race of men:
it is the condition of our nature, and no doubt necessary for us.
May you and your dear companion not be too much wrapped up in each other,
but in the time of outward tranquillity, and respite from heavy affliction,
seek diligently to get settled in some hiding-place in that rock,
the inhabitants whereof find a shelter from the storms; yes,
and at times sing in secret for very joy of heart.
It will be a very capital favour to be rightly helped through the present service:
it is difficult and dangerous--requires meekness of wisdom indeed.
I wish that you, who are young, may keep very constantly going to school;
that so you may be learning more and more every day,
and be more and more qualified to understand and
to teach the living lessons of pure Christianity.
This knowledge is indeed worth aspiring after.
It comprehends life eternal: it is not seated in the head, the region of the imagination,
but it occupies the heart; and, like the sense of feeling, pervades the whole inward man.
You know, dear William, something of this Divine nature:
it was the precious sense of it which caused in you such a disrelish for insipid,
lifeless, outward, unsubstantial forms.
Continue to hunger and thirst after it, and it alone, and in due season you will be fed.
Be content, yes, glad to be preserved one of the babes in Christ,
who are nourished by the milk of the word;
and not one of the wise and prudent of this world,
from whom the gospel of life and salvation is impenetrably hid.

M+++.+++ W. shines in her gift; our dear M. G. in her line,
appears clothed with the spirit of the gospel;
dear S. W.`"s little effusions are very acceptable; R. G., I hope, well concerned.
So we are getting on as well as we can, cautious and fearful, that so we may do no hurt.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
Lurgan, 19th of 4th Month, 1791.

The good and gracious Master would favour and overshadow with his goodness, but vain,
vain man, letting in another power to rule and sway,
the rain from heaven falls unprofitably, as it were, on the troubled sea.
However, in this we have satisfaction, that we have laboured plainly, honestly, tenderly,
respectfully, and firmly, both publicly and privately,
in order to bring into the unity and harmony, and to defeat the enemy`'s designs;
but I fear little is effected, besides bearing our testimony against that which is wrong,
and lifting up the standard of peace and concord.
The Lord grant that the princes among the people may flock to it!
Then I believe religion would flourish in this flourishing province.
You may think, my dear love, from this description,
that we have had a troublesome time of it.
Meekness of wisdom was the word, and I hope it was in a good degree kept to;
but though Moses was the meekest of men, he was also an undaunted warrior,
and fought with ardour to get the enemy of the true seed cast out of the land.

The monthly meeting proved a favoured, owning, bowing season.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
London, 12th of 5th Month, 1791.

Last afternoon I attended another sitting of the Committee on the Queries.
It is a very difficult job to get on with;
there is so much critical accuracy about choice of words.
I had to rub up my old Greek, and to give my interpretation of a word,
in the original language of the New Testament.
However, I felt the Power, which gathered us to be a people, near,
as they were framing and fashioning patterns for the discipline of the church;
and I bowed in humility and thankfulness to the Power, and travailed for a blessing,
on the endeavours used for the preservation and strengthening of
that which yet remains of glory and excellence among us.
My cry also was, and is, for wisdom,
that I may be instructed to behave myself aright in the house of God;
and if I meddle at all, that it may be with clean hands and a wise heart.
There is too much of the mere natural and superficial among us:
there is need of going deeper down than many do.
These things, the propagation and promotion of vital Christianity, are solemn, awful,
and ponderous.
Who is sufficient for them?
Not the wise and learned in the wisdom of this world;
not the rich and great in earthly possessions and rank;
not the prudent and crafty in human policy;
but those whose sufficiency is of and from the Lord Almighty,
who have no confidence in that part of themselves which appertains to the flesh;
who are as willing to be nothing as anything,
and who seek not themselves nor their own honour,
but the honour which comes from God only.
And such, I am persuaded, are still mercifully preserved.
It is not in the power of our nature to acquire the knowledge of the truth;
it is not in us to retain it in our experience; but we may very easily and readily,
as in a moment, dissipate, squander it away, and lose it forever.
Yes, while we preach to others; while we handle the law and support the testimony,
we may, without watchfulness and religious fear, become cast away from Divine favour,
and die to any sensations of good, or capacity to do good.
So let us fear as well as love, and be sure to take heed to ourselves first,
then to the flock, the sheep, and lambs of Christ,
if indeed we feel that we are appointed by the chief
Shepherd to take any oversight thereof.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Mary Leadbeater

[.signed-section-context-open]
1791.

I earnestly desire your particular attention to your mother.
Bear with her infirmities, prevent her wishes, supply her needs,
and lighten my absence to her in every respect, as much as is in your power.
You know the tenderness of the conjugal tie, and therefore you will bear with me.
I am persuaded that your husband, who is the very model of good nature, humanity,
and equanimity, will do his part of this business.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Son.

[.signed-section-context-open]
London, 18th of 5th Month, 1791.

Alterations, changes, dismemberments, etc. will fall out in families.
May we each seek to get settled on that which is unchangeable;
that in whatsoever proportion prosperity and adversity, things pleasant and disagreeable,
be mingled in the cup of life,
we may take it patiently and resignedly at the Lord`'s hand.
So will it be a cup of blessings to us: we shall be strengthened with effectual help,
and take courage to proceed to the end of our journey;
where the great plus ultra will open upon us, where is no mixture, no sorrow, sighing,
nor sickness, but joy everlasting upon the heads of the faithful, devoted,
humble followers, of our Lord and Saviour Jesus Christ.
The close of the business last evening was the reading of the testimonies
concerning our late beloved Sarah Robert Grubb.
It was a very solemn time.
Joseph Gurney Bevan read audibly and feelingly:
Lewis Majolier stood by and looked on the writing as the other read,
that he might the better collect the sense of a language
in which he was but little versed.
When Joseph Gurney Bevan had finished reading,
L+++.+++ M. asked permission to add his verbal testimony, which he did in a few sentences,
very explicitly, properly, and feelingly.
Joseph Gurney Bevan interpreted for him, sentence after sentence, as the other spoke,
in a very clear, intelligible manner.
The solemnity was great, the audience was very large; and, I believe, much pleased,
and I hope edified by the whole transaction.
For my part I was favoured to feel deeply, and to mourn, as I would wish,
the church`'s loss.
So much for that bright star, now set forever to this lower world.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Colebrook Dale, 4th of 6th Month, 1791.

[.salutation]
My Dear Margaret,

Believing it will be acceptable to you to hear from me,
I take up the pen at the house of our friend, Richard Reynolds, and have,
through the continued kindness of merciful Providence,
to inform you that I am in good health, enjoying the converse of friends,
whom I feel near to my heart,
and to whose hearts I have abundant reason to think I am nearly united.
Deborah Darby`'s presence would indeed consummate our social felicity;
but I believe she is rightly employed about her Master`'s business, from which,
neither the partiality of special friendship, nor maternal tenderness for her children,
who are here during school vacation, have attraction sufficient to draw her.
She and Rebecca Young are on their way from yearly meeting, visiting meetings, families, etc.
They are not likely to arrive here during our stay.
The yearly meeting was large, and, I hope, solemn.
I hope also that it was renewedly felt and experienced, that,
notwithstanding lamentable declension and dimness may be acknowledged,
our religious society is still owned a chosen people,
among whom the lively oracles are deposited,
the gifts and graces of the spirit are bestowed,
and the principles of pure and genuine Christianity are professed.

Much time had been previously employed, and during intervals continued to be employed,
about modelling new sets of queries: this furnished ample scope for argumentation, etc.
For my part, through the most merciful and gracious condescension of the Lord Almighty,
if in humble reverence I may so presume to say, I was satisfied,
having several times got down to my own hole in the rock,
the secret place of the stairs assigned me.
In that domicilium, that little mansion, I am not only content, but thankful to dwell.
May but the hand of Omnipotence preserve me there! for even
there the enemy will endeavour to make an entrance,
and defile, and defeat, and destroy if he can;
for that is the work of his cruelty and malice.

I doubt not that our beloved Elizabeth Pim would communicate to
you some intelligence respecting the women`'s yearly meeting,
etc. which her valuable sister G. would send her.
This dear sister grows, I hope, in a capacity for religious service,
and in the qualifications of a mother in Israel.
May they both grow together in the Lord:
so will their labours and their example be of singular use in their day,
and infinite and glorious will be their recompence of reward.

James Lecky, Anna Taverner, and I, set out from Worcester yesterday,
and arrived in the evening at this highly-favoured spot,
where we are most kindly and cordially entertained.
I expect we shall stay for the meeting here tomorrow,
and next day set off for Manchester, in order to pay a visit to dear Sarah Taylor, who,
we understand, appears to be near launching out of time, into, no doubt,
a blissful eternity.
If we can receive her last blessing, it may, perhaps, help us on our way.

And now, my beloved Margaret, having given you, historical, and all as it occurred,
I must draw to a conclusion.
You know that you are exceedingly near and dear to me,
and that your poor father`'s chief joy is to see, to be sensible,
that the children of the elect lady walk in the truth.
You have received a heavenly gift, let it be of whatever denomination it may.
What matters the name of it?
Attend upon it, prize it: it is the wisdom which is more precious than rubies.
Exercise it when the great Master bids; when he comes, calls for you, singles you out,
and puts you forth in any little service.
This is the way for the waters of this life`'s afflictions
to be changed into the wine of the kingdom,
and for the sorrows and perplexities of this world to be turned into heavenly joy.
Nothing short of hearkening and obeying will do; but diligently hearkening,
and faithfully obeying will do--will do all for you, and more than you can ask or think.

Farewell, my dearly beloved child.
Remember me affectionately to your worthy husband, sweet children,
all relations and friends.
I must particularize my dear E. P.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
Manchester, 7th of 6th Month, 1791.

Sarah Taylor, to all appearance, is not likely to hold out many weeks.
Good was evidently near her, and her door of utterance was open.
She spoke feelingly of that ocean of love and life,
which had been much the companion of her thoughts, and into which +++[+++I trust]
her cloudless sun was about to set forever.

We spent a few days at Colebrook Dale to satisfaction,
to which the company of R. R. did not a little contribute.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 23rd of 8th Month, 1791.

Who is exempt from trials and temptations?
This life is the field of battle,
and our most dangerous enemies are those of our own house.
May the lamp of God, in the temple of our hearts,
be kept still renewed and replenished with heavenly oil,
that we may have a clear sight of what is doing within us,
lest we should think otherwise of ourselves than we really are.
Purity of heart is a main qualification for any service in the church of Christ;
let us then use all diligence to obtain and retain this precious state.
"`Blessed are the pure in heart, for they shall see God.`"
They shall clearly discern the things which belong to his kingdom,
and when they speak of them, it will be of what they have seen with their spiritual eyes,
and what they have "`looked upon;`" what has been brought
by the Holy Spirit before their internal view,
as an object of contemplation for themselves,
and a subject which they are authorized to handle with clean hands,
and with hallowed lips to communicate to others.
Your effusions in this line, my dear M. according to the best of my apprehension,
are thus sanctified and commissioned.
I have had near unity with them, and I would have you, my dear child,
to "`thank God,`" that it has been his good pleasure thus to honour you with his commands;
and I wish you also to "`take courage,`" and proceed in the exercise of your gift.
Let your heart keep the commandments of wisdom, and the law of the spirit;
"`for length of days, and long life, and peace shall they add to you.`"

Farewell, my dear child; I am thankful that I am your affectionate father,

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 22nd of 11th Month, 1791.

[.salutation]
My Beloved Margaret,

I was favoured with your very acceptable letter,
and join you in gratitude for your getting so bravely home, and finding all so well.
Numberless are the favours, known and unknown, which we are made partakers of,
by the gracious interposition and ordering of our bountiful Creator and preserver.
May they all conspire to raise in us desires to serve him according to his will,
and may we manifest our gratitude by our filial obedience.

I gratefully and greatly admire at my enjoying so considerable a share of health.
Several of us attended our meetings for discipline at Carlow, the 18th inst.
A+++.+++ T. was with us, exercising her gift in public,
and completing what remained of her visit to families there,
which she has now performed throughout our monthly meeting.
Well, I do love to see business, the Lord`'s business, going forward,
and the youth stepping into their lots, lively, experimental witnesses,
of the power of an endless life; fresh, feeling, and full of good matter;
loving their Master, and willing to give that proof of it which he peculiarly required,
that is, to feed his lambs and his sheep.
A little longer time and we are numbered to the silent grave,
in common with all the generations which have been before us.
Let us then, while we are here,
seek for help to do our duty acceptably in the sight of our great judge, that so,
at the awful day of decision, our spirits, disrobed of this mortal clothing,
may hear the blessed sentence with unspeakable joy,
and be mercifully separated to eternal felicity.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
Mountmellick, 29th of 11th Month, 1791.

I know not how it may continue with me,
but I have hitherto felt more of the baptizing power of truth, I think, in this visit,
than I have usually experienced on like occasions.
I do not mean that I have found any increase of religious capacity to move in service,
but my spirit has been engaged in deep travail for the sake of the cause of Christ.
Indeed, this seems the business allotted me:
a silent travail and wrestling of spirit for my own preservation,
and for the return and restoration of our church,
which seems in danger of going back into the wilderness, out of which she came,
in former days, leaning upon her beloved.
It is painful indeed to see that there are so few, in most places,
qualified to answer the necessary calls and duties in religious society; but, I trust,
a number of the rising generation, being sensible that these things are so,
will be stirred up with a noble emulation and godly zeal,
for the promotion of this blessed cause;
in which they will have peace and the favour of their great Creator,
which is far beyond all that this world can afford.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to his Son.

[.signed-section-context-open]
12th Month, 1791.

It is marvellous how A. T. holds out in the depth of winter:
encompassed with bodily weakness and infirmities,
she struggles to get forward in the work pointed out to her, thinking it, no doubt,
her crown and high honour to be employed in advocating the cause of Christianity;
the most great and glorious which ever existed, or will ever exist among men.
There is much difference of sentiment, much conflict and contention among men,
respecting civil government; but few understand anything about the government of Christ.
His loyal subjects are very few:
very few qualified to espouse and promote his government,
though it is under his government alone that men can be safe, comfortable, and happy.
I wish the youth in our religious society would lay these things to heart,
in a general way, and that such of them as know and feel that those things are so,
would not reason with flesh and blood, nor be disobedient to the heavenly vision,
nor tarry behind the prophet, nor leave him;
but go with him in his successive progress to Bethel, to Jericho, and to Jordan, where,
having rent their own clothes in pieces, and occupied the mantle of the prophet,
(the covering of the spirit, the gift,
the qualification for service,) calling on the Lord God of Elijah,
they would know a dividing of the waters,
and a passing over into the several lots and portions of labour.
This is honour indeed, and worthy of the pursuit of immortal spirits.

The elders, the trained servants, the baptized, baptizing ministers,
are gone and going off the stage: "`Your fathers, where are they?
and the prophets, do they live forever?`"

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Sarah, (Then Attending Samuel Neale.)

[.signed-section-context-open]
Ballitore, 28th of 1st Month, 1792.

We are much concerned that you have no more favourable
account to give us of our beloved Samuel Neale,
whose indisposition, and that of his dear wife, is deeply affecting to us.
His particular, kind, and frequent remembrance of me, is grateful to my heart,
which salutes him in affectionate sympathy,
and earnestly desires that he may be supported every way
under the pressure of the present pungent affliction,
and that my dear friend, his faithful wife, may experience like effectual help.

If we really, truly, and sincerely love the Master,
let us willingly give that testimony of it, which he himself requires;
let us be willing to feed his lambs and his sheep.
There is nothing like obedience, it is even preferred to sacrifice,
which itself is highly excellent.
Obedience makes the Almighty our friend, as Abraham was called God`'s friend:
obedience causes peace and tranquillity at home, without which life is insipid,
unpleasant, if not miserable.
So, my dear Sarah, continue to be a good, obedient child,
that I may continue to be a glad and grateful father.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 16th of 2nd Month, 1792.

Whatever symptoms may attend our dear friend`'s bodily disorder,
the symptoms which you report attending his mind, are salutary and comfortable.
It is a fine thing for him now, that in the time of his health and strength,
and active life, he considered the poor,
(the poor church,) and was willing to spend and be spent, that she might be enriched.
"`Blessed,`" says the royal Psalmist, "`is he that considers the poor;
the Lord will deliver him in time of trouble;
the Lord will strengthen him upon the bed of languishing:
you will make all his bed in his sickness.`"
Present us all to him, as a family that loves and respects him sincerely, and wishes,
if it be the Divine will, that he may yet be restored to his numerous friends,
and fill up his measure of service on earth,
that so he may obtain the full fruition of reward in heaven.
He is seldom out of our waking thoughts, and the best desires which we are capable of,
are fervent on his behalf, not doubting but that,
whatever way Infinite Wisdom shall be pleased to dispose, it will be well,
everlastingly well with him.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 29th of 2nd Month, 1792.

[.salutation]
My Dear Child,

Last evening We received the sorrowful tidings of the decisive event,
for which your last had prepared us.
Present your mother and me, and all ours, as one joint family,
which unites in cordial love to, and affectionate sympathy with,
our dear afflicted friend, Sarah Neale.
I feel, I think, that she is supernaturally, effectually, supported in spirit,
under this great trial,
and that she can and does bless the hand which gave and takes away.
See, my dear Sarah, and learn confirmedly by her example,
how happy a circumstance it is to have been enabled to take
the yoke of Christ upon the neck in the early part life;
how such, in time of trouble, and when old age and infirmities increase, have an asylum,
a sanctuary to flee to, wherein they find protection and safety!

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 12th of 3rd Month, 1792.

I would not have you be too concise, nor get a habit of concealing and suppressing,
under an apprehension that your communications are little worth.
There is danger on that hand; though, as it grows out of the stock of humility,
it may be said to be erring on the right side, not on the left.
But I would have my beloved Sarah err on no side, but keep in the middle way,
out of all extremes.
"`I +++[+++wisdom]
lead in the way of righteousness, in the midst of the paths of judgment.`"
It is a certain truth, that when any are engaged in the Lord`'s business,
and see the pointings of his hand to particular service,
much trouble would often be saved by simply making
use of the opportunity put into the hand,
and not deferring, procrastinating, and reasoning, till the vision fades,
the understanding becomes clouded, and the strength and spiritual animation is gone.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to John Thorp.

[.signed-section-context-open]
Ballitore, 3rd of 4th Month, 1792.

It is now above a year since I was favoured with
your very acceptable and instructive letter;
since which I have had the pleasure of personal conversation with you.
The sentiments expressed in your letter, very much accord with my own,
and confirm my experience, so that it seems needless to dwell upon them.
Indeed, as in conversation, so in thus writing, the fresh, unpremeditated,
rising subject, with the fresh life upon it, is only truly pleasing and edifying.

By this time you have felt the loss of your honoured mother, beloved sister,
and faithful friend, Sarah Taylor.
Such a loss is not immediately known to its full extent;
but I think these dispensations are peculiarly useful.
They tend to make the surviving, rightly-concerned, gifted individuals,
still more sensible of their weakness and insufficiency, being thus stripped of,
as it were, collateral strength.
They cause such, under this sense, more importunately to crave Divine help,
trembling for the ark of the testimony, lest in their time,
and while committed to their care, it should fall into the hands of the enemy.
So dwelling here, a growth and increase are, in due time, witnessed:
the little ones are made as Davids, and the Davids as the angel of the divine presence,
ministering joy and gladness,
and kindling those sacrifices which the Lord never did nor ever will despise.
Of what great importance then is it, my beloved friend, that you,
who have received gifts, should not only go down deep, but dwell deep; and,
seeing the works and wonders of the Lord therein,
bring up your stones of memorial from there.
A sound and living ministry is of unspeakable benefit to the church.
The Almighty can do all things by his own immediate power;
but it is his pleasure to make use of the instrumentality of men and women,
in gathering and preserving the Christian church.
Even the head of it desired his immediate followers to pray the Lord of the harvest,
that he would send forth labourers into his harvest.

I fear some too lightly estimate their own qualifications for religious services,
and so fall back in their ranks, and weaken the general cause;
and I fear that sometimes some of our elders, through an excess of caution,
lest they should lift up too much, have been deficient in cherishing as they ought,
and encouraging the "`babes and sucklings,`" out of whose mouth is to be perfected praise.
Therefore there is a necessity to wait to be endued
with that wisdom which is profitable to direct,
that so the understanding of the inward man may be properly illuminated;
and to have the spiritual senses of the inward man quickened and exercised,
that so the understanding may rightly judge of spiritual things.

We too have suffered a general loss in the removal of our friend and brother,
Samuel Neale.
He was a man of a free, open, generous,
candid spirit--of considerable property in the world.
He was a visited and called instrument, a chosen vessel, a brand plucked out of the fire.
He was a baptized and baptizing minister of the gospel,
who spent and was spent in his Master`'s service.
In the active part of his life he travelled on the evangelical errand,
in all parts of the world where Friends were then settled.
For some years last past he grew more infirm, and disabled by bodily disorders;
but bis love to the precious truth,
and his desire to promote the saving knowledge of it was such,
that he still struggled to get out, even among his distant friends.
In the last excursion of the sort which he made, I was with him,
and several other friends.
It was in consequence of an appointment of our half-year`'s meeting,
in which he was free to join.
I did not expect his long surviving that service, and marked the patience, meekness,
humility, and tenderness of his spirit, very much to my satisfaction.
To my satisfaction, also,
I was a witness to the stream of gospel life in which he ministered;
that life in which at the first "`he spoke trembling,
and exalted himself in Israel;`" that life in a remarkable manner
accompanied his effusions through the course of his religious movements,
for above forty years, and evidently crowned his religious labours.
As he was an early and intimate friend of mine, I cannot but feelingly,
though resignedly, mourn his loss.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Sarah.

[.signed-section-context-open]
Colebrook Dale, 12th of 5th Month, 1792.

It looks as if we should stay here today and tomorrow, as none of our company,
beside myself, have been here before; and this is a princely Seat of hospitality,
from which, and the curiosities of which, I am reluctant to hurry my companions away.
I trust I am in degree sensible who it is that has
turned the hearts of this people towards me,
and who has also given me this sensibility and sensation of humble gratitude:
and there is not a doubt, my dear Sarah,
but that if we be graciously preserved in the way of our duty,
we shall have as much room as will be good for us in the hearts of our fellow creatures.
It is said, I think, that when a man`'s ways please the Lord,
he makes even his enemies to be at peace with him.
How closely then must the sweet union of friends be rivetted in such a case!
May our ways, my dear child, be so directed as more and more to please the Lord;
then I am sure it will be happy for us; our increase will be unto holiness,
and the end everlasting life.

Christ washed the feet of his disciples,
previously to the command that they should wash the feet of one another.
How remarkably cleanness was insisted on, and prescribed under the Jewish dispensation,
and how absolutely necessary it is in these gospel times:
it is necessary not only for beauty, but for strength:
men of clean hands shall wax stronger and stronger.
I have done what I could for you, my dear children, by way of worldly provision.
If I had been more of one of this world`'s children,
probably I should have done more for you in that way.
I have done what I could; and I trust, if you look and lean aright,
He that was mercifully pleased to care and provide for me,
who (in my estimation) am more unworthy, will not fail to care and provide for you,
every manner of way.
Love, and aid, and cherish your dear mother, as you have done.

Farewell, my precious Sarah; your simplicity, faithfulness, and obedience, will, I hope,
ever unite you to my heart;
which earnestly desires (and desires nothing more for you all than)
that you may walk in the fear and wisdom of our great Creator.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Mary Leadbeater.

[.signed-section-context-open]
London, 19th of 5th Month, 1792 (Dies quern semper acerbum habebo.)^
footnote:[The day on which Richard Shackleton lost his first wife.]

The cordial welcome I received from my very kind friend +++_______+++,
was particularly grateful to me,
and the kindness and attention of his wife are renewedly imprinted on my heart.
Their children too; their children are like Friends`' children,
love the society of Friends,
and are settled in the habits in which they have been brought up; habits of humility,
reverence for the laws and ordinances established among us,
and love and respect for good men.
They are brought up as wise children, who make glad fathers and mothers.

When the mind is relieved and strengthened by supernatural aid, there is a submissive,
patient acquiescence with the divine will; a belief that all that the Lord does is right;
and a humble, stedfast hope, that having been graciously pleased,
in condescending goodness, to love his own (his called, visited, chosen,
preserved children) in the early, inexperienced part of life;
and having manifested his providential care, support,
and supplies throughout their journey, he will love them to the end.
So I hope your dear mother, my precious help-mate,
will not be permitted to sink below measure; but rely on,
and feel underneath the everlasting arm of sure help.
You will, I doubt not, continue to take all necessary, assiduous,
affectionate care of her; and her prospect, whether she looks backward or forward,
as to herself, seems, in my estimation, bright and clear;
so to all-wise and all-merciful Providence, I commit and commend you all.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Wife.

[.signed-section-context-open]
Clonmel, 2nd of 8th Month, 1792.

My nearest natural connections, present or absent, are the objects of my affectionate,
tender, solicitous care, and best thoughts.
I do not often make an excursion of this sort, to gratify paternal love;
but I thought long to get some of the conversation
as well as company of our beloved Margaret:
the latter I had some time ago, but it was attended with very little of the former.
I now and then am, at this season, much gratified with her lively effusions,
and I never was so much pleased with her little flock before.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Mary Leadbeater.

[.signed-section-context-open]
Clonmel, 4th of 8th Month, 1792.

It is very pleasing intelligence that your mother is as well as usual.
I hope she has by this time got her children with, and about her; and that they,
with the hope of the next generation after you, her grandchildren,
comfort and cherish her.
I wot uneasy at not hearing from some of you;
but a little matter lays my storm pulveris exigui jactu.
I continue, thank Providence, in good health; visiting my friends,
chatting with Margaret, and pondering at times about my own state,
and the state of others.
Providence best knows what is best for us.
He knows how to proportion what is called good and evil in this life,
so as that the aggregate may be most to our advantage; as said the royal psalmist:
"`How precious also are your thoughts unto me, O God!
How great is the sum of them.`"

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to His Daughter Margaret.

[.signed-section-context-open]
Ballitore, 9th of 8th Month, 1792.

We should be pleased with intelligence concerning E. H.
M+++.+++ D. and E. P. a precious triumvirate gone on a high embassy.
It is comfortable to find that the Great Master is thus sending messenger after messenger,
on his holy errands; and that, notwithstanding our lapsed state,
so many are found worthy to be honoured with a commission from the Great King,
and willing to take as it were their lives in their hands, and run to and fro,
that the saving knowledge of God and Christ may be increased in the earth.

[.signed-section-signature]
Richard Shackleton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From the Same to the Same.

[.signed-section-context-open]
Ballitore, 20th of 8th Month, 1792.

I expect to go to Mountmellick tomorrow, to attend the monthly meeting there next day,
and join in a visit to the provincial school.
My precious Margaret, farewell!

[.signed-section-signature]
Richard Shackleton.

--

Withdrawn from the busier scenes of life, while their sun descended brightly,
Richard and Elizabeth Shackleton were solicitous,
not only for the welfare of their own family, and the society to which they belonged,
but for the race of mankind.
When Richard Shackleton returned home after journeys taken from motives of duty,
he returned with a thankful and cheerful heart,
although sometimes in tears--tears springing from grateful sensations;
for he enjoyed all his comforts of every kind; desiring nothing but what was allowable;
and with pious resignation submitted to the bereavements,
which his susceptible nature poignantly felt.
He was indeed greatly favoured in domestic and social life;
and his own company and conversation, while it increased the happiness of all around him,
by that means also increased his own.
He delighted and instructed his associates, because he was humble and condescending:
the gentleman, the scholar, and the Christian were united in his character;
and it was also marked with a simplicity which derogated nothing
from the dignity that pure and undented religion confers.
It was not in the circles of his distant friends or acquaintance,
that this good man appeared to most advantage.
It was by his own fireside,
that his sweetness of temper and his unaffected piety beamed brightest.
His excellent wife was the constant object of his care and affection;
his children also were his companions and his confidents.
He showed them most of the letters which he wrote and received,
and expected like openness from them.
This gave him opportunity to correct their style and their hand-writing, etc.;
and also to judge of the characters of their correspondents,
and to encourage or discourage the friendships they seemed likely to form.
He disapproved the manner that some young persons got into of handling religious subjects,
with which their general conduct bespoke them to be little acquainted;
for though a nursing father to what was good,
he desired not to have this theme introduced without a deep sense of its awfulness.
He often read to his female audience while they sat at work;
and the subjects he chose were likely to "`form the manners, and to mend the heart.`"
Though religious writings, being preferred by him, were frequently introduced,
they were not forced upon his young hearers:
historical events and good moral poetry diversified this entertainment.
He often called to see his neighbours; and bis son`'s house was a second home,
where he loved and was beloved, and where he found his first paternal feelings revived;
while his little grandchildren flocked about him, "`and climbed his knees,
the envied kiss to share.`"
Oh the cheerfulness of a pure mind!
What innocent delight does it extract from every pleasant circumstance.
Whether granted to the happy possessor of such a spirit or to others,
it can appropriate all to its own enjoyment!

Though an almost imperceptible decay of memory,
apparently accompanying a numbness in her right arm, increased upon Elizabeth Shackleton,
these infirmities did not threaten her family with the sudden loss of her;
and Richard Shackleton was favoured with uncommon health,
which seemed to promise long life.
They were universally beloved, and their love was universal;
their years glided on in outward and inward peace, when the stroke of separation came;
grievous to survivors, but doubtless sent in mercy,
to call a faithful servant to meet his reward, and to take him from the evils to come.

Richard Shackleton returned from his last visit to his son and daughter Grubb,
the 8th of 8th month, 1792.
On the 21st he rose early, as he was accustomed to do, bathed, took leave of his family,
and, accompanied by a servant, set out on horseback, for Mountmellick,
to attend the committee for the provincial school.
He left home apparently in usual health and spirits; but his daughter Chandlee,
when he reached her house in Athy, six miles on the way,
thought he did not seem quite well.
However, he proceeded fourteen miles, to Mountmellick,
to the house of his friend John Gatchell.
Not apprehending that he was alarmingly ill, he sat one of the meetings;
but being obliged to go out of the next,
John Gatchell sent Richard Shackleton`'s servant back to Ballitore on the 24th,
to acquaint his family with his indisposition.
His son, and daughter Sarah, immediately went to him:
those who remained at home felt in full force the dread and anguish of suspense.
It was a state they had not long to endure.
It is painful to reflect upon these days; the messages backwards and forwards;
the visits of his children, distressed for both parents; his poor,
feeble wife overwhelmed with grief, and already on her journey to him,
when all was terminated.
This event caused a wide-spreading sorrow, wherever the dear deceased was known;
but bitter indeed were the tears of his wife and children: his little grandchildren too,
young as they were, could most of them feel the pang of separation.

[.small-break]
'''

Notwithstanding the declining state of Elizabeth Shackleton`'s faculties, she felt,
with all its weight and poignancy,
the overwhelming blow which deprived her of such a husband,
and this heavy affliction seemed to accelerate the decay of her intellectual powers.
Yet she got out to General Meetings, as well as to her own, for a few years,
and could enjoy the pleasure of entertaining her friends.
It was in her house that the valuable life of Job Scott was closed,
and she accounted herself favoured in witnessing his happy and triumphant conclusion.

While the helplessness of second childhood, accompanied by the innocence of childhood,
increased upon her,
it might be accounted a mercy to Elizabeth Shackleton
that the cloud which overspread her mind,
once so prevented her from a painful participation in the distresses of her native country.
In the memorable year, 1798, the Rebellion raged violently at Ballitore;
the following winter the quiet of the inhabitants was often
broken in upon by robbers in the dead of night;
yet those who took up arms in rebellion,
those who came armed to inflict punishment upon them,
however furious in their conduct and expressions to others,
uniformly treated her with respect, and often with tenderness.
She did not appear to be terrified, as others were, in those times of dismay;
yet it is likely she felt the effects of the confusion and alarm which surrounded her,
and that her mental energies were additionally weakened thereby,
though she continued sensible of the affectionate
attention manifested towards her by her friends.

Her bodily powers failed by degrees, and, gradually withdrawing from life,
and unconscious of the approach of death, she gently breathed her last,
the 23rd of 3rd month, 1804, in the 78th year of her age.

Thus lived and thus died, Richard and Elizabeth Shackleton,
adorning by their conduct the doctrine they professed; and prepared, we trust,
through the power of redeeming love,
for "`an inheritance among all them that are sanctified.`"
