== Testimonies of Richard Shackleton

[.old-style]
=== The Testimony of Carlow Monthly Meeting, respecting Richard Shackleton, / though it alludes to circumstances in his life which have been narrated in the foregoing memoir, is here introduced, as containing some particulars of his last illness, and affording proof of the estimation in which he was held by his friends.

Richard Shackleton was the only son of Abraham and Margaret Shackleton,
respecting whom honourable mention has been made
in a testimony given forth by this meeting,
and was born at Ballitore, the 28th of 7th month, (O. S.) 1726.
Discovering early an inclination for learning, his father, who kept a boarding-school,
had him instructed in the necessary qualifications
for assisting and succeeding him in that useful occupation.
An account of the visitations of Divine love mercifully extended to him,
is found in his own writing, in a letter to a near friend, conveying much instruction,
as follows:
"`God Almighty visited my spirit with a sense of his goodness (precious
above all things) in the very early part of my life,
as early as I think I have any remembrance.
He graciously renewed the same divine influence upon my soul,
at various seasons of my childhood and more advanced youth.
This sense and savour was everything needful to me; it was knowledge enough,
strength enough, joy and comfort in abundance:
while in possession of this I lacked nothing; all things as to me were right.
But temptations, suited to my cast and dispositions as a boy, were thrown in my way:
puerile amusements, reading unprofitable, vain books were spread before me,
and I was at times taken in the snare.
When the heart gave its preference to these gratifications, the heavenly guest withdrew,
and would not reside with such rivals.
Yet good and gracious was the Lord, who, notwithstanding my unfaithfulness,
would knock again for an entrance, and offer again to visit;
and as I opened the door of my heart,
(or rather He opened by his spirit,) he came in with the power of his judgments,
and by his operative word burned up the chaffy, combustible nature;
and this office being over, remained a flame of pure and heavenly joy.
So I experienced him to be not only a jealous God, but a consuming fire.
Thus, with these alternate visits and conflicts,
I went on till I grew to a more advanced stage of youth; then the subtle nets of glossy,
worldly wisdom, and the toils of youthful lasts, which war against the soul,
proved too strong for me,
and often carried my vessel back again down the stream of natural inclination.
Arrived at manhood, and being about to settle in life,
a high hand arrested me in my course, showed me my state of alienation,
and the impossibility of my making a happy progress without the Divine blessing: so,
in the sincerity of my heart, I obeyed the heavenly vision,
became as a fool among my companions, and an alien among my intimate acquaintance.
I sought retirement and the company of them who companied with Jesus.
My sincerity was seen by the great Creator,
and many were the baptisms I was baptized with in that day:
it was also felt by his approved servants,
and close was the fellowship cemented between many of their spirits and mine.
Thus I have gone on to this day and hour, on the same search, hungry and thirsty still;
not desiring anything so much as the bread of life for myself and my dear friends,
companions in the same travail.

Though possessed of superior natural abilities,
and adorned with the gifts and graces of the spirit, he did not value himself thereon;
but steadily advanced in his pilgrimage,
bowed down under a grateful sense of the numerous favours received at the Divine hand.
To his most intimate friends he frequently enforced the necessity of humility,
as the only safe situation to keep continually in; dreading lest himself,
or those he dearly loved, should by the stratagems of the enemy be drawn therefrom.
His naturally cheerful disposition being in great measure regulated by best wisdom,
he had much enjoyment of social and domestic comforts,
with which he was remarkably blest.
He was a kind, affectionate husband, a tender and careful father, a good neighbour,
liberal and generous,
especially exemplary in anything relating to the needs of our society.
But he was careful that his attention should not
be too long occupied by anything in this world.
Those who had the opportunity of minutely observing his conduct,
have often perceived him retiring from company,
to seek in secret a renewal of spiritual strength.
And we doubt not with like filial piety,
in the midst of his outward employ (which he conducted with great reputation)
he was engaged frequently to ask for Divine counsel and wisdom,
particularly when deprived by death of his highly-valued father.
He recommended to his friends a practice which he found beneficial to himself,
devoting a part of each evening to religious retirement:
the effects of such sacrifices were at times obvious in him,
his countenance indicating that he had been in the best company.

The prosperity of genuine Christianity was the object of his greatest solicitude:
for this his spirit was exercised in deep mental travail:
for this he was willing to be employed in any way consistent with Infinite Wisdom,
in private or more public labour.
He was particularly exemplary in a diligent attendance
of meetings appointed for the good order of the society;
and latterly, when at liberty from his outward occupation,
he almost constantly attended the yearly meeting in London.
He long filled with much propriety the weighty station of an elder.
As his dwelling was near the spring of divine refreshment,
he was often enabled to draw water for the benefit of others.
He was a man of great benevolence,
and the welfare of his fellow creatures was very near his heart,
frequently expressing his deep travail of spirit for the salvation of all mankind.
For the departure from ancient purity, obvious in our religious society,
he deeply mourned: on this account his tears were poured forth;
yet he was consoled in hope,
that through suffering and patience the church would
come forth from her wilderness state,
though he did not expect to see it in his day.

He was often engaged in family-visits in various parts,
and was earnest that the flock might be led into fresh and living pastures,
and feed securely beside the still waters.
He used to say that he esteemed it his honour to be allowed to tread these courts,
or to be employed on any little errand, as a boy or runner, about the house;
because in this house there was abundance of soul-sustaining
nourishment--there was bread enough and to spare;
and when thus broken in spirit among his friends,
and thus pouring forth the warm expression of his gratitude,
he would speak largely of the beauty of the house of God, how it is all glorious,
how its pavement shone with holiness,
and how clean ought to be the feet which trod therein.
He was well gifted for this private labour in families,
which he believed our Lord particularly intended,
when he enjoined the disciples to wash one another`'s feet;
being an unceasing obligation on all their successors in the truth,
to do even as He had done to them,
that by this exercise of discipline the members might
be preserved clean from spot or blemish.
Being endued with the spirit of discernment respecting ministry,
(which he earnestly desired might flow pure and unmixed from the
sacred spring,) he was well qualified to be a nursing father to
those in the station of minister who needed a hand of help;
and such he encouraged to a humble, simple, faithful,
diligent occupying with the divine gift.

In a letter a few months before his decease he wrote:
"`The faithfulness and dedication of some of you has been cause of joy,
and a kind of triumph to me; so that, according to my measure,
I can join a remnant in adopting the apostle`'s expression: "`For what is our hope,
or joy, or crown of rejoicing?
Is it not you in the presence of our Lord Jesus Christ at his coming?
for you are our glory and joy.`"
To the Lord alone be the praise of his own works, but "`let his own works praise him.`"
He was fervent in intercession for his beloved offspring,
that they might be preserved near the source of all our blessings;
and as they dwelt humbly before Him, who is Lord of earth as well as heaven,
he had no doubt but a sufficiency of the good things of this life would be granted them,
with a "`treasure in the heavens that fails not.`"
To a particular friend, about three weeks before his decease, he wrote,
"`I trust that we know something of the vicissitude of day and night,
and the revolution of the Lord`'s year in our spirits;
and that He will be mercifully pleased to deliver us from evil,
and preserve us to the end, and at the end.`"

Being on a visit to our provincial school at Mountmellick,
he was taken ill at the house of our friend John Gatchell.
Under the heavy pressure of his disorder, which was termed a low fever,
he said he did not know how the dispensation would terminate;
if it was come for the final separation he feared he was not prepared,
but he believed the baptism of sickness was necessary for purification.
After much depression of mind, he was encouraged in the recollection of Isaiah, xl.
chapter, 1st and 2nd verses: "`Comfort, comfort my people, says your God.
Speak comfortably to Jerusalem, and cry unto her, that her warfare is accomplished,
that her iniquity is pardoned;
for she has received of the Lord`'s hand double for all her sins.`"
He discovered no impatience, lay calm,
and spoke at times rather cheerfully to those about him.
He once said, "`I think it a favour that I feel a sympathy with the seed in suffering.`"
He spoke of what a gloomy day it was in Jerusalem
when our Lord was about to be offered up,
how afflicted the women were who followed him, and how he exhorted them:
"`Daughters of Jerusalem, weep not for me, but weep for yourselves,
and for your children.`"
Also how the high professors arrayed him in a purple robe, and mocked him;
and that now the same spirit was setting up a mockery of Christianity,
while they were crucifying him afresh.
He said that the present times required to send for the mourning women,
such as were skilful in lamentation.
At another time, appearing under great languor and depression, he said, "`My friends,
my friends, pray for me, that my patience fail not.`"
To some taking leave of him,
he recommended faithfulness and dedication to religious duties,
which would draw down the blessing on them, and on their families:
he said that what we profess is the truth,
which our worthy predecessors were so eminently called to support,
laying the axe to the root of the corrupt tree.
He spoke of a sacrifice which David made that was accepted,
even a broken and a contrite spirit; and he hoped that his also was accepted.

Early in the morning of the 28th of 8th month, being the eighth day of his illness,
he passed through sore conflict.
For about an hour he was favoured with calmness;
frequently embraced a beloved child who attended him;
and about seven o`'clock the same morning, quietly departed this life,
in the 66th year of his age.
His remains, being conveyed to Ballitore, were interred the 30th of the month,
after a solemn meeting.

Having been uncommonly blessed with health,
and his mental faculties continuing undiminished, to his beloved wife,
numerous friends and connections, his removal was an unexpected stroke.
We doubt not his purified spirit is now in the enjoyment of an everlasting crown.
May we profitably feel our loss! "`Who then is a faithful and wise servant,
whom his Lord has made ruler over his household, to give them food in due season?
Blessed is that servant whom his Lord when he comes shall find so doing.
Verily I say unto you, that he shall make him ruler over all his goods.`"

[.asterism]
'''

[.old-style]
=== The Testimony of his friend Edmund Burke, / who also could justly appreciate the character of him whom he had loved so long and so sincerely, ought, in justice to their mutual friendship, to find a place here.

[.letter-heading]
Letter From Edmund Burke To Mary Leadbeater.

[.signed-section-context-open]
Beaconsfield, September 8th, 1792.

[.salutation]
My Dear Madam,

After some tears on the truly melancholy event,
of which your letter gives me the first account,
I sit down to thank you for your very kind attention to me, in a season of so much,
and so just sorrow to yourself.
Certainly my loss is not so great as yours,
who constantly enjoyed the advantage and satisfaction of the society of such a companion,
such a friend, such an instructor, and such an example:
yet I am penetrated with a very sincere affliction, for my loss is great too.
I am declining, or rather declined in life; and the loss of friends,
at no time very reparable, is impossible to be repaired at all in this advanced period.
His annual visit had been for some years a source
of satisfaction that I cannot easily express.
He had kept up the fervour of youthful affections; and his vivacity and cheerfulness,
which made his early days so pleasant, continued the same to the last:
the strictness of his virtue and piety had nothing in it of morose or austere;
and surely no life was better, and, it is a comfort to us to add,
more happily spent than his.
I knew him from the boyish days in which we began to love each other:
his talents were great, strong, and various;
there was no art or science to which they were not sufficient in the contemplative life,
nor any employment that they would not more than adequately fill in the active.
Though his talents were not without that ambition
which generally accompanies great natural endowments,
it was kept under by great wisdom and temperance of mind;
and though it was his opinion that the exercise of virtue was more easy,
its nature more pure, and its means more certain in the walk he chose, yet in that,
the activity and energy which formed the character of his mind, were very visible.
Apparently in a private path of life, his spirit was public.
You know how tender a father he was to children worthy of him;
yet he extended himself more widely,
and devoted a great part of his time to the good of that society, of no mean extent,
of which the order of Divine Providence had made him a member.
With a heart far from excluding others,
he was entirely devoted to the benefit of that society,
and had a zeal very uncommon for everything which regarded its welfare and reputation;
and when he retired, which he did wisely, and in time,
from the worthy occupation which he filled in a superior manner,
his time and thoughts were given to that object.
He sanctified his family benevolence, his benevolence to his society, and to his friends,
and to mankind, with that reverence in all things to the Supreme Being,
without which the best dispositions, and the best teaching, will make virtue,
if it can be at all attained, uncertain, poor, hard, dry, cold, and comfortless.
Indeed we have had a loss, I console myself under it,
by going over the virtues of my old friend, of which, I believe,
I am one of the earliest witnesses, and the most warm admirers and lovers.

Believe me, this whole family,
who have adopted my interest in my excellent departed friend,
are deeply touched with our common loss, and sympathize with you most sincerely.
I hope you will assure my dear friend, Mrs.
Shackleton, the worthy wife of my late invaluable friend,
that we sympathize cordially in all she feels; and join our entreaties to yours,
that she will preserve to you,
as much as possible of the friend and parent you have lost.

[.signed-section-signature]
Edmund Burke

[.asterism]
'''

[.blurb]
=== The following letter is from Thomas Wilkinson.

[.signed-section-context-open]
Yanwath, 25th of Tenth Month, 1792.

[.salutation]
Dear Friend,

It is certainly more congenial to my disposition to visit the abodes of sorrow,
than the mansions of joy and festivity;
not that I am insensible to the comfort and happiness of those I love,
but if my friends are more near to me at one period than another,
it is when they are under the pressure of affliction.
Though I have deferred paying my visit of sympathy and affection in this way till now,
it was not because you were not daily in my remembrance;
but sorrow is not at all times communicative,
and I reflected that numerous would be the tributes
of condolence on the late mournful occasion:
mine might, perhaps, have been spared.
Of your loss I make estimation from what I have felt myself I have but twice
in my life had the satisfaction of any personal interaction with the dear deceased,
and these at six years`' distance from each other;
yet the lively impression of Richard Shackleton, left thereby on my mind,
is equalled by few indeed.
Few indeed possessed the powers of engaging and improving those around them,
by their society, like him.
His pleasant and communicative disposition opened his way with all ranks.
It sometimes happens that the great and the good are encircled by a forbidding gravity,
(I mean,
something distinct from religious authority,) but in him the love of the
Almighty was shown in kindness and good-will to those around him:
this gave him place wherever he came,
and his mind seemed equally fit for the vigour of reasoning,
the capacious range of science,
or to comfort and bring forward the hindmost of his brethren and sisters.
To me he was kind indeed, and there is a sweetness accompanies his memory in my mind,
hard to be described,
which I believe will be the general feeling where he was known
so that his loss will be as extensive as his acquaintance,
and lasting as the present generation: to you, dear friends,
it must be peculiarly trying,
--you who felt his paternal care,--you who felt the
cheering influence of his daily conversation,
and saw a thousand little acts of solicitude and kindness,
unknown to the eyes of his more distant friends.

I need not, I cannot enlarge.
Farewell: if the cloud of mourning overshadows your valley,
extend your prospect to that bright region, where your father, companion, and friend is,
I believe, gathered to the just of all generations; and where a few more days,
a few more tears, a few more struggles, and, if we follow the Light that guided him,
we shall rejoin his released spirit,
and be united to the redeemed and happy forever and ever!

[.signed-section-signature]
Thomas Wilkinson.
